export const configColumns = [
    {
      title: "yearProductPlan.project_id",
      subTitle: "项目id",
      dataIndex: "project_id",
      width: 160,
      align: "center",
    },
    {
      title: "yearProductPlan.project_name",
      subTitle: "项目名称",
      dataIndex: "project_name",
      width: 160,
      align: "center",
    },
    {
      title: "levelConstructor.name",
      subTitle: "姓名",
      dataIndex: "name",
      width: 160,
      align: "center",
    },
    {
      title: "levelConstructor.employee_number",
      subTitle: "员工编号",
      dataIndex: "employee_number",
      width: 160,
      align: "center",
    },
    {
      title: "levelConstructor.id_card",
      subTitle: "证件号",
      dataIndex: "id_card",
      width: 210,
      align: "center",
    },
    {
      title: "levelConstructor.province_id",
      subTitle: "省份id",
      dataIndex: "province_id",
      width: 160,
      align: "center",
    },
    {
      title: "levelConstructor.city_id",
      subTitle: "市id",
      dataIndex: "city_id",
      width: 160,
      align: "center",
    },
    {
      title: "levelConstructor.province_id",
      subTitle: "省份",
      dataIndex: "province_name",
      width: 160,
      align: "center",
    },
    {
      title: "levelConstructor.city_id",
      subTitle: "地市",
      dataIndex: "city_name",
      width: 160,
      align: "center",
    },
    {
      title: "levelConstructor.company",
      subTitle: "注册企业",
      dataIndex: "company",
      width: 160,
      align: "center",
    },
    {
      title: "levelConstructor.major",
      subTitle: "注册专业",
      dataIndex: "major",
      width: 160,
      align: "center",
    },
    {
      title: "levelConstructor.register_date_start",
      subTitle: "注册有效期开始",
      dataIndex: "register_date_start",
      width: 160,
      align: "center",
    },
    {
      title: "levelConstructor.register_date_end",
      subTitle: "注册有效期结束",
      dataIndex: "register_date_end",
      width: 160,
      align: "center",
    },
    {
      title: "levelConstructor.register_date_start",
      subTitle: "注册有效期开始",
      dataIndex: "register_date_start_str",
      width: 160,
      align: "center",
    },
    {
      title: "levelConstructor.register_date_end",
      subTitle: "注册有效期结束",
      dataIndex: "register_date_end_str",
      width: 160,
      align: "center",
    },
    {
      title: "levelConstructor.registration_number",
      subTitle: "注册编号",
      dataIndex: "registration_number",
      width: 160,
      align: "center",
    },
    {
      title: "levelConstructor.use_date_start",
      subTitle: "使用有效期（起始）",
      dataIndex: "use_date_start",
      width: 160,
      align: "center",
    },
    {
      title: "levelConstructor.use_date_end",
      subTitle: "使用有效期（截止）",
      dataIndex: "use_date_end",
      width: 160,
      align: "center",
    },
    {
      title: "levelConstructor.use_date_start",
      subTitle: "使用有效期（起始）",
      dataIndex: "use_date_start_str",
      width: 160,
      align: "center",
    },
    {
      title: "levelConstructor.use_date_end",
      subTitle: "使用有效期（截止）",
      dataIndex: "use_date_end_str",
      width: 160,
      align: "center",
    },
    {
      title: "levelConstructor.url",
      subTitle: "附件",
      dataIndex: "url",
      width: 160,
      align: "center",
    },
    
    {
      title: "wrokLicenseRegister.remark",
      subTitle: "备注",
      dataIndex: "remark",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.create_ts_str",
      subTitle: "创建时间",
      dataIndex: "create_ts_str",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.create_user_name",
      subTitle: "创建人名称",
      dataIndex: "create_user_name",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.modify_ts_str",
      subTitle: "修改时间",
      dataIndex: "modify_ts_str",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.modify_user_name",
      subTitle: "修改人名称",
      dataIndex: "modify_user_name",
      width: 160,
      align: "center",
    },
  ];
