export const configColumns = [
    {
      title: "compinfo.id",
      subTitle: "主键ID",
      dataIndex: "id",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.source",
      subTitle: "来源",
      dataIndex: "source",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.notice_no",
      subTitle: "通知单编号",
      dataIndex: "notice_no",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.level",
      subTitle: "级别(0:一般,1:严重不合格)",
      dataIndex: "level",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.level",
      subTitle: "级别(0:一般,1:严重不合格)",
      dataIndex: "level_str",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.description",
      subTitle: "不合格品描述",
      dataIndex: "description",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.event_time",
      subTitle: "发生时间",
      dataIndex: "event_time",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.event_time",
      subTitle: "发生时间",
      dataIndex: "event_time_str",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.event_location",
      subTitle: "发生地点",
      dataIndex: "event_location",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.disposal_result",
      subTitle: "处置结果",
      dataIndex: "disposal_result",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.remark",
      subTitle: "备注",
      dataIndex: "remark",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.depName",
      subTitle: "单位",
      dataIndex: "dep_code",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.depName",
      subTitle: "单位",
      dataIndex: "dep_name",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.form_maker_code",
      subTitle: "制单人编码",
      dataIndex: "form_maker_code",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.form_maker_name",
      subTitle: "制单人名称",
      dataIndex: "form_maker_name",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.form_make_time",
      subTitle: "制单时间",
      dataIndex: "form_make_time",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.form_make_time",
      subTitle: "制单时间",
      dataIndex: "form_make_time_str",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.form_make_tz",
      subTitle: "制单时区",
      dataIndex: "form_make_tz",
      width: 160,
      align: "center",
    },
  ];
