export const configColumns = [
    {
      title: "compinfo.id",
      subTitle: "主键ID",
      dataIndex: "id",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.brand_name",
      subTitle: "品牌名称",
      dataIndex: "brand_name",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.model",
      subTitle: "型号",
      dataIndex: "model",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.quantity",
      subTitle: "数量",
      dataIndex: "quantity",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.self_inspection_status",
      subTitle: "本月质量自检情况",
      dataIndex: "self_inspection_status",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.superior_inspection_status",
      subTitle: "本月上级机构质量检查情况",
      dataIndex: "superior_inspection_status",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.dep_code",
      subTitle: "dep_code",
      dataIndex: "dep_code",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.form_maker_code",
      subTitle: "制单人编码",
      dataIndex: "form_maker_code",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.form_maker_name",
      subTitle: "制单人名称",
      dataIndex: "form_maker_name",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.form_make_time",
      subTitle: "制单时间",
      dataIndex: "form_make_time",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.form_make_time",
      subTitle: "制单时间",
      dataIndex: "form_make_time_str",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.form_make_tz",
      subTitle: "制单时区",
      dataIndex: "form_make_tz",
      width: 160,
      align: "center",
    },
  ];
