export const configColumns = [
  {
    title: "Engineering.oil_refining",
    subTitle: "炼油化工(亿元)",
    dataIndex: "oil_refining",
    width: 160,
    align: "center",
  },
  {
    title: "Engineering.gas_storeage",
    subTitle: "油气储运(亿元)",
    dataIndex: "gas_storeage",
    width: 160,
    align: "center",
  },
  {
    title: "Engineering.gas_field",
    subTitle: "油气田地面(亿元)",
    dataIndex: "gas_field",
    width: 160,
    align: "center",
  },
  {
    title: "Engineering.dual_carbon_emerging",
    subTitle: "双碳新兴(亿元)",
    dataIndex: "dual_carbon_emerging",
    width: 160,
    align: "center",
  },
  {
    title: "Engineering.other_bets",
    subTitle: "其它业务(亿元)",
    dataIndex: "other_bets",
    width: 160,
    align: "center",
  },
  {
    title: "Engineering.id",
    subTitle: "序号",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "Indicators.basic_indicators",
    subTitle: "基础指标",
    dataIndex: "basic_indicators",
    width: 160,
    align: "center",
  },
  {
    title: "Indicators.strive_indicators",
    subTitle: "奋斗指标",
    dataIndex: "strive_indicators",
    width: 160,
    align: "center",
  },
  {
    title: "Indicators.finished_indicators",
    subTitle: "已完成指标",
    dataIndex: "finished_indicators",
    width: 160,
    align: "center",
  },
  {
    title: "Indicators.id",
    subTitle: "序号",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
];
