export const configColumns = [
  {
    title: "compinfo.id",
    subTitle: "自增主键",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.month",
    subTitle: "月份",
    dataIndex: "month",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contract_no",
    subTitle: "合同编号",
    dataIndex: "contract_no",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.accounting_subject",
    subTitle: "会计科目",
    dataIndex: "accounting_subject",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.accounting_subject_descripe",
    subTitle: "会计科目描述",
    dataIndex: "accounting_subject_descripe",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.funtional_scope",
    subTitle: "功能范围",
    dataIndex: "funtional_scope",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.funtional_scope_descripe",
    subTitle: "功能范围描述",
    dataIndex: "funtional_scope_descripe",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.beginning_month_amount",
    subTitle: "月初金额",
    dataIndex: "beginning_month_amount",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.debit_amount",
    subTitle: "借方",
    dataIndex: "debit_amount",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.creditor_amount",
    subTitle: "贷方",
    dataIndex: "creditor_amount",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.ending_month_amount",
    subTitle: "月末金额",
    dataIndex: "ending_month_amount",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.profit_center_code",
    subTitle: "利润中心编码",
    dataIndex: "profit_center_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.voucher_no",
    subTitle: "凭证编号",
    dataIndex: "voucher_no",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.voucher_detail",
    subTitle: "凭证抬头摘要",
    dataIndex: "voucher_detail",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.row_project",
    subTitle: "行项目",
    dataIndex: "row_project",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_ts",
    subTitle: "创建时间",
    dataIndex: "create_ts",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_tz",
    subTitle: "创建时区",
    dataIndex: "create_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_user_code",
    subTitle: "创建人编码",
    dataIndex: "create_user_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_user_name",
    subTitle: "创建人名称",
    dataIndex: "create_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_ts",
    subTitle: "修改时间",
    dataIndex: "modify_ts",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_tz",
    subTitle: "修改时区",
    dataIndex: "modify_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_user_code",
    subTitle: "修改人编码",
    dataIndex: "modify_user_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_user_name",
    subTitle: "修改人名称",
    dataIndex: "modify_user_name",
    width: 160,
    align: "center",
  },
];
