export const configColumns = [
  {
    title: "compinfo.id",
    subTitle: "自增主键",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.up_wbs_name",
    subTitle: "分公司",
    dataIndex: "up_wbs_name",
    width: 160,
    align: "center",
  },
  {
    "title": "contract.id",
    "subTitle": "收入合同id",
    "dataIndex": "contract_income_id",
    "width": 160,
    "align": "center"
  },
  {
    "title": "contract.contract_no2",
    "subTitle": "合同系统2.0合同编号",
    "dataIndex": "contract_no",
    "width": 200,
    "align": "center"
  },
  {
    "title": "contract.contract_no2",
    "subTitle": "合同系统2.0合同编号",
    "dataIndex": "contract_no",
    "width": 200,
    "align": "center"
  },
  {
    title: "compinfo.dep_name",
    subTitle: "项目部",
    dataIndex: "dep_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.wbs_define_code",
    subTitle: "项目定义",
    dataIndex: "wbs_define_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.wbs_define_name",
    subTitle: "项目名称",
    dataIndex: "wbs_define_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.profit_center_code",
    subTitle: "利润中心",
    dataIndex: "profit_center_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.owner_group",
    subTitle: "工程所属集团",
    dataIndex: "owner_group",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.owner_group",
    subTitle: "工程所属集团",
    dataIndex: "owner_group_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.client_name",
    subTitle: "客户名称",
    dataIndex: "client_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contract_start_date",
    subTitle: "合同开工时间",
    dataIndex: "contract_start_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.actual_start_date",
    subTitle: "实际开工时间",
    dataIndex: "actual_start_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contract_end_date",
    subTitle: "计划完工时间",
    dataIndex: "contract_end_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.actual_end_date",
    subTitle: "实际完工时间",
    dataIndex: "actual_end_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contract_say_price",
    subTitle: "合同额(含税价)",
    dataIndex: "contract_say_price",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contract_un_say_price",
    subTitle: "合同额(不含税价)",
    dataIndex: "contract_un_say_price",
    width: 160,
    align: "center",
  },

  {
    title: "compinfo.engineering_calc_finish_amount",
    subTitle: "工程累计完工进度",
    dataIndex: "engineering_calc_finish_amount",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.profitAndLoss.project_status",
    subTitle: "工程状态",
    dataIndex: "project_status",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_status",
    subTitle: "工程状态",
    dataIndex: "project_status_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.settlement_status",
    subTitle: "结算状态",
    dataIndex: "settlement_status",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.settlement_status",
    subTitle: "结算状态",
    dataIndex: "settlement_status_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_level",
    subTitle: "项目级别",
    dataIndex: "project_level",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_level",
    subTitle: "项目级别",
    dataIndex: "project_level_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.company_supervision_user",
    subTitle: "公司督导负责人",
    dataIndex: "company_supervision_user",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.sub_company_manager",
    subTitle: "分公司经理",
    dataIndex: "sub_company_manager",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.sub_company_supervision_user",
    subTitle: "分公司督导负责人",
    dataIndex: "sub_company_supervision_user",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_manager",
    subTitle: "项目经理",
    dataIndex: "project_manager",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_sub_engine_manager",
    subTitle: "项目工程副经理",
    dataIndex: "project_sub_engine_manager",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_sub_settlement_manager",
    subTitle: "项目经营副经理",
    dataIndex: "project_sub_settlement_manager",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_finance_user",
    subTitle: "项目财务负责人",
    dataIndex: "project_finance_user",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark",
    subTitle: "备注",
    dataIndex: "remark",
    width: 160,
    align: "center",
  },
];
