// 承包商合同信息配置
export const contractInfoConfig: any[] = [
  {
    label: '合同号：',
    key: 'contract_no',
    labelWidth: 80,
  },
  {
    label: '支出合同名称：',
    key: 'contract_out_name',
    labelWidth: 100,
  },
  {
    label: '合同金额（含税万元）：',
    key: 'contract_say_price',
    labelWidth: 80,
  },
  {
    label: '合同开工日期：',
    key: 'contract_start_date_format',
    labelWidth: 110,
  },
  {
    label: '合同完工日期：',
    key: 'contract_end_date_format',
    labelWidth: 110,
  },
];

// 基本条件评价配置列
export const basicCols: any = [
  { title: '序号', dataIndex: 'RowNumber', width: 80 },
  { title: '评价项目', dataIndex: 'score_standard' },
  {
    title: '是否满足',
    formField: {
      name: (row: any) => `basic_${row.id}_satisfied`,
      type: 'radio',
      options: [
        { label: '是', value: '1' },
        { label: '否', value: '0' },
      ],
      rules: [{ required: true, message: '请选择' }],
    },
  },
];
export const configColumns = [
    {
      title: "compinfo.id",
      subTitle: "主键ID",
      dataIndex: "id",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.id",
      subTitle: "主键ID",
      dataIndex: "contract_out_id",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.code",
      subTitle: "编码",
      dataIndex: "code",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.wbs_code",
      subTitle: "项目部",
      dataIndex: "wbs_code",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.report_date",
      subTitle: "填报日期",
      dataIndex: "report_date",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.report_date",
      subTitle: "填报日期",
      dataIndex: "report_date_str",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.branchCompCode",
      subTitle: "分公司",
      dataIndex: "branch_comp_code",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.branchCompCode",
      subTitle: "分公司",
      dataIndex: "branch_comp_name",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.depCode",
      subTitle: "项目经理部",
      dataIndex: "dep_code",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.depCode",
      subTitle: "项目经理部",
      dataIndex: "dep_name",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.contractor_name",
      subTitle: "承包商名称",
      dataIndex: "contractor_name",
      width: 210,
      align: "center",
    },
    {
      title: "compinfo.contractor_manager",
      subTitle: "承包商项目经理",
      dataIndex: "contractor_manager",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.contractor_manager",
      subTitle: "承包商项目经理",
      dataIndex: "contractor_manager_name",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.register_number",
      subTitle: "承包商编码",
      dataIndex: "register_number",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.contact_phone",
      subTitle: "联系电话",
      dataIndex: "contact_phone",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.contract_name",
      subTitle: "合同名称",
      dataIndex: "contract_name",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.contract_amount",
      subTitle: "合同总额（元）",
      dataIndex: "contract_amount",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.contract_start_date",
      subTitle: "合同起始日期",
      dataIndex: "contract_start_date",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.contract_end_date",
      subTitle: "合同结束日期",
      dataIndex: "contract_end_date",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.contract_start_date",
      subTitle: "合同起始日期",
      dataIndex: "contract_start_date_str",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.contract_end_date",
      subTitle: "合同结束日期",
      dataIndex: "contract_end_date_str",
      width: 160,
      align: "center",
    },
    {
      title: "scheduleManagement.annual_completed_amount_when",
      subTitle: "当年完成合同额（万元）",
      dataIndex: "annual_completed_amount",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.project_category",
      subTitle: "项目类别",
      dataIndex: "project_category",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.project_category",
      subTitle: "项目类别",
      dataIndex: "project_category_name",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.form_maker_code",
      subTitle: "制单人编码",
      dataIndex: "form_maker_code",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.form_maker_name",
      subTitle: "制单人名称",
      dataIndex: "form_maker_name",
      width: 160,
      align: "center",
    },

    {
      title: "compinfo.project_principal",
      subTitle: "项目部考核负责人",
      dataIndex: "project_principal",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.contract_dep_out_score",
      subTitle: "项目部考核得分",
      dataIndex: "contract_dep_out_score",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.contract_out_score",
      subTitle: "分公司考核得分",
      dataIndex: "contract_out_score",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.contract_out_principal",
      subTitle: "分公司考核负责人",
      dataIndex: "contract_out_principal",
      width: 210,
      align: "center",
    },
    {
      title: "compinfo.contract_out_reason",
      subTitle: "分公司考核扣分原因",
      dataIndex: "contract_out_reason",
      width: 210,
      align: "center",
    },

    {
      title: "compinfo.belong_year",
      subTitle: "所属年份",
      dataIndex: "belong_year",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.is_publish",
      subTitle: "是否发布",
      dataIndex: "is_publish",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.create_ts_str",
      subTitle: "创建时间",
      dataIndex: "create_ts_format",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.create_user_name",
      subTitle: "创建人名称",
      dataIndex: "create_user_name",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.modify_ts_str",
      subTitle: "修改时间",
      dataIndex: "modify_ts_format",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.modify_user_name",
      subTitle: "修改人名称",
      dataIndex: "modify_user_name",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.action",
      subTitle: "评价",
      dataIndex: "action",
      width: 160,
      align: "center",
    },
    {
      title: "scheduleManagement.contract_no",
      subTitle: "合同号",
      dataIndex: "contract_no",
      width: 160,
      align: "center",
    },
    {
      title: "scheduleManagement.contract_out_name",
      subTitle: "支出合同名称",
      dataIndex: "contract_out_name",
      width: 160,
      align: "center",
    },
    {
      title: "scheduleManagement.contract_start_date_format",
      subTitle: "合同金额（含税）",
      dataIndex: "contract_start_date_format",
      width: 210,
      align: "center",
    },
    {
      title: "scheduleManagement.contract_end_date",
      subTitle: "合同完工日期",
      dataIndex: "contract_end_date_format",
      width: 160,
      align: "center",
    },
    {
      title: "scheduleManagement.branch_score",
      subTitle: "分公司考核得分",
      dataIndex: "branch_score",
      width: 160,
      align: "center",
    },
    
    {
      title: "scheduleManagement.project_score_str",
      subTitle: "得分",
      dataIndex: "project_score",
      width: 160,
      align: "center",
    },
    {
      title: "scheduleManagement.project_score_str",
      subTitle: "得分",
      dataIndex: "project_score",
      width: 160,
      align: "center",
    },
    {
      title: "scheduleManagement.comp_score",
      subTitle: "公司得分",
      dataIndex: "comp_score",
      width: 160,
      align: "center",
    },
    {
      title: "scheduleManagement.comp_principal",
      subTitle: "公司考核负责人",
      dataIndex: "comp_principal",
      width: 210,
      align: "center",
    },
    {
      title: "scheduleManagement.comp_reason",
      subTitle: "公司考核扣分原因",
      dataIndex: "comp_reason",
      width: 210,
      align: "center",
    },
    {
      title: "scheduleManagement.evaluation",
      subTitle: "评估结果",
      dataIndex: "evaluation",
      width: 210,
      align: "center",
    },
    
  ];
