export const configColumns = [
  {
    title: "InspectorSeniorityApply.sub_comp_code",
    subTitle: "分公司",
    dataIndex: "sub_comp_name",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.dep_code",
    subTitle: "项目部",
    dataIndex: "dep_name",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.name",
    subTitle: "姓名",
    dataIndex: "name",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.gender",
    subTitle: "性别",
    dataIndex: "gender",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.birth_date",
    subTitle: "出生日期",
    dataIndex: "birth_date",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.job",
    subTitle: "职务",
    dataIndex: "job",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.job_title",
    subTitle: "职称",
    dataIndex: "job_title",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.cert_no",
    subTitle: "证书编号",
    dataIndex: "cert_no",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_category",
    subTitle: "项目类别",
    dataIndex: "project_category",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.first_date",
    subTitle: "首次取得特种设备作业人员取证时间",
    dataIndex: "first_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.exam_type",
    subTitle: "考试性质",
    dataIndex: "exam_type",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.valid_project",
    subTitle: "证书有效项目",
    dataIndex: "valid_project",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.valid_date",
    subTitle: "证书有效日期",
    dataIndex: "valid_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.cer_approval_date",
    subTitle: "证书批准日期",
    dataIndex: "cer_approval_date",
    width: 160,
    align: "center",
  },
  
  {
    title: "compinfo.steel_seal_no",
    subTitle: "钢印号",
    dataIndex: "steel_seal_no",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.work_date",
    subTitle: "参加工作时间",
    dataIndex: "work_date",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.education",
    subTitle: "文化程度",
    dataIndex: "education",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.employee_no",
    subTitle: "员工编号",
    dataIndex: "employee_no",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.graduation_school",
    subTitle: "毕业院校",
    dataIndex: "graduation_school",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.major",
    subTitle: "所学专业",
    dataIndex: "major",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.department",
    subTitle: "所在单位部门",
    dataIndex: "department",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.post",
    subTitle: "现从事岗位",
    dataIndex: "post",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.train_date",
    subTitle: "培训时间",
    dataIndex: "train_date",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.train_grade",
    subTitle: "培训成绩",
    dataIndex: "train_grade",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.application_project",
    subTitle: "申请操作项目",
    dataIndex: "application_project",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.phone",
    subTitle: "联系电话",
    dataIndex: "phone",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.on_duty",
    subTitle: "在岗状态",
    dataIndex: "on_duty",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.related_work_date",
    subTitle: "从事质检或相关工作时间",
    dataIndex: "related_work_date",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.apply_major",
    subTitle: "申请检查专业",
    dataIndex: "apply_major",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.job_resume",
    subTitle: "工作简历",
    dataIndex: "job_resume",
    width: 210,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.approval_date",
    subTitle: "审批时间",
    dataIndex: "approval_date",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.remark",
    subTitle: "备注",
    dataIndex: "remark",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_ts_str",
    subTitle: "创建时间",
    dataIndex: "create_ts_format",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_ts_str",
    subTitle: "创建时间",
    dataIndex: "create_ts_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_user_name",
    subTitle: "创建人名称",
    dataIndex: "create_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_ts_str",
    subTitle: "修改时间",
    dataIndex: "modify_ts_format",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_ts_str",
    subTitle: "修改时间",
    dataIndex: "modify_ts_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_user_name",
    subTitle: "修改人名称",
    dataIndex: "modify_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "levelConstructor.url",
    subTitle: "附件",
    dataIndex: "url",
    width: 160,
    align: "center",
  },
  {
    title: "common.status",
    subTitle: "审批状态",
    dataIndex: "approval_status",
    width: 160,
    align: "center",
  },

  {
    title: "wrokLicenseRegister.create_ts_str",
    subTitle: "创建时间",
    dataIndex: "create_ts_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_ts_str",
    subTitle: "创建时间",
    dataIndex: "create_ts_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_user_name",
    subTitle: "创建人名称",
    dataIndex: "create_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_ts_str",
    subTitle: "修改时间",
    dataIndex: "modify_ts_format",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_ts_str",
    subTitle: "修改时间",
    dataIndex: "modify_ts_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_user_name",
    subTitle: "修改人名称",
    dataIndex: "modify_user_name",
    width: 160,
    align: "center",
  },
];
/**
   * 工作简历表格列配置
   */
export const resumeColumns = [
  {
    title: '开始时间',
    dataIndex: 'time_start',
    key: 'time_start',
    width: 120,
    render: (text: string) => text || '-',
  },
  {
    title: '结束时间',
    dataIndex: 'time_end',
    key: 'time_end',
    width: 120,
    render: (text: string) => text || '-',
  },
  {
    title: '工作单位',
    dataIndex: 'company',
    key: 'company',
    width: 200,
    render: (text: string) => text || '-',
  },
  {
    title: '工作经历和业绩',
    dataIndex: 'experience',
    key: 'experience',
    width: 300,
    render: (text: string) => text || '-',
  },
  
];
