export const configColumns = [
  {
    title: "compinfo.id",
    subTitle: "自增主键",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.year",
    subTitle: "年",
    dataIndex: "year",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.wbs_define_code",
    subTitle: "项目定义",
    dataIndex: "wbs_define_code",
    width: 160,
    align: "center",
  },
  {
    title: "PerformanceLedger.contract_type",
    subTitle: "合同类型",
    dataIndex: "contract_type_str",
    width: 160,
    align: "center",
  },
  {
    title: "PerformanceLedger.contract_type",
    subTitle: "合同类型",
    dataIndex: "contract_type",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.wbs_define_name",
    subTitle: "项目(合同 合同名称)",
    dataIndex: "wbs_define_name",
    width: 160,
    align: "center",
  },

  {
    title: "compinfo.contract_sign_year",
    subTitle: "合同签订年度",
    dataIndex: "contract_sign_year_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contract_sign_year",
    subTitle: "合同签订年度",
    dataIndex: "contract_sign_year",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.inOrOut",
    subTitle: "境内/境外",
    dataIndex: "inOrOut",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.relative_person_code",
    subTitle: "合同相对人(往来单位编码)",
    dataIndex: "relative_person_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.owner_name",
    subTitle: "业主名称(合同 甲方单位名称)",
    dataIndex: "owner_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.inside_outside_group",
    subTitle: "集团内外",
    dataIndex: "inside_outside_group",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.income_method",
    subTitle: "收入确认方式",
    dataIndex: "income_method",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_location",
    subTitle: "项目所在地",
    dataIndex: "project_location",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contract_say_price",
    subTitle: "初始金额(合同 含税合同价)",
    dataIndex: "contract_say_price",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.after_change_price_en",
    subTitle: "变更后累计金额-美元",
    dataIndex: "after_change_price_en",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.rate",
    subTitle: "汇率",
    dataIndex: "rate",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.change_price_zh",
    subTitle: "变更后金额-元人民币",
    dataIndex: "change_price_zh",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.hetong_shouru_cha",
    subTitle: "合同额与收入差",
    dataIndex: "hetong_shouru_cha",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.add_rate",
    subTitle: "增值税率",
    dataIndex: "add_rate",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.is_finish_no_close",
    subTitle: "是否为已完工未关闭合同项目",
    dataIndex: "is_finish_no_close",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.is_finish_no_close",
    subTitle: "是否为已完工未关闭合同项目",
    dataIndex: "is_finish_no_close_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.in_company_jia_name",
    subTitle: "公司内部项目甲方名称",
    dataIndex: "in_company_jia_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contract_sign_date",
    subTitle: "合同签订日期",
    dataIndex: "contract_sign_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contract_sign_date",
    subTitle: "合同签订日期",
    dataIndex: "contract_sign_date_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.profitLoss.contract_start_date",
    subTitle: "项目开工日期(合同 合同开工日期)",
    dataIndex: "contract_start_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.profitLoss.contract_start_date",
    subTitle: "项目开工日期(合同 合同开工日期)",
    dataIndex: "contract_start_date_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contract_area",
    subTitle: "合同约定工期(合同 完工-开工)",
    dataIndex: "contract_area",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_jiexie_date",
    subTitle: "项目机械完工时间",
    dataIndex: "project_jiexie_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_jiexie_date",
    subTitle: "项目机械完工时间",
    dataIndex: "project_jiexie_date_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_finish_date",
    subTitle: "项目终交时间",
    dataIndex: "project_finish_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_finish_date",
    subTitle: "项目终交时间",
    dataIndex: "project_finish_date_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.company_a_b",
    subTitle: "当年公司AB类标注",
    dataIndex: "company_a_b",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.expected_revenue_price",
    subTitle: "预计收入",
    dataIndex: "expected_revenue_price",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.expected_cost",
    subTitle: "预计成本",
    dataIndex: "expected_cost",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.gross_profit",
    subTitle: "毛利",
    dataIndex: "gross_profit",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.operating_revenue",
    subTitle: "营业收入",
    dataIndex: "operating_revenue",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.cost_price",
    subTitle: "成本费用",
    dataIndex: "cost_price",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.finance_price",
    subTitle: "财务费用",
    dataIndex: "finance_price",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.profit_total_price",
    subTitle: "利润总额",
    dataIndex: "profit_total_price",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.income_tax",
    subTitle: "所得税",
    dataIndex: "income_tax",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.net_profix",
    subTitle: "净利润",
    dataIndex: "net_profix",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.net_profix_rate",
    subTitle: "净利润率",
    dataIndex: "net_profix_rate",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.profit_center_code",
    subTitle: "利润中心",
    dataIndex: "profit_center_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark",
    subTitle: "备注",
    dataIndex: "remark",
    width: 160,
    align: "center",
  },
];
