
export const configColumns = [
  {
    subTitle: "compinfo.up_wbs_name",
    title: "分公司",
    dataIndex: "up_wbs_name",
    width: 160,
    align: "center",
  },
  {
    subTitle: "compinfo.dep_name",
    title: "项目部",
    dataIndex: "dep_name",
    width: 160,
    align: "center",
  },
  {
    subTitle: "compinfo.wbs_define_code",
    title: "项目定义",
    dataIndex: "wbs_define_code",
    width: 160,
    align: "center",
  },
  {
    subTitle: "compinfo.profit_center_code",
    title: "利润中心",
    dataIndex: "profit_center_code",
    width: 160,
    align: "center",
  },
  {
    subTitle: "PerformanceLedger.contract_type",
    title: "合同类型",
    dataIndex: "contract_type_str",
    width: 160,
    align: "center",
  },
  // {
  //   subTitle: "PerformanceLedger.contract_type",
  //   title: "合同类型",
  //   dataIndex: "contract_type",
  //   width: 160,
  //   align: "center",
  // },
  {
    subTitle: "compinfo.wbs_define_name",
    title: "项目",
    dataIndex: "wbs_define_name",
    width: 160,
    align: "center",
  },
  {
    subTitle: "compinfo.contract_sign_year",
    title: "合同签订年度",
    dataIndex: "contract_sign_year",
    width: 160,
    align: "center",
  },
  {
    subTitle: "compinfo.inOrOut",
    title: "境内/境外",
    dataIndex: "inOrOut",
    width: 160,
    align: "center",
  },
  {
    subTitle: "compinfo.relative_person_code",
    title: "合同相对人",
    dataIndex: "relative_person_code",
    width: 160,
    align: "center",
  },
  {
    subTitle: "compinfo.owner_name",
    title: "业主名称",
    dataIndex: "owner_name",
    width: 160,
    align: "center",
  },
  {
    subTitle: "compinfo.inside_outside_group",
    title: "集团内外",
    dataIndex: "inside_outside_group",
    width: 160,
    align: "center",
  },
  {
    subTitle: "compinfo.income_method",
    title: "收入确认方式",
    dataIndex: "income_method",
    width: 160,
    align: "center",
  },
  {
    subTitle: "compinfo.project_location",
    title: "项目所在地",
    dataIndex: "project_location",
    width: 160,
    align: "center",
  },
  {
    title: ' 合同额（美元需折成人民币) （含税金额，单位元）',
    children: [
      {
        subTitle: "compinfo.contract_say_price",
        title: "初始金额",
        dataIndex: "contract_say_price",
        width: 160,
        align: "center",
      },
      {
        subTitle: "compinfo.after_change_price_en",
        title: "变更后累计金额-美元",
        dataIndex: "after_change_price_en",
        width: 160,
        align: "center",
      },
      {
        subTitle: "compinfo.rate",
        title: "汇率",
        dataIndex: "rate",
        width: 160,
        align: "center",
      },
      {
        subTitle: "compinfo.change_price_zh",
        title: "变更后金额-元人民币",
        dataIndex: "change_price_zh",
        width: 160,
        align: "center",
      },
    ]
  },
  {
    subTitle: "compinfo.hetong_shouru_cha",
    title: "合同额与收入差",
    dataIndex: "hetong_shouru_cha",
    width: 160,
    align: "center",
  },
  {
    subTitle: "compinfo.add_rate",
    title: "增值税率",
    dataIndex: "add_rate",
    width: 160,
    align: "center",
  },
  // {
  //   subTitle: "compinfo.is_finish_no_close",
  //   title: "是否为已完工未关闭合同项目",
  //   dataIndex: "is_finish_no_close",
  //   width: 160,
  //   align: "center",
  // },
  {
    subTitle: "compinfo.is_finish_no_close",
    title: "是否为已完工未关闭合同项目",
    dataIndex: "is_finish_no_close_str",
    width: 160,
    align: "center",
  },
  {
    subTitle: "compinfo.in_company_jia_name",
    title: "公司内部项目甲方名称",
    dataIndex: "in_company_jia_name",
    width: 160,
    align: "center",
  },
  {
    subTitle: "compinfo.contract_sign_date",
    title: "合同签订日期",
    dataIndex: "contract_sign_date_str",
    width: 160,
    align: "center",
  },
  {
    subTitle: "compinfo.contract_start_date",
    title: "项目开工日期",
    dataIndex: "contract_start_date_str",
    width: 160,
    align: "center",
  },
  {
    subTitle: "compinfo.contract_area",
    title: "合同约定工期",
    dataIndex: "contract_area",
    width: 160,
    align: "center",
  },
  {
    subTitle: "compinfo.project_jiexie_date",
    title: "项目机械完工时间",
    dataIndex: "project_jiexie_date_str",
    width: 160,
    align: "center",
  },
  {
    subTitle: "compinfo.project_finish_date",
    title: "项目终交时间",
    dataIndex: "project_finish_date_str",
    width: 160,
    align: "center",
  },
  {
    subTitle: "compinfo.company_a_b",
    title: "当年公司AB类标注",
    dataIndex: "company_a_b",
    width: 160,
    align: "center",
  },
  {
    title: '项目责任预算',
    children: [
      {
        subTitle: "compinfo.expected_revenue_price",
        title: "预计收入",
        dataIndex: "expected_revenue_price",
        width: 160,
        align: "center",
      },
      {
        subTitle: "compinfo.expected_cost",
        title: "预计成本",
        dataIndex: "expected_cost",
        width: 160,
        align: "center",
      },
      {
        subTitle: "compinfo.gross_profit",
        title: "毛利",
        dataIndex: "gross_profit",
        width: 160,
        align: "center",
      },
    ]
  },
  {
    title: '合计（万元人民币）',
    children: [
      {
        subTitle: "compinfo.operating_revenue",
        title: "营业收入",
        dataIndex: "operating_revenue",
        width: 160,
        align: "center",
      },
      {
        subTitle: "compinfo.cost_price",
        title: "成本费用",
        dataIndex: "cost_price",
        width: 160,
        align: "center",
      },
      {
        subTitle: "compinfo.finance_price",
        title: "财务费用",
        dataIndex: "finance_price",
        width: 160,
        align: "center",
      },
      {
        subTitle: "compinfo.profit_total_price",
        title: "利润总额",
        dataIndex: "profit_total_price",
        width: 160,
        align: "center",
      },
      {
        subTitle: "compinfo.income_tax",
        title: "所得税",
        dataIndex: "income_tax",
        width: 160,
        align: "center",
      },
      {
        subTitle: "compinfo.net_profix",
        title: "净利润",
        dataIndex: "net_profix",
        width: 160,
        align: "center",
      },
      {
        subTitle: "compinfo.net_profix_rate",
        title: "净利润率",
        dataIndex: "net_profix_rate",
        width: 160,
        align: "center",
      },
    ]
  },
];
