export const configColumns = [
    {
      title: "yearProductPlan.belong_year",
      subTitle: "所属年份",
      dataIndex: "belong_year",
      width: 160,
      align: "center",
    },
    {
      title: "yearProductPlan.project_id",
      subTitle: "项目id",
      dataIndex: "project_id",
      width: 160,
      align: "center",
    },
    {
      title: "yearProductPlan.project_name",
      subTitle: "项目名称",
      dataIndex: "project_name",
      width: 160,
      align: "center",
    },
    {
      title: "yearProductPlan.contract_start_date",
      subTitle: "合同开工日期",
      dataIndex: "contract_start_date",
      width: 160,
      align: "center",
    },
    {
      title: "yearProductPlan.contract_end_date",
      subTitle: "合同完工工期",
      dataIndex: "contract_end_date",
      width: 160,
      align: "center",
    },
    {
      title: "yearProductPlan.contract_start_date",
      subTitle: "合同开工工期",
      dataIndex: "contract_start_date_format",
      width: 160,
      align: "center",
    },
    {
      title: "yearProductPlan.contract_end_date",
      subTitle: "合同完工工期",
      dataIndex: "contract_end_date_format",
      width: 160,
      align: "center",
    },
    {
      title: "yearProductPlan.actual_start_date",
      subTitle: "实际开工日期",
      dataIndex: "actual_start_date",
      width: 160,
      align: "center",
    },
    {
      title: "yearProductPlan.plan_end_date",
      subTitle: "预计完工日期",
      dataIndex: "plan_end_date",
      width: 160,
      align: "center",
    },
    {
      title: "scheduleManagement.plan_finish_date",
      subTitle: "预计完工日期",
      dataIndex: "plan_finish_date",
      width: 160,
      align: "center",
    },
    
    {
      title: "yearProductPlan.actual_start_date",
      subTitle: "实际开工日期",
      dataIndex: "actual_start_date_format",
      width: 160,
      align: "center",
    },
    {
      title: "yearProductPlan.plan_end_date",
      subTitle: "预计完工日期",
      dataIndex: "plan_end_date_format",
      width: 160,
      align: "center",
    },
    {
      title: "yearProductPlan.plan_output_value",
      subTitle: "年计划产值（万元）",
      dataIndex: "plan_output_value",
      width: 210,
      align: "center",
    },
    {
      title: "yearProductPlan.progress_description",
      subTitle: "形象进度描述",
      dataIndex: "progress_description",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.remark",
      subTitle: "备注",
      dataIndex: "remark",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.create_ts_str",
      subTitle: "创建时间",
      dataIndex: "create_ts_format",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.create_user_name",
      subTitle: "创建人名称",
      dataIndex: "create_user_name",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.modify_ts_str",
      subTitle: "修改时间",
      dataIndex: "modify_ts_format",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.modify_user_name",
      subTitle: "修改人名称",
      dataIndex: "modify_user_name",
      width: 160,
      align: "center",
    },
  ];
