export const configColumns = [
  {
    title: "InspectorSeniorityApply.sub_comp_code",
    subTitle: "分公司",
    dataIndex: "sub_comp_name",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.dep_code",
    subTitle: "项目部",
    dataIndex: "dep_name",
    width: 160,
    align: "center",
  },
  {
    title: "monitoringMeasuring.year",
    subTitle: "年份",
    dataIndex: "year",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.approval_date",
    subTitle: "审批时间",
    dataIndex: "approval_date",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.remark",
    subTitle: "备注",
    dataIndex: "remark",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_ts_str",
    subTitle: "创建时间",
    dataIndex: "create_ts_format",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_ts_str",
    subTitle: "创建时间",
    dataIndex: "create_ts_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_user_name",
    subTitle: "创建人名称",
    dataIndex: "create_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_ts_str",
    subTitle: "修改时间",
    dataIndex: "modify_ts_format",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_ts_str",
    subTitle: "修改时间",
    dataIndex: "modify_ts_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_user_name",
    subTitle: "修改人名称",
    dataIndex: "modify_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "levelConstructor.url",
    subTitle: "附件",
    dataIndex: "url",
    width: 160,
    align: "center",
  },
  {
    title: "common.status",
    subTitle: "审批状态",
    dataIndex: "approval_status",
    width: 160,
    align: "center",
  },

  {
    title: "wrokLicenseRegister.monitor",
    subTitle: "监控人",
    dataIndex: "monitor",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.maintainer",
    subTitle: "维护人员",
    dataIndex: "maintainer",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.maintainer",
    subTitle: "维护人员",
    dataIndex: "maintainer_names",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.monitor",
    subTitle: "监控人",
    dataIndex: "monitor_name",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.monitoring_status",
    subTitle: "监控状况",
    dataIndex: "monitoring_status",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.monitoring_status",
    subTitle: "监控状况",
    dataIndex: "monitoring_status_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.evaluation_date",
    subTitle: "评价日期",
    dataIndex: "evaluation_date",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.qualification",
    subTitle: "资质名称",
    dataIndex: "qualification",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.qualification_date",
    subTitle: "资质到期时间",
    dataIndex: "qualification_date",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.qualification_url",
    subTitle: "资质附件",
    dataIndex: "qualification_url",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.full_name_ledger",
    subTitle: "试验室名称",
    dataIndex: "lab_full_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.lab_nature_ledger",
    subTitle: "性质",
    dataIndex: "lab_nature",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.qualification_change",
    subTitle: "实验室资质范围、有效期的变化情况",
    dataIndex: "qualification_change",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.data_reliability",
    subTitle: "数据可靠性",
    dataIndex: "data_reliability",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.service_quality",
    subTitle: "服务质量",
    dataIndex: "service_quality",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.contract_performance",
    subTitle: "合同履约",
    dataIndex: "contract_performance",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.reviewer",
    subTitle: "审查人姓名",
    dataIndex: "reviewer",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.review_date",
    subTitle: "审查日期",
    dataIndex: "review_date",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.review_unit",
    subTitle: "审查单位",
    dataIndex: "review_unit",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.is_choose",
    subTitle: "下年度是否选用",
    dataIndex: "is_choose",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.qualifications",
    subTitle: "外委实验室的资质证名称及相应有效期",
    dataIndex: "qualifications",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.qualification_scope",
    subTitle: "资质范围",
    dataIndex: "qualification_scope",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.business_license_no",
    subTitle: "外委实验室营业执照号码",
    dataIndex: "business_license_no",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.lab_responsible_person",
    subTitle: "外委实验室负责人",
    dataIndex: "lab_responsible_person",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.province",
    subTitle: "所在省份",
    dataIndex: "province",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.province",
    subTitle: "所在省份",
    dataIndex: "province_name",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.city",
    subTitle: "所在地市",
    dataIndex: "city",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.city",
    subTitle: "所在地市",
    dataIndex: "city_name",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.address",
    subTitle: "详细地址",
    dataIndex: "address",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.lab_phone",
    subTitle: "外委实验室联系电话",
    dataIndex: "lab_phone",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.geo_traffic",
    subTitle: "地理位置、交通情况",
    dataIndex: "geo_traffic",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.entrusted_projects_ledger",
    subTitle: "监控试验项目",
    dataIndex: "entrusted_projects",
    width: 160,
    align: "center",
  },
];