
type ColumnType = {
  "title": string,
  "subTitle": string,
  "dataIndex": string,
  "width": number,
  "align": string,
}
export const configColumns: ColumnType[] = [
  {
    title: "compinfo.form_no",
    subTitle: "序号",
    dataIndex: "form_no",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_no",
    subTitle: "序号",
    dataIndex: "RowNumber",
    width: 160,
    align: "center",
  },
  {
    title: "提报单位",
    subTitle: "提报单位",
    dataIndex: "wbs_code",
    width: 160,
    align: "center",
  },
  {
    title: "提报单位",
    subTitle: "提报单位",
    dataIndex: "wbs_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_loc_type",
    subTitle: "项目属地(0:境内,1:境外)",
    dataIndex: "project_loc_type",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_loc_type",
    subTitle: "项目属地",
    dataIndex: "project_loc_type_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.report_category",
    subTitle: "报告类别(0:工程分包,1:工程物资,2:工程服务)",
    dataIndex: "report_category",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.report_category",
    subTitle: "报告类别",
    dataIndex: "report_category_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.pre_audit_no",
    subTitle: "预审编号",
    dataIndex: "pre_audit_no",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.decision_meeting",
    subTitle: "决策会(0:MC,1:TC)",
    dataIndex: "decision_meeting",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.decision_meeting",
    subTitle: "决策会",
    dataIndex: "decision_meeting_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.topic_name",
    subTitle: "议题名称",
    dataIndex: "topic_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.batch_number",
    subTitle: "批次(数字格式)",
    dataIndex: "batch_number",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark",
    subTitle: "备注",
    dataIndex: "remark",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.file_url",
    subTitle: "附件",
    dataIndex: "file_url",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.submit_target_topic",
    subTitle: "向公司招标委员会报送+议题名称",
    dataIndex: "submit_target_topic",
    width: 280,
    align: "center",
  },
  {
    title: "compinfo.project_overview",
    subTitle: "项目概述",
    dataIndex: "project_overview",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_name",
    subTitle: "项目名称",
    dataIndex: "project_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.is_confidential",
    subTitle: "涉密(0:是,1:否)",
    dataIndex: "is_confidential",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.is_confidential",
    subTitle: "涉密",
    dataIndex: "is_confidential_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_level",
    subTitle: "项目级别(0:A,1:B,2:C,3:D)",
    dataIndex: "project_level",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_level",
    subTitle: "项目级别",
    dataIndex: "project_level_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_code",
    subTitle: "项目编号",
    dataIndex: "project_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.owner_name",
    subTitle: "业主名称",
    dataIndex: "owner_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_attr",
    subTitle: "项目属性(0:系统内项目,1:系统外项目,2:其他项目,3:集团重点项目,4:非重点项目)",
    dataIndex: "project_attr",
    width: 280,
    align: "center",
  },
  {
    title: "compinfo.project_attr",
    subTitle: "项目属性",
    dataIndex: "project_attr_str",
    width: 280,
    align: "center",
  },
  {
    title: "compinfo.design_unit",
    subTitle: "设计单位",
    dataIndex: "design_unit",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.supervision_unit",
    subTitle: "监理单位",
    dataIndex: "supervision_unit",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.eng_summary",
    subTitle: "工程概述",
    dataIndex: "eng_summary",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.handover_time",
    subTitle: "中交时间",
    dataIndex: "handover_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.handover_time",
    subTitle: "中交时间",
    dataIndex: "handover_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.completionTime",
    subTitle: "竣工时间",
    dataIndex: "completion_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.completionTime",
    subTitle: "竣工时间",
    dataIndex: "completion_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.strat_reply_time",
    subTitle: "执行策略批复时间",
    dataIndex: "strat_reply_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.strat_reply_time",
    subTitle: "执行策略批复时间",
    dataIndex: "strat_reply_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.strat_reply_org",
    subTitle: "执行策略批复机构",
    dataIndex: "strat_reply_org",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.strat_filing_time",
    subTitle: "执行策略备案时间",
    dataIndex: "strat_filing_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.strat_filing_time",
    subTitle: "执行策略备案时间",
    dataIndex: "strat_filing_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.risk_desc",
    subTitle: "物资采购策划及风险描述",
    dataIndex: "risk_desc",
    width: 280,
    align: "center",
  },
  {
    title: "compinfo.contract_total_amt",
    subTitle: "工程合同总金额",
    dataIndex: "contract_total_amt",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.sub_proc_scale",
    subTitle: "工程分包总采购规模",
    dataIndex: "sub_proc_scale",
    width: 200,
    align: "center",
  },
  {
    title: "compinfo.mat_proc_scale",
    subTitle: "工程物资总采购规模",
    dataIndex: "mat_proc_scale",
    width: 200,
    align: "center",
  },
  {
    title: "compinfo.srv_proc_scale",
    subTitle: "工程服务总采购规模",
    dataIndex: "srv_proc_scale",
    width: 200,
    align: "center",
  },
  {
    title: "compinfo.meeting_basis",
    subTitle: "议题上会依据",
    dataIndex: "meeting_basis",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.obtain_method",
    subTitle: "获得工程项目的方式(0:招标方式,1:非招标方式,2:通过海外单位获取的境外工程,3:自行获取的境外工程)",
    dataIndex: "obtain_method",
    width: 400,
    align: "center",
  },
  {
    title: "compinfo.obtain_method",
    subTitle: "获得工程项目的方式",
    dataIndex: "obtain_method_str",
    width: 400,
    align: "center",
  },
  {
    title: "compinfo.contract_mode",
    subTitle: "承包方式(0:EPC,1:PC,2:C,3:专业工程承包)",
    dataIndex: "contract_mode",
    width: 280,
    align: "center",
  },
  {
    title: "compinfo.contract_mode",
    subTitle: "承包方式",
    dataIndex: "contract_mode_str",
    width: 280,
    align: "center",
  },
  {
    title: "compinfo.project_auth",
    subTitle: "项目预算审批权(0:总部预算委员会,1:分/子公司预算委员会)",
    dataIndex: "project_auth",
    width: 320,
    align: "center",
  },
  {
    title: "compinfo.project_auth",
    subTitle: "项目预算审批权",
    dataIndex: "project_auth_str",
    width: 320,
    align: "center",
  },
  {
    title: "compinfo.project_create_time",
    subTitle: "项目预算报审情况编制时间",
    dataIndex: "project_create_time",
    width: 200,
    align: "center",
  },
  {
    title: "compinfo.project_create_time",
    subTitle: "项目预算报审情况编制时间",
    dataIndex: "project_create_time_str",
    width: 200,
    align: "center",
  },
  {
    title: "compinfo.project_submit_time",
    subTitle: "项目预算报审情况提交时间",
    dataIndex: "project_submit_time",
    width: 200,
    align: "center",
  },
  {
    title: "compinfo.project_submit_time",
    subTitle: "项目预算报审情况提交时间",
    dataIndex: "project_submit_time_str",
    width: 200,
    align: "center",
  },
  {
    title: "compinfo.project_approval_status",
    subTitle: "项目预算批复情况(0:未批复,1:已批复)",
    dataIndex: "project_approval_status",
    width: 240,
    align: "center",
  },
  {
    title: "compinfo.project_approval_status",
    subTitle: "项目预算批复情况",
    dataIndex: "project_approval_status_str",
    width: 240,
    align: "center",
  },
  {
    title: "compinfo.project_time",
    subTitle: "项目预算批复日期",
    dataIndex: "project_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_time",
    subTitle: "项目预算批复日期",
    dataIndex: "project_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.total_invest_amt",
    subTitle: "工程总包预算(万)",
    dataIndex: "total_invest_amt",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.sub_budget_ratio",
    subTitle: "分包总预算占比",
    dataIndex: "sub_budget_ratio",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.mat_budget_amt",
    subTitle: "工程物资总预算(万)",
    dataIndex: "mat_budget_amt",
    width: 180,
    align: "center",
  },
  {
    title: "compinfo.mat_budget_ratio",
    subTitle: "物资总预算占比",
    dataIndex: "mat_budget_ratio",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.srv_budget_amt",
    subTitle: "工程服务总预算(万)",
    dataIndex: "srv_budget_amt",
    width: 180,
    align: "center",
  },
  {
    title: "compinfo.srv_budget_ratio",
    subTitle: "服务总预算占比",
    dataIndex: "srv_budget_ratio",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.tax_rate",
    subTitle: "税率",
    dataIndex: "tax_rate",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.select_req",
    subTitle: "选商要求",
    dataIndex: "select_req",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.quality_req",
    subTitle: "质量要求",
    dataIndex: "quality_req",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.origin_req",
    subTitle: "原产地要求",
    dataIndex: "origin_req",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.owner_part_req",
    subTitle: "业主及相关方参与要求",
    dataIndex: "owner_part_req",
    width: 220,
    align: "center",
  },
  {
    title: "compinfo.contract_type",
    subTitle: "合同类型(0:固定单价,1:暂定总价)",
    dataIndex: "contract_type",
    width: 240,
    align: "center",
  },
  {
    title: "compinfo.contract_type",
    subTitle: "合同类型",
    dataIndex: "contract_type_str",
    width: 240,
    align: "center",
  },
  {
    title: "compinfo.currency_type",
    subTitle: "合同币种",
    dataIndex: "currency_type",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.warranty_period_req",
    subTitle: "质保期要求",
    dataIndex: "warranty_period_req",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.icv_req",
    subTitle: "ICV要求",
    dataIndex: "icv_req",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.select_rule_content",
    subTitle: "选商规则",
    dataIndex: "select_rule_content",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.tech_eval_rule",
    subTitle: "技术评审通用规则",
    dataIndex: "tech_eval_rule",
    width: 200,
    align: "center",
  },
  {
    title: "compinfo.biz_eval_rule",
    subTitle: "商务评审通用规则",
    dataIndex: "biz_eval_rule",
    width: 200,
    align: "center",
  },
  {
    title: "compinfo.tech_special_req",
    subTitle: "技术评审特殊要求",
    dataIndex: "tech_special_req",
    width: 200,
    align: "center",
  },
  {
    title: "compinfo.biz_special_req",
    subTitle: "商务评审特殊要求",
    dataIndex: "biz_special_req",
    width: 200,
    align: "center",
  },
  {
    title: "compinfo.expert_source",
    subTitle: "招标采购专家组成员来源",
    dataIndex: "expert_source",
    width: 240,
    align: "center",
  },
  {
    title: "compinfo.non_bid_team_src",
    subTitle: "非招标评审小组成员来源",
    dataIndex: "non_bid_team_src",
    width: 240,
    align: "center",
  },
  {
    title: "compinfo.non_bid_team_qual",
    subTitle: "非招标评审小组成员数量及资格",
    dataIndex: "non_bid_team_qual",
    width: 300,
    align: "center",
  },
  {
    title: "compinfo.qty_change_plan",
    subTitle: "采购计划数量增减变更策划",
    dataIndex: "qty_change_plan",
    width: 280,
    align: "center",
  },
  {
    title: "compinfo.next_step_plan",
    subTitle: "下一步工作实施方案",
    dataIndex: "next_step_plan",
    width: 200,
    align: "center",
  },
  {
    title: "compinfo.form_maker_code",
    subTitle: "制单人编码",
    dataIndex: "form_maker_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_name",
    subTitle: "制单人名称",
    dataIndex: "form_maker_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_time",
    subTitle: "制单时间",
    dataIndex: "form_make_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_time",
    subTitle: "制单时间",
    dataIndex: "form_make_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_tz",
    subTitle: "制单时区",
    dataIndex: "form_make_tz",
    width: 160,
    align: "center",
  },
];
