export const configColumns = [
  {
    title: "compinfo.contractName",
    subTitle: "项目名称",
    dataIndex: "contract_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_level",
    subTitle: "项目级别",
    dataIndex: "project_level",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_level",
    subTitle: "项目级别",
    dataIndex: "project_level_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contractNo",
    subTitle: "项目编号",
    dataIndex: "contract_no",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.owner_name",
    subTitle: "业主名称",
    dataIndex: "owner_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.import_level",
    subTitle: "是否重点项目(1:重点,0:非重点)",
    dataIndex: "import_level",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.import_level",
    subTitle: "是否重点项目(1:重点,0:非重点)",
    dataIndex: "import_level_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.weekly_status_date",
    subTitle: "中交时间",
    dataIndex: "weekly_status_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.weekly_status",
    subTitle: "状态(1：设计完成；2：在执行；3：机械完工；4：中交；5：投产；6：停工）",
    dataIndex: "weekly_status",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.weekly_status",
    subTitle: "状态(1：设计完成；2：在执行；3：机械完工；4：中交；5：投产；6：停工）",
    dataIndex: "weekly_status_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contract_say_price",
    subTitle: "项目额度",
    dataIndex: "contract_say_price",
    width: 160,
    align: "center",
  },
];
