export const configColumns = [
    {
      title: "compinfo.id",
      subTitle: "id",
      dataIndex: "id",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.config_code",
      subTitle: "配置编码",
      dataIndex: "config_code",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.config_name",
      subTitle: "配置表名",
      dataIndex: "config_name",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.serial_number",
      subTitle: "编号",
      dataIndex: "serial_number",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.form_maker_code",
      subTitle: "制单人编码",
      dataIndex: "form_maker_code",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.form_maker_name",
      subTitle: "制单人名称",
      dataIndex: "form_maker_name",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.form_make_time",
      subTitle: "制单时间",
      dataIndex: "form_make_time",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.form_make_tz",
      subTitle: "制单时区",
      dataIndex: "form_make_tz",
      width: 160,
      align: "center",
    },
  ];
