export const configColumns = [
    {
      title: "compinfo.id",
      subTitle: "主键ID",
      dataIndex: "id",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.wbsName",
      subTitle: "项目部",
      dataIndex: "wbs_code",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.wbsName",
      subTitle: "项目部",
      dataIndex: "wbs_name",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.id_card_no",
      subTitle: "身份证号",
      dataIndex: "id_card_no",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.person_name",
      subTitle: "姓名",
      dataIndex: "person_name",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.team_name",
      subTitle: "隶属承包商单位",
      dataIndex: "team_name",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.position_id",
      subTitle: "岗位",
      dataIndex: "position_id",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.certificate_id",
      subTitle: "持证类型",
      dataIndex: "certificate_id",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.position_id",
      subTitle: "岗位",
      dataIndex: "position_name",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.certificate_id",
      subTitle: "持证类型",
      dataIndex: "certificate_type",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.certificate_no",
      subTitle: "持证编号",
      dataIndex: "certificate_no",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.entry_date",
      subTitle: "入场时间",
      dataIndex: "entry_date",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.entry_date",
      subTitle: "入场时间",
      dataIndex: "entry_date_str",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.create_person",
      subTitle: "制单人",
      dataIndex: "create_person",
      width: 160,
      align: "center",
    },
    {
      title: "scheduleManagement.status",
      subTitle: "状态",
      dataIndex: "status",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.status_name",
      subTitle: "状态",
      dataIndex: "status_name",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.contract_name",
      subTitle: "合同名称",
      dataIndex: "contract_no",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.contract_name",
      subTitle: "合同名称",
      dataIndex: "contract_name",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.reason",
      subTitle: "拉黑原因",
      dataIndex: "reason",
      width: 160,
      align: "center",
    },

    
    
  ];
