export const configColumns = [
  {
    title: "compinfo.id",
    subTitle: "id",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.course_id",
    subTitle: "培训课程",
    dataIndex: "course_id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.material_name",
    subTitle: "资料名称",
    dataIndex: "material_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.material_url",
    subTitle: "资料地址",
    dataIndex: "material_url",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.material_type",
    subTitle: "资料类型",
    dataIndex: "material_type",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.material_type",
    subTitle: "资料类型",
    dataIndex: "material_type_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_ts",
    subTitle: "创建时间",
    dataIndex: "create_ts",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_tz",
    subTitle: "创建时区",
    dataIndex: "create_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_user_code",
    subTitle: "创建人编码",
    dataIndex: "create_user_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_user_name",
    subTitle: "创建人名称",
    dataIndex: "create_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_ts",
    subTitle: "修改时间",
    dataIndex: "modify_ts",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_tz",
    subTitle: "修改时区",
    dataIndex: "modify_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_user_code",
    subTitle: "修改人编码",
    dataIndex: "modify_user_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_user_name",
    subTitle: "修改人名称",
    dataIndex: "modify_user_name",
    width: 160,
    align: "center",
  },
];
