export const configColumns = [
  {
    title: "compinfo.id",
    subTitle: "id",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
   {
    title: "compinfo.belong_month",
    subTitle: "所属月份",
    dataIndex: "belong_month",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.month.report_dep_name",
    subTitle: "月报部门名称",
    dataIndex: "report_dep_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_name",
    subTitle: "项目名称",
    dataIndex: "project_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_level",
    subTitle: "项目等级",
    dataIndex: "project_level",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_level",
    subTitle: "项目等级",
    dataIndex: "project_level_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contract_start_date",
    subTitle: "合同开始日期",
    dataIndex: "contract_start_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contract_end_date",
    subTitle: "合同结束日期",
    dataIndex: "contract_end_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.construction_dep",
    subTitle: "建设单位",
    dataIndex: "construction_dep",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.confirmation_status_str",
    subTitle: "确认状态",
    dataIndex: "confirmation_status_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_id",
    subTitle: "项目ID",
    dataIndex: "project_id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_code",
    subTitle: "月报编码",
    dataIndex: "form_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.report_dep_code",
    subTitle: "填报单位",
    dataIndex: "report_dep_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.monthly_report_start",
    subTitle: "月报日期开始",
    dataIndex: "monthly_report_start",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.monthly_report_end",
    subTitle: "月报日期结束",
    dataIndex: "monthly_report_end",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_status",
    subTitle: "项目状态（1：设计完成；2：在执行；3：机械完工；4：中交；5：投产；6：停工）",
    dataIndex: "project_status",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.is_first",
    subTitle: "是否首次月报（0：否；1：是）",
    dataIndex: "is_first",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_status_date",
    subTitle: "项目状态日期",
    dataIndex: "project_status_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.confirmation_status",
    subTitle: "确认状态（0：草稿；2：公司未确认；3：公司已确认；）",
    dataIndex: "confirmation_status",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark",
    subTitle: "备注",
    dataIndex: "remark",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_ts",
    subTitle: "创建时间",
    dataIndex: "create_ts",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_tz",
    subTitle: "创建时区",
    dataIndex: "create_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_user_code",
    subTitle: "创建人编码",
    dataIndex: "create_user_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_user_name",
    subTitle: "创建人名称",
    dataIndex: "create_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_ts",
    subTitle: "修改时间",
    dataIndex: "modify_ts",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_tz",
    subTitle: "修改时区",
    dataIndex: "modify_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_user_code",
    subTitle: "修改人编码",
    dataIndex: "modify_user_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_user_name",
    subTitle: "修改人名称",
    dataIndex: "modify_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.monthly_id",
    subTitle: "月报id",
    dataIndex: "monthly_id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.change_date",
    subTitle: "变更日期",
    dataIndex: "change_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.change_complete_date",
    subTitle: "变更后完工日期",
    dataIndex: "change_complete_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.change_reason",
    subTitle: "工期变更原因",
    dataIndex: "change_reason",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.stop_report_date",
    subTitle: "停报日期",
    dataIndex: "stop_report_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.shut_down_date",
    subTitle: "停工日期",
    dataIndex: "shut_down_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.work_resumption_date",
    subTitle: "复工日期",
    dataIndex: "work_resumption_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.shut_down_reason",
    subTitle: "停工原因",
    dataIndex: "shut_down_reason",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.person_type",
    subTitle: "人员类别(1:管理人员/2:设计人员/3:采办人员/4:施工人员)",
    dataIndex: "person_type",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.person_situation",
    subTitle: "人员情况(1:投入人员情况/2:缺口人员情况)",
    dataIndex: "person_situation",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.person_category",
    subTitle: "人员类型(1:自有人员(合同化+市场化)/2:劳务用工人员/3:分包商人员)",
    dataIndex: "person_category",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.chinese_count",
    subTitle: "中方人员",
    dataIndex: "chinese_count",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.foreign_count",
    subTitle: "外方人员",
    dataIndex: "foreign_count",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.equipment_type",
    subTitle: "设备分类",
    dataIndex: "equipment_type",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.equipment_name",
    subTitle: "设备名称",
    dataIndex: "equipment_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.equipment_index",
    subTitle: "设备排序",
    dataIndex: "equipment_index",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.own_equipment_count",
    subTitle: "自有/台(套)",
    dataIndex: "own_equipment_count",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.leasing_equipment_count",
    subTitle: "租赁/台(套)",
    dataIndex: "leasing_equipment_count",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.leasing_company",
    subTitle: "租赁公司",
    dataIndex: "leasing_company",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.shared_equipment_count",
    subTitle: "共享/台(套)",
    dataIndex: "shared_equipment_count",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.shared_company",
    subTitle: "共享单位",
    dataIndex: "shared_company",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.subcontractor_name",
    subTitle: "分包商名称",
    dataIndex: "subcontractor_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.subcontracted_content",
    subTitle: "分包内容",
    dataIndex: "subcontracted_content",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.completion_status",
    subTitle: "简述本月关键节点、重点施工工序完成情况",
    dataIndex: "completion_status",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.schedule_desc",
    subTitle: "项目进度描述",
    dataIndex: "schedule_desc",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.work_plan",
    subTitle: "简述当前累计完成的主要工作，关键节点完成情况及下月计划",
    dataIndex: "work_plan",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.progress_id",
    subTitle: "项目进度id",
    dataIndex: "progress_id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.phase",
    subTitle: "工程阶段(设计/采购/施工/试运/其他)",
    dataIndex: "phase",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.cumulative",
    subTitle: "当前累计完成工作情况",
    dataIndex: "cumulative",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.this_month",
    subTitle: "本月工作情况",
    dataIndex: "this_month",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.next_plan",
    subTitle: "下月计划",
    dataIndex: "next_plan",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.weight",
    subTitle: "权重（%）",
    dataIndex: "weight",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.last_month_plan",
    subTitle: "上月计划累计（%）",
    dataIndex: "last_month_plan",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.last_month_reality",
    subTitle: "上月实际累计（%）",
    dataIndex: "last_month_reality",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.last_month_difference",
    subTitle: "上月差值（%）",
    dataIndex: "last_month_difference",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.curr_month_plan",
    subTitle: "本月计划累计（%）",
    dataIndex: "curr_month_plan",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.curr_month_reality",
    subTitle: "本月实际累计（%）",
    dataIndex: "curr_month_reality",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.curr_month_difference",
    subTitle: "本月差值（%）",
    dataIndex: "curr_month_difference",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.single_project",
    subTitle: "单体工程",
    dataIndex: "single_project",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.unit",
    subTitle: "单位",
    dataIndex: "unit",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.major_workload",
    subTitle: "主要工作量",
    dataIndex: "major_workload",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.complete_workload",
    subTitle: "完成工作量",
    dataIndex: "complete_workload",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remaining_work",
    subTitle: "剩余工作量",
    dataIndex: "remaining_work",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.this_month_complete_workload",
    subTitle: "本月完成工作量",
    dataIndex: "this_month_complete_workload",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.next_month_complete_workload",
    subTitle: "下月计划工作量",
    dataIndex: "next_month_complete_workload",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.planned_completion_time",
    subTitle: "计划完工时间",
    dataIndex: "planned_completion_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.main_issues",
    subTitle: "当前存在的主要问题、风险和原因分析",
    dataIndex: "main_issues",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.solution",
    subTitle: "解决措施",
    dataIndex: "solution",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.image_des",
    subTitle: "照片描述",
    dataIndex: "image_des",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.image_url",
    subTitle: "照片附件（请上传原图）",
    dataIndex: "image_url",
    width: 160,
    align: "center",
  },

  {
    title: "scheduleManagement.region_category",
    subTitle: "地域类型",
    dataIndex: "region_category",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.owner_group",
    subTitle: "系统分类",
    dataIndex: "owner_group",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.sign_status",
    subTitle: "签约情况",
    dataIndex: "sign_status",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.erp_code",
    subTitle: "ERP项目编码",
    dataIndex: "erp_code",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.epm_code",
    subTitle: "EPM编码",
    dataIndex: "epm_code",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.create_dep_code",
    subTitle: "创建单位",
    dataIndex: "create_dep_code",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.report_dep_code",
    subTitle: "填报单位",
    dataIndex: "report_dep_code",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.project_name",
    subTitle: "项目名称",
    dataIndex: "project_name",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.contract_no",
    subTitle: "合同号",
    dataIndex: "contract_no",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.contract_status",
    subTitle: "合同状态",
    dataIndex: "contract_status",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.plan_finish_date",
    subTitle: "预计完工日期",
    dataIndex: "plan_finish_date",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.warranty_period",
    subTitle: "合同质保期",
    dataIndex: "warranty_period",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.project_category",
    subTitle: "专业分类",
    dataIndex: "project_category",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.three_new_category",
    subTitle: "三新分类",
    dataIndex: "three_new_category",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.sub_category",
    subTitle: "专业细分",
    dataIndex: "sub_category",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.contract_mode",
    subTitle: "合同类型",
    dataIndex: "contract_mode",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.contract_mode",
    subTitle: "合同类型",
    dataIndex: "contract_mode_name",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.project_level",
    subTitle: "项目等级",
    dataIndex: "project_level",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.project_level",
    subTitle: "项目等级",
    dataIndex: "project_level_name",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.is_guaranty",
    subTitle: "是否由中油工程担保",
    dataIndex: "is_guaranty",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.is_related",
    subTitle: "是否CPECC内部关联项目",
    dataIndex: "is_related",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.import_level",
    subTitle: "项目重要级别",
    dataIndex: "import_level",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.project_status",
    subTitle: "项目状态",
    dataIndex: "project_status",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.project_status",
    subTitle: "项目状态",
    dataIndex: "report_project_status_name",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.project_subject",
    subTitle: "项目概况",
    dataIndex: "project_subject",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.project_quantities",
    subTitle: "项目工程量",
    dataIndex: "project_quantities",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.project_significance",
    subTitle: "项目意义",
    dataIndex: "project_significance",
    width: 160,
    align: "center",
  },

  {
    title: "scheduleManagement.project_director",
    subTitle: "项目主任",
    dataIndex: "project_director",
    width: 160,
    align: "center",
  },



  {
    title: "scheduleManagement.contract_say_price",
    subTitle: "合同金额（含税）",
    dataIndex: "contract_say_price",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.contract_un_say_price",
    subTitle: "合同金额（不含税）",
    dataIndex: "contract_un_say_price",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.contract_sign_date",
    subTitle: "合同签署日期",
    dataIndex: "contract_sign_date",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.contract_start_date",
    subTitle: "合同生效日期",
    dataIndex: "contract_start_date",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.actual_start_date",
    subTitle: "实际开工日期",
    dataIndex: "actual_start_date",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.contract_end_date",
    subTitle: "合同完工日期",
    dataIndex: "contract_end_date",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.contract_end_date",
    subTitle: "合同完工日期",
    dataIndex: "contract_end_date_format",
    width: 160,
    align: "center",
  },

  {
    title: "scheduleManagement.director_phone",
    subTitle: "联系电话",
    dataIndex: "director_phone",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.director_email",
    subTitle: "电子邮箱",
    dataIndex: "director_email",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.project_manager",
    subTitle: "项目经理",
    dataIndex: "project_manager",
    width: 160,
    align: "center",
  },

  {
    title: "scheduleManagement.manager_phone",
    subTitle: "项目经理联系电话",
    dataIndex: "manager_phone",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.manager_email",
    subTitle: "项目经理电子邮箱",
    dataIndex: "manager_email",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.project_contact",
    subTitle: "项目联系人",
    dataIndex: "project_contact",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.contact_phone",
    subTitle: "项目联系人电话",
    dataIndex: "contact_phone",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.contact_email",
    subTitle: "项目联系人邮箱",
    dataIndex: "contact_email",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.project_doc_control",
    subTitle: "项目文控",
    dataIndex: "project_doc_control",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.dc_phone",
    subTitle: "项目文控联系电话",
    dataIndex: "dc_phone",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.dc_email",
    subTitle: "项目文控电子邮箱",
    dataIndex: "dc_email",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.construction_dep",
    subTitle: "建设单位",
    dataIndex: "construction_dep",
    width: 160,
    align: "center",
  },


  {
    title: "scheduleManagement.construction_dep_contact",
    subTitle: "建设单位联系人",
    dataIndex: "construction_dep_contact",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.construction_dep_phone",
    subTitle: "建设单位联系电话",
    dataIndex: "construction_dep_phone",
    width: 160,
    align: "center",
  },

  {
    title: "scheduleManagement.construction_dep_email",
    subTitle: "建设单位电子邮箱",
    dataIndex: "construction_dep_email",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.pmc_pmt_dep",
    subTitle: "PMC/PMT单位",
    dataIndex: "pmc_pmt_dep",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.pmc_pmt_contact",
    subTitle: "PMC/PMT联系人",
    dataIndex: "pmc_pmt_contact",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.pmc_pmt_phone",
    subTitle: "PMC/PMT联系电话",
    dataIndex: "pmc_pmt_phone",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.pmc_pmt_email",
    subTitle: "PMC/PMT电子邮箱",
    dataIndex: "pmc_pmt_email",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.supervision_dep",
    subTitle: "监理单位",
    dataIndex: "supervision_dep",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.supervision_dep_contact",
    subTitle: "监理单位联系人",
    dataIndex: "supervision_dep_contact",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.supervision_dep_phone",
    subTitle: "监理单位联系电话",
    dataIndex: "supervision_dep_phone",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.supervision_dep_email",
    subTitle: "监理单位电子邮箱",
    dataIndex: "supervision_dep_email",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.general_contractor_data",
    subTitle: "总承包单位",
    dataIndex: "general_contractor_data",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.design_dep_data",
    subTitle: "设计单位",
    dataIndex: "design_dep_data",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.purchase_dep_data",
    subTitle: "采购单位",
    dataIndex: "purchase_dep_data",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.internal_dep_data",
    subTitle: "内部施工单位",
    dataIndex: "internal_dep_data",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.external_dep_data",
    subTitle: "外部施工单位",
    dataIndex: "external_dep_data",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.ndt_dep_data",
    subTitle: "无损检测单位",
    dataIndex: "ndt_dep_data",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.operation_dep_data",
    subTitle: "投产运行单位",
    dataIndex: "operation_dep_data",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.project_location",
    subTitle: "项目地点",
    dataIndex: "project_location",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.longitude",
    subTitle: "经度",
    dataIndex: "longitude",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.latitude",
    subTitle: "纬度",
    dataIndex: "latitude",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.area_data",
    subTitle: "区域",
    dataIndex: "area_data",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.create_ts",
    subTitle: "录入时间",
    dataIndex: "create_ts",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.create_user_name",
    subTitle: "录入人名称",
    dataIndex: "create_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.modify_user_name",
    subTitle: "修改人名称",
    dataIndex: "modify_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.modify_ts_format",
    subTitle: "修改时间",
    dataIndex: "modify_ts_format",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.create_ts",
    subTitle: "录入时间",
    dataIndex: "create_ts_format",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.flow_status",
    subTitle: "审批状态",
    dataIndex: "flow_status",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.flow_status",
    subTitle: "审批状态",
    dataIndex: "flow_status_name",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.calculate_date",
    subTitle: "计算合同工期",
    dataIndex: "calculate_date",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.sign_status",
    subTitle: "合同签约情况",
    dataIndex: "sign_status",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.contract_currency",
    subTitle: "合同币种",
    dataIndex: "contract_currency",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.RMB_rate",
    subTitle: "人民币汇率",
    dataIndex: "RMB_rate",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.equivalent_RMB_price",
    subTitle: "折合人民币(含税)",
    dataIndex: "equivalent_RMB_price",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.equivalent_RMB_un_price",
    subTitle: "折合人民币(不含税)",
    dataIndex: "equivalent_RMB_un_price",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.US_rate",
    subTitle: "美元汇率",
    dataIndex: "US_rate",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.equivalent_US_price",
    subTitle: "折合美元(含税)",
    dataIndex: "equivalent_US_price",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.equivalent_US_un_price",
    subTitle: "折合美元(不含税)",
    dataIndex: "equivalent_US_un_price",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.RMB_Total_price",
    subTitle: "人民币合计(含税)",
    dataIndex: "RMB_Total_price",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.RMB_Total_un_price",
    subTitle: "人民币合计(不含税)",
    dataIndex: "RMB_Total_un_price",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.US_Total_price",
    subTitle: "美元合计(含税)",
    dataIndex: "US_Total_price",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.US_Total_un_price",
    subTitle: "美元合计(不含税)",
    dataIndex: "US_Total_un_price",
    width: 160,
    align: "center",
  },
];
