export const configColumns = [
  
  {
    title: "InspectorSeniorityApply.sub_comp_code",
    subTitle: "分公司",
    dataIndex: "sub_comp_name",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.dep_code",
    subTitle: "项目部",
    dataIndex: "dep_name",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.name",
    subTitle: "姓名",
    dataIndex: "name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.exam_unit",
    subTitle: "考试单位",
    dataIndex: "exam_unit",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.exam_project_code",
    subTitle: "考试项目代号",
    dataIndex: "exam_project_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_quantity",
    subTitle: "项目数量",
    dataIndex: "project_quantity",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_quantity",
    subTitle: "项目数量",
    dataIndex: "project_count",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.person_count",
    subTitle: "考试人数",
    dataIndex: "person_count",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.plan_exam_time",
    subTitle: "计划考试时间",
    dataIndex: "plan_exam_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.exam_address",
    subTitle: "考试地点",
    dataIndex: "exam_address",
    width: 160,
    align: "center",
  },

  {
    title: "compinfo.employee_number",
    subTitle: "员工编号",
    dataIndex: "employee_number",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.name",
    subTitle: "姓名",
    dataIndex: "name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.phone",
    subTitle: "电话号码",
    dataIndex: "phone",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.current_unit",
    subTitle: "现单位",
    dataIndex: "current_unit",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.employment_type",
    subTitle: "用工形式",
    dataIndex: "employment_type",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.employment_type",
    subTitle: "用工形式",
    dataIndex: "employment_type_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.gender",
    subTitle: "性别",
    dataIndex: "gender",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.nation",
    subTitle: "民族",
    dataIndex: "nation",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.nation",
    subTitle: "民族",
    dataIndex: "nation_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.operation_project",
    subTitle: "作业项目",
    dataIndex: "operation_project",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.operation_project",
    subTitle: "作业项目",
    dataIndex: "operation_project_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.education",
    subTitle: "文化程度",
    dataIndex: "education",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.education",
    subTitle: "文化程度",
    dataIndex: "education_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.skill_level",
    subTitle: "职业技能等级",
    dataIndex: "skill_level",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.skill_level",
    subTitle: "职业技能等级",
    dataIndex: "skill_level_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.id_card",
    subTitle: "身份证号",
    dataIndex: "id_card",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.address",
    subTitle: "身份证地址",
    dataIndex: "address",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.file_no",
    subTitle: "档案编号",
    dataIndex: "file_no",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.health_status",
    subTitle: "职业健康状况",
    dataIndex: "health_status",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.review_date",
    subTitle: "复审日期",
    dataIndex: "review_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.next_review_date",
    subTitle: "下次审核日期",
    dataIndex: "next_review_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.violation_statuse",
    subTitle: "违章作业情况",
    dataIndex: "violation_statuse",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.work_start_date",
    subTitle: "参加工作时间",
    dataIndex: "work_start_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.work_years",
    subTitle: "从事本工种年限",
    dataIndex: "work_years",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.approval_date",
    subTitle: "审批时间",
    dataIndex: "approval_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.worker_id",
    subTitle: "作业人员",
    dataIndex: "worker_id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.worker_id",
    subTitle: "作业人员",
    dataIndex: "worker_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.exam_result",
    subTitle: "考试结果",
    dataIndex: "exam_result",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.exam_result",
    subTitle: "考试结果",
    dataIndex: "exam_result_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.remark",
    subTitle: "备注",
    dataIndex: "b_remark",
    width: 160,
    align: "center",
  },
  
  {
    title: "compinfo.first_date",
    subTitle: "首次取得特种设备作业人员取证时间",
    dataIndex: "first_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.exam_type",
    subTitle: "考试性质",
    dataIndex: "exam_type",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.valid_project",
    subTitle: "证书有效项目",
    dataIndex: "valid_project",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.valid_date",
    subTitle: "证书有效日期",
    dataIndex: "valid_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.is_exchange",
    subTitle: "是否换取项目",
    dataIndex: "is_exchange",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.is_exchange",
    subTitle: "是否换取项目",
    dataIndex: "is_exchange_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.remark",
    subTitle: "备注",
    dataIndex: "remark",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_ts_str",
    subTitle: "创建时间",
    dataIndex: "create_ts_format",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_ts_str",
    subTitle: "创建时间",
    dataIndex: "create_ts_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_user_name",
    subTitle: "创建人名称",
    dataIndex: "create_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_ts_str",
    subTitle: "修改时间",
    dataIndex: "modify_ts_format",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_ts_str",
    subTitle: "修改时间",
    dataIndex: "modify_ts_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_user_name",
    subTitle: "修改人名称",
    dataIndex: "modify_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "levelConstructor.url",
    subTitle: "附件",
    dataIndex: "url",
    width: 160,
    align: "center",
  },
  {
    title: "common.status",
    subTitle: "审批状态",
    dataIndex: "approval_status",
    width: 160,
    align: "center",
  },

];