export default {
  "compinfo.id": "id",
  "compinfo.wbs_code": "wbsCode",
  "compinfo.prop_key": "层级（branchComp：公司级，subComp：分公司，dep：项目部）",
  "compinfo.course_name": "课程名称",
  "compinfo.course_content": "课程内容",
  "compinfo.course_cover": "课程封面",
  "compinfo.course_intro": "课程简介",
  "compinfo.course_category": "课程分类",
  "compinfo.course_tag": "课程标签",
  "compinfo.course_status": "发布状态",
  "compinfo.is_public": "是否公开",
  "compinfo.create_ts": "创建时间",
  "compinfo.create_tz": "创建时区",
  "compinfo.create_user_code": "创建人编码",
  "compinfo.create_user_name": "创建人名称",
  "compinfo.modify_ts": "修改时间",
  "compinfo.modify_tz": "修改时区",
  "compinfo.modify_user_code": "修改人编码",
  "compinfo.modify_user_name": "修改人名称",
};
