export const configColumns = [
  {
    title: "compinfo.id",
    subTitle: "id",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.supplier_name",
    subTitle: "供应商名称",
    dataIndex: "supplier_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.supplier_code",
    subTitle: "供应商编码",
    dataIndex: "supplier_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.supplier_type",
    subTitle: "供应商管理类别",
    dataIndex: "supplier_type",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.product_quality",
    subTitle: "产品质量",
    dataIndex: "product_quality",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.service_ability",
    subTitle: "服务能力",
    dataIndex: "service_ability",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contract_performance",
    subTitle: "合同履约",
    dataIndex: "contract_performance",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.price_level",
    subTitle: "价格水平",
    dataIndex: "price_level",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.market_shares",
    subTitle: "市场份额",
    dataIndex: "market_shares",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.technological_level",
    subTitle: "技术水平",
    dataIndex: "technological_level",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.integrity_management",
    subTitle: "诚信经营",
    dataIndex: "integrity_management",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.total_score",
    subTitle: "总成绩",
    dataIndex: "total_score",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.delivery_amount",
    subTitle: "ERP到货金额元",
    dataIndex: "delivery_amount",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.year",
    subTitle: "所属年份",
    dataIndex: "year",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_ts",
    subTitle: "创建时间",
    dataIndex: "create_ts",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_tz",
    subTitle: "创建时区",
    dataIndex: "create_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_user_code",
    subTitle: "创建人编码",
    dataIndex: "create_user_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_user_name",
    subTitle: "创建人名称",
    dataIndex: "create_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_ts",
    subTitle: "修改时间",
    dataIndex: "modify_ts",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_tz",
    subTitle: "修改时区",
    dataIndex: "modify_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_user_code",
    subTitle: "修改人编码",
    dataIndex: "modify_user_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_user_name",
    subTitle: "修改人名称",
    dataIndex: "modify_user_name",
    width: 160,
    align: "center",
  },
];
