export const configColumns = [
  {
    title: "compinfo.id",
    subTitle: "自增主键",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.group_code",
    subTitle: "分组",
    dataIndex: "group_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.business_partner_code",
    subTitle: "业务伙伴",
    dataIndex: "business_partner_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.client_code",
    subTitle: "客户",
    dataIndex: "client_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.supplier_code",
    subTitle: "供应商编号",
    dataIndex: "supplier_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.name_1",
    subTitle: "名称1",
    dataIndex: "name_1",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.search_2",
    subTitle: "搜索条件2",
    dataIndex: "search_2",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.unit_category",
    subTitle: "单位分类",
    dataIndex: "unit_category",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.unit_category_description",
    subTitle: "单位分类描述",
    dataIndex: "unit_category_description",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.unit_type",
    subTitle: "单位性质",
    dataIndex: "unit_type",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.unit_type_description",
    subTitle: "单位性质描述",
    dataIndex: "unit_type_description",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.company_type",
    subTitle: "企业类型",
    dataIndex: "company_type",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.company_type_description",
    subTitle: "企业类型描述",
    dataIndex: "company_type_description",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.company_size",
    subTitle: "企业规模",
    dataIndex: "company_size",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.company_size_description",
    subTitle: "企业规模描述",
    dataIndex: "company_size_description",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.belong_company_type",
    subTitle: "所属集团类型",
    dataIndex: "belong_company_type",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.belong_company_type_description",
    subTitle: "所属集团类型描述",
    dataIndex: "belong_company_type_description",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.belong_company_name",
    subTitle: "所属集团名称",
    dataIndex: "belong_company_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.belong_company_name_description",
    subTitle: "所属集团名称描述",
    dataIndex: "belong_company_name_description",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contact_hongkong",
    subTitle: "关联人士-香港准则",
    dataIndex: "contact_hongkong",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contact_hongkong_description",
    subTitle: "关联人士-香港准则描述",
    dataIndex: "contact_hongkong_description",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contact_inter",
    subTitle: "关联人士-国际准则",
    dataIndex: "contact_inter",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contact_inter_description",
    subTitle: "关联人士-国际准则描述",
    dataIndex: "contact_inter_description",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.operation_status",
    subTitle: "经营状态",
    dataIndex: "operation_status",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.operation_status_description",
    subTitle: "经营状态描述",
    dataIndex: "operation_status_description",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.organization_code",
    subTitle: "组织机构编码",
    dataIndex: "organization_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.internal_employee_code",
    subTitle: "内部员工编号",
    dataIndex: "internal_employee_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.trade_partner",
    subTitle: "贸易伙伴",
    dataIndex: "trade_partner",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.company_name",
    subTitle: "公司名称",
    dataIndex: "company_name",
    width: 160,
    align: "center",
  },
];
