export const configColumns = [
  {
    title: "compinfo.id",
    subTitle: "主键ID",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.nc_name",
    subTitle: "不合格品/项名称",
    dataIndex: "nc_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.nc_code",
    subTitle: "不合格品/项编号",
    dataIndex: "nc_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.nc_nature",
    subTitle: "不合格品/项性质",
    dataIndex: "nc_nature",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.occurrence_time",
    subTitle: "发生时间",
    dataIndex: "occurrence_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.occurrence_time",
    subTitle: "发生时间",
    dataIndex: "occurrence_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.occurrence_unit",
    subTitle: "发生单位",
    dataIndex: "occurrence_unit",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.nc_reason",
    subTitle: "不合格原因按人机料法环测归类分析",
    dataIndex: "nc_reason",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.corrective_action",
    subTitle: "纠正措施方案",
    dataIndex: "corrective_action",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.completion_time",
    subTitle: "完成时间",
    dataIndex: "completion_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.status",
    subTitle: "状态",
    dataIndex: "status",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark",
    subTitle: "备注",
    dataIndex: "remark",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.dep_code",
    subTitle: "depcode",
    dataIndex: "dep_code",
    width: 160,
    align: "center",
  },
  {
    title: "填报单位",
    subTitle: "填报单位",
    dataIndex: "dep_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_code",
    subTitle: "制单人编码",
    dataIndex: "form_maker_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_name",
    subTitle: "制单人名称",
    dataIndex: "form_maker_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_time",
    subTitle: "制单时间",
    dataIndex: "form_make_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_tz",
    subTitle: "制单时区",
    dataIndex: "form_make_tz",
    width: 160,
    align: "center",
  },
];
