export const configColumns = [
  {
    title: "Contractor.RowNumber",
    subTitle: "序号",
    dataIndex: "RowNumber",
    width: 160,
    align: "center",
  },
  {
    title: "Contractor.id",
    subTitle: "ID",
    dataIndex: "id",
    width: 160,
  },
  {
    title: "Contractor.auditor_name",
    subTitle: "监督审核人员",
    dataIndex: "auditor_name",
    width: 220,
    align: "center",
  },
  {
    title: "Contractor.audit_time",
    subTitle: "审核时间",
    dataIndex: "audit_time",
    width: 160,
    align: "center",
  },
  {
    title: "Contractor.audit_time",
    subTitle: "审核时间",
    dataIndex: "audit_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "Contractor.audit_location",
    subTitle: "审核地点",
    dataIndex: "audit_location",
    width: 200,
    align: "center",
  },
  {
    title: "Contractor.audited_unit",
    subTitle: "接受审核单位",
    dataIndex: "audited_unit",
    width: 220,
    align: "center",
  },
  {
    title: "Contractor.dept_name",
    subTitle: "部门",
    dataIndex: "dept_name",
    width: 160,
    align: "center",
  },
  {
    title: "Contractor.post_name",
    subTitle: "岗位",
    dataIndex: "post_name",
    width: 160,
    align: "center",
  },
  {
    title: "Contractor.issue_description",
    subTitle: "问题描述",
    dataIndex: "issue_description",
    width: 300,
    align: "center",
  },
  {
    title: "Contractor.judgement_basis",
    subTitle: "判定依据",
    dataIndex: "judgement_basis",
    width: 250,
    align: "center",
  },
  {
    title: "Contractor.problem_category",
    subTitle: "问题归类",
    dataIndex: "problem_category",
    width: 160,
    align: "center",
  },

  {
    title: "Contractor.problem_category",
    subTitle: "问题归类",
    dataIndex: "problem_category_name",
    width: 160,
    align: "center",
  },
  {
    title: "Contractor.professional_field",
    subTitle: "专业",
    dataIndex: "professional_field",
    width: 160,
    align: "center",
  },
  {
    title: "Contractor.professional_field",
    subTitle: "专业",
    dataIndex: "professional_field_name",
    width: 160,
    align: "center",
  },
  {
    title: "Contractor.one_involved_elements",
    subTitle: "一级要素",
    dataIndex: "one_involved_elements",
    width: 180,
    align: "center",
  },
  {
    title: "Contractor.involved_elements",
    subTitle: "涉及要素",
    dataIndex: "involved_elements",
    width: 180,
    align: "center",
  },
  {
    title: "Contractor.audit_item",
    subTitle: "审核项目",
    dataIndex: "audit_item",
    width: 180,
    align: "center",
  },
  {
    title: "Contractor.issue_nature",
    subTitle: "问题性质",
    dataIndex: "issue_nature",
    width: 160,
    align: "center",
  },
  {
    title: "Contractor.rectification_advice",
    subTitle: "整改建议",
    dataIndex: "rectification_advice",
    width: 260,
    align: "center",
  },
  {
    title: "Contractor.completion_time",
    subTitle: "完成时间",
    dataIndex: "completion_time",
    width: 160,
    align: "center",
  },
  {
    title: "Contractor.completion_time",
    subTitle: "完成时间",
    dataIndex: "completion_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "Contractor.remark",
    subTitle: "备注",
    dataIndex: "remark",
    width: 200,
    align: "center",
  },
  {
    title: "Contractor.wbs_name",
    subTitle: "分公司名称",
    dataIndex: "wbs_name",
    width: 160,
    align: "center",
  },
];