export const configColumns = [
  {
    title: "compinfo.id",
    subTitle: "主键ID",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.internal_audit",
    subTitle: "内审情况",
    dataIndex: "internal_audit",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.training",
    subTitle: "培训情况",
    dataIndex: "training",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.formulation",
    subTitle: "制定情况",
    dataIndex: "formulation",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.implementation",
    subTitle: "实施情况",
    dataIndex: "implementation",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.inspection",
    subTitle: "检查情况",
    dataIndex: "inspection",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.improvement",
    subTitle: "改进情况",
    dataIndex: "improvement",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.activities",
    subTitle: "其他质量体系运行相关活动",
    dataIndex: "activities",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.dep_code",
    subTitle: "depcode",
    dataIndex: "dep_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_code",
    subTitle: "制单人编码",
    dataIndex: "form_maker_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_name",
    subTitle: "制单人名称",
    dataIndex: "form_maker_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_time",
    subTitle: "制单时间",
    dataIndex: "form_make_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_tz",
    subTitle: "制单时区",
    dataIndex: "form_make_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_time",
    subTitle: "制单时间",
    dataIndex: "form_make_time_str",
    width: 160,
    align: "center",
  },
];
