export const configColumns = [
  {
    title: "InspectorSeniorityApply.sub_comp_code",
    subTitle: "分公司",
    dataIndex: "sub_comp_name",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.dep_code",
    subTitle: "项目部",
    dataIndex: "dep_name",
    width: 160,
    align: "center",
  },
  {
    title: "monitoringMeasuring.year",
    subTitle: "年份",
    dataIndex: "year",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.month",
    subTitle: "所属月份",
    dataIndex: "month",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project",
    subTitle: "工程名称",
    dataIndex: "project",
    width: 160,
    align: "center",
  },

  {
    title: "compinfo.construction_specialty",
    subTitle: "施工专业/过程",
    dataIndex: "construction_specialty",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.job_activity",
    subTitle: "作业活动/作业部位",
    dataIndex: "job_activity",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.risk",
    subTitle: "风险",
    dataIndex: "risk",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.risk_description",
    subTitle: "风险描述",
    dataIndex: "risk_description",
    width: 260,
    align: "center",
  },
  {
    title: "compinfo.leader",
    subTitle: "公司片区督导领导",
    dataIndex: "leader",
    width: 260,
    align: "center",
  },
  {
    title: "compinfo.is_comp_risk",
    subTitle: "公司级风险",
    dataIndex: "is_comp_risk",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.is_sub_risk",
    subTitle: "分公司级风险",
    dataIndex: "is_sub_risk",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.is_project_risk",
    subTitle: "项目级风险",
    dataIndex: "is_project_risk",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.is_comp_risk",
    subTitle: "公司级风险",
    dataIndex: "is_comp_risk_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.is_sub_risk",
    subTitle: "分公司级风险",
    dataIndex: "is_sub_risk_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.is_project_risk",
    subTitle: "项目级风险",
    dataIndex: "is_project_risk_str",
    width: 160,
    align: "center",
  },

  {
    title: "compinfo.risk_position",
    subTitle: "风险部位",
    dataIndex: "risk_position",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.responsible_dep",
    subTitle: "责任部门",
    dataIndex: "responsible_dep",
    width: 160,
    align: "center",
  },

  {
    title: "compinfo.first_risk_type",
    subTitle: "一级风险类别",
    dataIndex: "first_risk_type",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.first_process",
    subTitle: "一级流程/专业",
    dataIndex: "first_process",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.second_process",
    subTitle: "二级流程/作业活动",
    dataIndex: "second_process",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.work_step",
    subTitle: "作业步骤/工序",
    dataIndex: "work_step",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.risk_name",
    subTitle: "风险类别/风险名称",
    dataIndex: "risk_name",
    width: 160,
    align: "center",
  },

  {
    title: "compinfo.risk_cause",
    subTitle: "风险可能产生之因",
    dataIndex: "risk_cause",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.risk_consequence",
    subTitle: "风险可能导致之果",
    dataIndex: "risk_consequence",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.likelihood",
    subTitle: "可能性（L）",
    dataIndex: "likelihood",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.severity",
    subTitle: "严重程度（S）",
    dataIndex: "severity",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.risk_coefficient",
    subTitle: "风险系数（R）",
    dataIndex: "risk_coefficient",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.risk_grade",
    subTitle: "风险等级",
    dataIndex: "risk_grade",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.acceptable",
    subTitle: "可否接受",
    dataIndex: "acceptable",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.control_target",
    subTitle: "控制目标",
    dataIndex: "control_target",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.preventive_measures",
    subTitle: "预防措施/控制方案",
    dataIndex: "preventive_measures",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.responsible_person",
    subTitle: "责任人",
    dataIndex: "responsible_person",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.approval_date",
    subTitle: "审批时间",
    dataIndex: "approval_date",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.remark",
    subTitle: "备注",
    dataIndex: "remark",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_ts_str",
    subTitle: "创建时间",
    dataIndex: "create_ts_format",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_ts_str",
    subTitle: "创建时间",
    dataIndex: "create_ts_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_user_name",
    subTitle: "创建人名称",
    dataIndex: "create_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_ts_str",
    subTitle: "修改时间",
    dataIndex: "modify_ts_format",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_ts_str",
    subTitle: "修改时间",
    dataIndex: "modify_ts_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_user_name",
    subTitle: "修改人名称",
    dataIndex: "modify_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "levelConstructor.url",
    subTitle: "附件",
    dataIndex: "url",
    width: 160,
    align: "center",
  },
  {
    title: "common.status",
    subTitle: "审批状态",
    dataIndex: "approval_status",
    width: 160,
    align: "center",
  },


  {
    title: "wrokLicenseRegister.serial_number",
    subTitle: "序号",
    dataIndex: "serial_number",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.risk_category",
    subTitle: "一级风险类别",
    dataIndex: "risk_category",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.construction_profession",
    subTitle: "施工专业/过程",
    dataIndex: "construction_profession",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.operation_activity",
    subTitle: "作业活动",
    dataIndex: "operation_activity",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.risk_point",
    subTitle: "风险点",
    dataIndex: "risk_point",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.risk_description",
    subTitle: "风险描述",
    dataIndex: "risk_description",
    width: 160,
    align: "center",
  },
];
