import { AUDIT_STATUS_NAME } from "@/common/common";
import { Tag } from "antd";

export const configColumns = [
  {
    title: "HoistingMachineryPreformance.RowNumber",
    subTitle: "序号",
    dataIndex: "RowNumber",
    width: 160,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.id",
    subTitle: "序号",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.branch_comp_code",
    subTitle: "分公司",
    dataIndex: "branch_comp_code",
    width: 160,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.branch_comp_code",
    subTitle: "分公司",
    dataIndex: "branch_comp_name",
    width: 160,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.project_name",
    subTitle: "工程项目",
    dataIndex: "project_name",
    width: 200,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.completion_date",
    subTitle: "出厂/竣工日期",
    dataIndex: "completion_date",
    width: 180,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.completion_date",
    subTitle: "出厂/竣工日期",
    dataIndex: "completion_date_str",
    width: 180,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.currDepCode",
    subTitle: "当前项目部",
    dataIndex: "currDepCode",
    width: 160,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.currUserCode",
    subTitle: "用户",
    dataIndex: "currUserCode",
    width: 160,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.currUserName",
    subTitle: "用户名称",
    dataIndex: "currUserName",
    width: 160,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.design_pressure",
    subTitle: "设计压力（MPa）",
    dataIndex: "design_pressure",
    width: 200,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.design_temperature",
    subTitle: "设计温度（℃）",
    dataIndex: "design_temperature",
    width: 200,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.equipment_material",
    subTitle: "设备材质",
    dataIndex: "equipment_material",
    width: 160,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.equipment_name",
    subTitle: "设备名称",
    dataIndex: "equipment_name",
    width: 160,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.equipment_specification",
    subTitle: "设备规格（HDL mm / m³）",
    dataIndex: "equipment_specification",
    width: 230,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.equipment_type",
    subTitle: "设备类别",
    dataIndex: "equipment_type",
    width: 160,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.inspection_report_file",
    subTitle: "上传监检报告",
    dataIndex: "inspection_report_file",
    width: 200,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.inspection_unit_name",
    subTitle: "监检单位名称",
    dataIndex: "inspection_unit_name",
    width: 200,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.product_device_no",
    subTitle: "产品编号/设备位号",
    dataIndex: "product_device_no",
    width: 230,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.quantity",
    subTitle: "数量",
    dataIndex: "quantity",
    width: 160,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.single_weight",
    subTitle: "设备单体重量（kg）",
    dataIndex: "single_weight",
    width: 200,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.user_unit_name",
    subTitle: "使用单位名称",
    dataIndex: "user_unit_name",
    width: 200,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.wbs_code",
    subTitle: "项目部编码",
    dataIndex: "wbs_code",
    width: 160,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.wbs_code",
    subTitle: "项目部编码",
    dataIndex: "wbs_name",
    width: 160,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.work_medium",
    subTitle: "工作介质",
    dataIndex: "work_medium",
    width: 160,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.audit_status_name",
    subTitle: "审批状态",
    dataIndex: "audit_status_name",
    width: 160,
    align: "center",
    render: (text: any) => {
      if (AUDIT_STATUS_NAME[text]) {
        return <Tag color={AUDIT_STATUS_NAME[text]}>{text}</Tag>
      } else {
        return <Tag color="orange">{text || '暂无审批'}</Tag>
      }
    }
  },
  {
    title: "HoistingMachineryPreformance.hoisting_machinery_variety",
    subTitle: "品种(型式)",
    dataIndex: "hoisting_machinery_variety",
    width: 160,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.hoisting_machinery_model",
    subTitle: "型号(参数)",
    dataIndex: "hoisting_machinery_model",
    width: 160,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.height",
    subTitle: "起升高度(m)",
    dataIndex: "height",
    width: 160,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.rated_load_weight",
    subTitle: "额定起重量(t)",
    dataIndex: "rated_load_weight",
    width: 160,
    align: "center",
  },
  {
    title: "HoistingMachineryPreformance.span",
    subTitle: "跨度(m)",
    dataIndex: "span",
    width: 160,
    align: "center",
  },
];
