export const configColumns = [
  {
    title: "BidQuotation.owner_unit_name",
    subTitle: "业主（甲方）单位名称",
    dataIndex: "owner_unit_name",
    width: 200,
    align: "center",
  },
  {
    title: "BidQuotation.project_name",
    subTitle: "工程项目名称",
    dataIndex: "project_name",
    width: 160,
    align: "center",
  },
  {
    title: "BidQuotation.applicant_unit",
    subTitle: "投标单位",
    dataIndex: "applicant_unit",
    width: 160,
    align: "center",
  },
  {
    title: "BidQuotation.is_internal_project",
    subTitle: "是否集团内项目",
    dataIndex: "is_internal_project",
    width: 160,
    align: "center",
  },
  {
    title: "BidQuotation.lt_5m_flag",
    subTitle: "是否小规模项目",//小于500万元
    dataIndex: "lt_5m_flag",
    width: 160,
    align: "center",
  },
  {
    title: "BidQuotation.is_new_lowcarbon",
    subTitle: "是否双碳新兴",
    dataIndex: "is_new_lowcarbon",
    width: 160,
    align: "center",
  },
  {
    title: "BidQuotation.is_internal_project",
    subTitle: "是否集团内项目",
    dataIndex: "is_internal_project_str",
    width: 160,
    align: "center",
  },
  {
    title: "BidQuotation.lt_5m_flag",
    subTitle: "小于500万元",
    dataIndex: "lt_5m_flag_str",
    width: 160,
    align: "center",
  },
  {
    title: "BidQuotation.is_new_lowcarbon",
    subTitle: "是否双碳新兴",
    dataIndex: "is_new_lowcarbon_str",
    width: 160,
    align: "center",
  },
  {
    title: "BidQuotation.project_description",
    subTitle: "项目描述",
    dataIndex: "project_description",
    width: 160,
    align: "center",
  },
  // {
  //   title: "BidQuotation.construction_location",
  //   subTitle: "建设地点",
  //   dataIndex: "construction_location",
  //   width: 160,
  //   align: "center",
  // },
  {
    title: "BidQuotation.quotation_method",
    subTitle: "报价方式",
    dataIndex: "quotation_method",
    width: 160,
    align: "center",
  },
  {
    title: "BidQuotation.bid_open_time",
    subTitle: "开标时间",
    dataIndex: "bid_open_time",
    width: 160,
    align: "center",
  },
  {
    title: "BidQuotation.bid_open_time",
    subTitle: "开标时间",
    dataIndex: "bid_open_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "BidQuotation.bid_result",
    subTitle: "中标情况",
    dataIndex: "bid_result",
    width: 160,
    align: "center",
  },
  {
    title: "BidQuotation.winning_amount",
    subTitle: "中标金额(万元)",
    dataIndex: "winning_amount",
    width: 160,
    align: "center",
  },
  {
    title: "BidQuotation.resource_review_report",
    subTitle: "资源信息评审报告。",
    dataIndex: "resource_review_report",
    width: 220,
    align: "center",
  },
  {
    title: "BidQuotation.tender_docs_and_attachments",
    subTitle: "招标文件及相关附件",
    dataIndex: "tender_docs_and_attachments",
    width: 240,
    align: "center",
  },
  {
    title: "BidQuotation.tender_doc_review",
    subTitle: "招标文件评审",
    dataIndex: "tender_doc_review",
    width: 160,
    align: "center",
  },
  {
    title: "BidQuotation.bid_document",
    subTitle: "投标文件",
    dataIndex: "bid_document",
    width: 160,
    align: "center",
  },
  {
    title: "BidQuotation.bid_document_review",
    subTitle: "投标文件评审",
    dataIndex: "bid_document_review",
    width: 160,
    align: "center",
  },
  {
    title: "BidQuotation.winning_notice",
    subTitle: "中标通知书",
    dataIndex: "winning_notice",
    width: 160,
    align: "center",
  },
  {
    title: "BidQuotation.company_meeting_materials",
    subTitle: "公司上会材料",
    dataIndex: "company_meeting_materials",
    width: 160,
    align: "center",
  },
  {
    title: "BidQuotation.crm_entry_no",
    subTitle: "CRM录入编号",
    dataIndex: "crm_entry_no",
    width: 160,
    align: "center",
  },
  {
    title: "BidQuotation.id",
    subTitle: "序号",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "BidQuotation.RowNumber",
    subTitle: "序号",
    dataIndex: "RowNumber",
    width: 160,
    align: "center",
  },
  {
    title: "BidQuotation.wbs_code",
    subTitle: "项目部",
    dataIndex: "wbs_code",
    width: 160,
    align: "center",
  },
  {
    title: "BidQuotation.create_by_name",
    subTitle: "制单人",
    dataIndex: "create_by",
    width: 160,
    align: "center",
  },
  {
    title: "BidQuotation.create_by_name",
    subTitle: "制单人",
    dataIndex: "create_by_name",
    width: 160,
    align: "center",
  },
  {
    title: "BidQuotation.explanation",
    subTitle: "情况说明",
    dataIndex: "explanation",
    width: 160,
    align: "center",
  },
  {
    title: "BidQuotation.fact_sheet_file",
    subTitle: "情况说明文件",
    dataIndex: "fact_sheet_file",
    width: 160,
    align: "center",
  },
   {
    title: "BidQuotation.fact_sheet",
    subTitle: "情况说明",
    dataIndex: "fact_sheet",
    width: 160,
    align: "center",
  },
];
