export const configColumns = [
  {
    title: "AnnualAssessment.id",
    subTitle: "序号",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "AnnualAssessment.config_id",
    subTitle: "年度公司重大经营风险评估调查配置表",
    dataIndex: "config_id",
    width: 160,
    align: "center",
  },
  {
    title: "AnnualAssessment.report_name",
    subTitle: "填表人",
    dataIndex: "report_name",
    width: 160,
    align: "center",
  },
  {
    title: "AnnualAssessment.post_name",
    subTitle: "岗位",
    dataIndex: "post_name",
    width: 160,
    align: "center",
  },
  {
    title: "AnnualAssessment.weight",
    subTitle: "权重",
    dataIndex: "weight",
    width: 160,
    align: "center",
  },
  {
    title: "AnnualAssessment.possibility_score",
    subTitle: "风险发生可能性",
    dataIndex: "possibility_score",
    width: 160,
    align: "center",
  },
  {
    title: "AnnualAssessment.influence_score",
    subTitle: "风险影响程度",
    dataIndex: "influence_score",
    width: 160,
    align: "center",
  },
  {
    title: "AnnualAssessment.create_date",
    subTitle: "创建日期",
    dataIndex: "create_date",
    width: 160,
    align: "center",
  },
  {
    title: "AnnualAssessment.create_by",
    subTitle: "创建人",
    dataIndex: "create_by",
    width: 160,
    align: "center",
  },
  {
    title: "AnnualAssessment.create_by_name",
    subTitle: "创建人",
    dataIndex: "create_by_name",
    width: 160,
    align: "center",
  },
  {
    title: "AnnualAssessment.update_date",
    subTitle: "更新日期",
    dataIndex: "update_date",
    width: 160,
    align: "center",
  },
  {
    title: "AnnualAssessment.update_by",
    subTitle: "更新姓名",
    dataIndex: "update_by",
    width: 160,
    align: "center",
  },
  {
    title: "AnnualAssessment.update_by_name",
    subTitle: "更新姓名",
    dataIndex: "update_by_name",
    width: 160,
    align: "center",
  },
  {
    title: "AnnualAssessment.wbs_code",
    subTitle: "项目部编码",
    dataIndex: "wbs_code",
    width: 160,
    align: "center",
  },
  {
    title: "AnnualAssessment.risk_name",
    subTitle: "风险名称",
    dataIndex: "risk_name",
    width: 160,
    align: "center",
  },
  {
    title: "AnnualAssessment.wbs_name",
    subTitle: "项目部名称",
    dataIndex: "wbs_name",
    width: 160,
    align: "center",
  },
  {
    title: "AnnualAssessment.create_date_str",
    subTitle: "创建日期",
    dataIndex: "create_date_str",
    width: 160,
    align: "center",
  },
  {
    title: "AnnualAssessment.update_date_str",
    subTitle: "创建人",
    dataIndex: "update_date_str",
    width: 160,
    align: "center",
  },
  {
    title: "AnnualAssessment.RowNumber",
    subTitle: "序号",
    dataIndex: "RowNumber",
    width: 160,
    align: "center",
  },
];
