export const configColumns = [
  {
    title: "InspectorSeniorityApply.sub_comp_code",
    subTitle: "分公司",
    dataIndex: "sub_comp_name",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.dep_code",
    subTitle: "项目部",
    dataIndex: "dep_name",
    width: 160,
    align: "center",
  },

  {
    title: "monitoringMeasuring.year",
    subTitle: "年份",
    dataIndex: "year",
    width: 160,
    align: "center",
  },
  {
    title: "monitoringMeasuring.month",
    subTitle: "月份",
    dataIndex: "month",
    width: 160,
    align: "center",
  },
  

  {
    title: "wrokLicenseRegister.remark",
    subTitle: "备注",
    dataIndex: "remark",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_ts_str",
    subTitle: "创建时间",
    dataIndex: "create_ts_format",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_ts_str",
    subTitle: "创建时间",
    dataIndex: "create_ts_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_user_name",
    subTitle: "创建人名称",
    dataIndex: "create_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_ts_str",
    subTitle: "修改时间",
    dataIndex: "modify_ts_format",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_ts_str",
    subTitle: "修改时间",
    dataIndex: "modify_ts_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_user_name",
    subTitle: "修改人名称",
    dataIndex: "modify_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "levelConstructor.url",
    subTitle: "附件",
    dataIndex: "url",
    width: 160,
    align: "center",
  },
  {
    title: "common.status",
    subTitle: "审批状态",
    dataIndex: "approval_status",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.dev_code",
    subTitle: "装置",
    dataIndex: "dev_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.dev_name",
    subTitle: "装置",
    dataIndex: "dev_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.year",
    subTitle: "所属年份",
    dataIndex: "year",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.merit_types",
    subTitle: "创优类型",
    dataIndex: "merit_types",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.merit_types",
    subTitle: "创优类型",
    dataIndex: "merit_types_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.application_date",
    subTitle: "计划申报时间",
    dataIndex: "application_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.charge_person_phone",
    subTitle: "负责人电话",
    dataIndex: "charge_person_phone",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contact_person_phone",
    subTitle: "联络人电话",
    dataIndex: "contact_person_phone",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.charge_person",
    subTitle: "负责人",
    dataIndex: "charge_person",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contact_person",
    subTitle: "联络人",
    dataIndex: "contact_person",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.application_unit",
    subTitle: "主申报单位",
    dataIndex: "application_unit",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.start_date",
    subTitle: "工程开工时间",
    dataIndex: "start_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.end_date",
    subTitle: "工程竣工时间",
    dataIndex: "end_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contract_amount",
    subTitle: "合同额",
    dataIndex: "contract_amount",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.budget_amount",
    subTitle: "概算额",
    dataIndex: "budget_amount",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.final_account_amount",
    subTitle: "决算额",
    dataIndex: "final_account_amount",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.construction_unit",
    subTitle: "建设单位",
    dataIndex: "construction_unit",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.survey_unit",
    subTitle: "勘察单位",
    dataIndex: "survey_unit",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.design_unit",
    subTitle: "设计单位",
    dataIndex: "design_unit",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.construction_contractor",
    subTitle: "施工单位",
    dataIndex: "construction_contractor",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.supervision_unit",
    subTitle: "监理单位",
    dataIndex: "supervision_unit",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.design_award",
    subTitle: "设计获奖情况",
    dataIndex: "design_award",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.tech_progress_award",
    subTitle: "科技进步获奖情况",
    dataIndex: "tech_progress_award",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.other_award",
    subTitle: "其他获奖情况",
    dataIndex: "other_award",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.design_award",
    subTitle: "设计获奖情况",
    dataIndex: "design_award_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.tech_progress_award",
    subTitle: "科技进步获奖情况",
    dataIndex: "tech_progress_award_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.other_award",
    subTitle: "其他获奖情况",
    dataIndex: "other_award_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.construction_unit_opinion",
    subTitle: "建设单位意见",
    dataIndex: "construction_unit_opinion",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.construction_unit_opinion",
    subTitle: "建设单位意见",
    dataIndex: "construction_unit_opinion_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.quality_accident_proof",
    subTitle: "无质量事故证明",
    dataIndex: "quality_accident_proof",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.quality_accident_proof",
    subTitle: "无质量事故证明",
    dataIndex: "quality_accident_proof_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.no_wage_arrears_proof",
    subTitle: "无拖欠农民工工资证明",
    dataIndex: "no_wage_arrears_proof",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.embassy_proof",
    subTitle: "大使馆商务参赞证明",
    dataIndex: "embassy_proof",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.no_wage_arrears_proof",
    subTitle: "无拖欠农民工工资证明",
    dataIndex: "no_wage_arrears_proof_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.embassy_proof",
    subTitle: "大使馆商务参赞证明",
    dataIndex: "embassy_proof_str",
    width: 160,
    align: "center",
  },





  {
    title: "计划申报国家级优质工程的装置",
    subTitle: "国家级优质工程",
    dataIndex: "国家级优质工程",
    width: 160,
    align: "center",
  },
  {
    title: "计划申报国家级优秀焊接工程的装置",
    subTitle: "国家级优秀焊接工程",
    dataIndex: "国家级优秀焊接工程",
    width: 160,
    align: "center",
  },
  {
    title: "计划申报省部级优质工程的装置",
    subTitle: "省部级优质工程",
    dataIndex: "省部级优质工程",
    width: 160,
    align: "center",
  },
  {
    title: "计划申报省部级石油安装工程的装置",
    subTitle: "省部级石油安装工程",
    dataIndex: "省部级石油安装工程",
    width: 160,
    align: "center",
  },
  {
    title: "计划申报局级优质工程的装置",
    subTitle: "局级优质工程",
    dataIndex: "局级优质工程",
    width: 160,
    align: "center",
  },
  {
    title: "计划申报局级安装工程优质奖的装置",
    subTitle: "局级安装工程优质奖",
    dataIndex: "局级安装工程优质奖",
    width: 160,
    align: "center",
  },
  {
    title: "计划申报国家安装之星的装置",
    subTitle: "国家安装之星",
    dataIndex: "国家安装之星",
    width: 160,
    align: "center",
  },
];

export const resumeColumns = [
  {
    title: '名称',
    dataIndex: 'engin_name',
    key: 'engin_name',
    width: 160,
    render: (text: string) => text || '-',
  },
  {
    title: '时间',
    dataIndex: 'engin_time',
    key: 'engin_time',
    width: 160,
    render: (text: string) => text || '-',
  },
  {
    title: '等级',
    dataIndex: 'engin_level',
    key: 'engin_level',
    width: 160,
    render: (text: string) => text || '-',
  },
]