export const configColumns = [
  {
    title: "compinfo.form_no",
    subTitle: "id",
    dataIndex: "form_no",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.main_form_no",
    subTitle: "关联主表id",
    dataIndex: "main_form_no",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.lot_name",
    subTitle: "单个标段名称",
    dataIndex: "lot_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.lot_no",
    subTitle: "标段编号",
    dataIndex: "lot_no",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.site_demand_time",
    subTitle: "现场需求时间",
    dataIndex: "site_demand_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.site_demand_time",
    subTitle: "现场需求时间",
    dataIndex: "site_demand_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.procurement_method",
    subTitle: "采购方式",
    dataIndex: "procurement_method",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.procurement_method",
    subTitle: "采购方式",
    dataIndex: "procurement_method_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.plan_approve_time",
    subTitle: "采购计划批准时间",
    dataIndex: "plan_approve_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.plan_approve_time",
    subTitle: "采购计划批准时间",
    dataIndex: "plan_approve_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.doc_prepare_time",
    subTitle: "采购文件编制/签发时间",
    dataIndex: "doc_prepare_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.doc_prepare_time",
    subTitle: "采购文件编制/签发时间",
    dataIndex: "doc_prepare_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.tech_eval_time",
    subTitle: "技术评审报告时间",
    dataIndex: "tech_eval_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.tech_eval_time",
    subTitle: "技术评审报告时间",
    dataIndex: "tech_eval_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.comm_eval_time",
    subTitle: "商务评审报告时间",
    dataIndex: "comm_eval_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.comm_eval_time",
    subTitle: "商务评审报告时间",
    dataIndex: "comm_eval_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.loa_time",
    subTitle: "授标 (LOA) 时间",
    dataIndex: "loa_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.loa_time",
    subTitle: "授标 (LOA) 时间",
    dataIndex: "loa_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.po_time",
    subTitle: "签约 (PO) 时间",
    dataIndex: "po_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.po_time",
    subTitle: "签约 (PO) 时间",
    dataIndex: "po_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.procurement_wbs_code",
    subTitle: "采购执行方",
    dataIndex: "procurement_wbs_code",
    width: 160,
    align: "center",
  },
  {
    title: "总体策略议题名称",
    subTitle: "总体策略议题名称",
    dataIndex: "topic_name",
    width: 160,
    align: "center",
  },
];
