export const configColumns = [
  {
    title: "compinfo.id",
    subTitle: "主键ID",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.dep_code",
    subTitle: "depcode",
    dataIndex: "dep_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.dep_name",
    subTitle: "depname",
    dataIndex: "dep_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_code",
    subTitle: "制单人编码",
    dataIndex: "form_maker_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_name",
    subTitle: "制单人名称",
    dataIndex: "form_maker_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_time",
    subTitle: "制单时间",
    dataIndex: "form_make_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_tz",
    subTitle: "制单时区",
    dataIndex: "form_make_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.id",
    subTitle: "主键ID",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_no",
    subTitle: "formno",
    dataIndex: "form_no",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_code_id",
    subTitle: "配置id",
    dataIndex: "type_code_id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_code_name",
    subTitle: "配置名称",
    dataIndex: "type_code_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.num",
    subTitle: "数量",
    dataIndex: "num",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.ratio_num",
    subTitle: "比例",
    dataIndex: "ratio_num",
    width: 160,
    align: "center",
  },
];
