export const columns = [
  {
    title: "compinfo.id",
    subTitle: "id",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contract_no",
    subTitle: "合同编号",
    dataIndex: "contract_no",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.procurement_content",
    subTitle: "采购内容/结算依据",
    dataIndex: "procurement_content",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.wbs_code",
    subTitle: "采购单位",
    dataIndex: "wbs_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.buyer",
    subTitle: "采购员",
    dataIndex: "buyer",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.supplier_name",
    subTitle: "供应商名称",
    dataIndex: "supplier_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.supplier_code",
    subTitle: "供应商编码",
    dataIndex: "supplier_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.supplier_type",
    subTitle: "供应商管理类别",
    dataIndex: "supplier_type",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contract_amount",
    subTitle: "合同金额(元)",
    dataIndex: "contract_amount",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.year",
    subTitle: "所属年份",
    dataIndex: "year",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_ts",
    subTitle: "创建时间",
    dataIndex: "create_ts",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_ts",
    subTitle: "创建时间",
    dataIndex: "create_ts_str",
    width: 160,
    align: "center",
  },

  {
    title: "compinfo.create_tz",
    subTitle: "创建时区",
    dataIndex: "create_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_user_code",
    subTitle: "创建人编码",
    dataIndex: "create_user_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_user_name",
    subTitle: "创建人名称",
    dataIndex: "create_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_ts",
    subTitle: "修改时间",
    dataIndex: "modify_ts",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_ts",
    subTitle: "修改时间",
    dataIndex: "modify_ts_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_tz",
    subTitle: "修改时区",
    dataIndex: "modify_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_user_code",
    subTitle: "修改人编码",
    dataIndex: "modify_user_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_user_name",
    subTitle: "修改人名称",
    dataIndex: "modify_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.h_id",
    subTitle: "表头主键",
    dataIndex: "h_id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.id",
    subTitle: "表体主键",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contract_id",
    subTitle: "供应商合同id",
    dataIndex: "contract_id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.product_quality",
    subTitle: "产品质量20分",
    dataIndex: "product_quality",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.service_ability",
    subTitle: "服务能力15分",
    dataIndex: "service_ability",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contract_performance",
    subTitle: "合同履约15分",
    dataIndex: "contract_performance",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.price_level",
    subTitle: "价格水平15分",
    dataIndex: "price_level",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.technological_level",
    subTitle: "技术水平10分",
    dataIndex: "technological_level",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.integrity_management",
    subTitle: "诚信经营10分",
    dataIndex: "integrity_management",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.total_score",
    subTitle: "总成绩85分",
    dataIndex: "total_score",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.delivery_amount",
    subTitle: "ERP到货金额元",
    dataIndex: "delivery_amount",
    width: 160,
    align: "center",
  },
]
