export default {
  "compinfo.id": "id",
  "compinfo.wbs_code": "wbsCode",
  "compinfo.prop_key": "层级（branchComp：公司级，subComp：分公司，dep：项目部）",
  "compinfo.plan_id": "培训计划",
  "compinfo.year": "所属年份",
  "compinfo.organizer": "承办单位",
  "compinfo.class_name": "培训班名称",
  "compinfo.training_target": "培训对象",
  "compinfo.training_type": "培训方式",
  "compinfo.start_time": "开始时间",
  "compinfo.end_time": "结束时间",
  "compinfo.monitor": "班长",
  "compinfo.create_ts": "创建时间",
  "compinfo.create_tz": "创建时区",
  "compinfo.create_user_code": "创建人编码",
  "compinfo.create_user_name": "创建人名称",
  "compinfo.modify_ts": "修改时间",
  "compinfo.modify_tz": "修改时区",
  "compinfo.modify_user_code": "修改人编码",
  "compinfo.modify_user_name": "修改人名称",
};
