export const configColumns = [
  {
    title: "compinfo.project_name",
    subTitle: "项目名称",
    dataIndex: "project_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contract_mode_str",
    subTitle: "合同类型",
    dataIndex: "contract_mode_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_level_str",
    subTitle: "项目等级",
    dataIndex: "project_level_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.specialty_type_str",
    subTitle: "专业类别",
    dataIndex: "specialty_type_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.region_category_str",
    subTitle: "地域类别",
    dataIndex: "region_category_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.owner_group_str",
    subTitle: "系统分类",
    dataIndex: "owner_group_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contract_say_price",
    subTitle: "合同金额万元",
    dataIndex: "contract_say_price",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.curr_week_plan",
    subTitle: "计划进度",
    dataIndex: "curr_week_plan",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.curr_week_reality",
    subTitle: "实际进度",
    dataIndex: "curr_week_reality",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.curr_week_difference",
    subTitle: "偏离计划",
    dataIndex: "curr_week_difference",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.construction_dep",
    subTitle: "建设单位",
    dataIndex: "construction_dep",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.general_contractor_name",
    subTitle: "总承包单位",
    dataIndex: "general_contractor_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_status_str",
    subTitle: "项目状态",
    dataIndex: "project_status_str",
    width: 160,
    align: "center",
  },
];
