export const configColumns = [
  {
    title: "RiskControlConfig.RowNumber",
    subTitle: "序号",
    dataIndex: "RowNumber",
    width: 160,
    align: "center",
  },
  {
    title: "RiskControlConfig.id",
    subTitle: "序号",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "RiskControlConfig.wbs_code",
    subTitle: "项目部",
    dataIndex: "wbs_code",
    width: 180,
    align: "center",
  },
  {
    title: "RiskControlConfig.wbs_code",
    subTitle: "项目部",
    dataIndex: "wbs_name",
    width: 160,
    align: "center",
  },
  {
    title: "RiskCategoryConfig.dict_type",
    subTitle: "配置类型",
    dataIndex: "dict_type",
    width: 160,
    align: "center",
  },
  {
    title: "RiskCategoryConfig.category_name",
    subTitle: "配置名称",
    dataIndex: "category_name",
    width: 160,
    align: "center",
  },
  {
    title: "RiskCategoryConfig.category_name2",
    subTitle: "配置名称",
    dataIndex: "category_name2",
    width: 160,
    align: "center",
  },
  {
    title: "RiskCategoryConfig.parent_id",
    subTitle: "根节点",
    dataIndex: "parent_id",
    width: 160,
    align: "center",
  },
  {
    title: "RiskCategoryConfig.parent_id_2",
    subTitle: "二级节点",
    dataIndex: "parent_id_2",
    width: 160,
    align: "center",
  },
];
