export const configColumns = [
  {
    title: "compinfo.id",
    subTitle: "id",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.year",
    subTitle: "所属年份",
    dataIndex: "year",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.upload_date_start",
    subTitle: "合同上传开始日期",
    dataIndex: "upload_date_start",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.upload_date_end",
    subTitle: "合同上传结束日期",
    dataIndex: "upload_date_end",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.calculate_start_date",
    subTitle: "计算供应商分数开始日期",
    dataIndex: "calculate_start_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.calculate_end_date",
    subTitle: "计算供应商分数结束日期",
    dataIndex: "calculate_end_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.score_date_start",
    subTitle: "合同打分开始日期",
    dataIndex: "score_date_start",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.score_date_end",
    subTitle: "合同打分结束日期",
    dataIndex: "score_date_end",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_ts",
    subTitle: "创建时间",
    dataIndex: "create_ts",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_tz",
    subTitle: "创建时区",
    dataIndex: "create_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_user_code",
    subTitle: "创建人编码",
    dataIndex: "create_user_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_user_name",
    subTitle: "创建人名称",
    dataIndex: "create_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_ts",
    subTitle: "修改时间",
    dataIndex: "modify_ts",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_tz",
    subTitle: "修改时区",
    dataIndex: "modify_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_user_code",
    subTitle: "修改人编码",
    dataIndex: "modify_user_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_user_name",
    subTitle: "修改人名称",
    dataIndex: "modify_user_name",
    width: 160,
    align: "center",
  },
];
