export const configColumns = [
  {
    title: "compinfo.id",
    subTitle: "自增主键",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.temporary_wbs_define_code",
    subTitle: "临时项目定义",
    dataIndex: "temporary_wbs_define_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.wbs_define_code",
    subTitle: "项目定义",
    dataIndex: "wbs_define_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.wbs_define_name",
    subTitle: "项目名称",
    dataIndex: "wbs_define_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.wbs_major_category",
    subTitle: "项目大类",
    dataIndex: "wbs_major_category",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.wbs_medium_category",
    subTitle: "项目中类",
    dataIndex: "wbs_medium_category",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.wbs_minor_category",
    subTitle: "项目小类",
    dataIndex: "wbs_minor_category",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.profit_center_code",
    subTitle: "利润中心",
    dataIndex: "profit_center_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.profit_wbs_name",
    subTitle: "名称",
    dataIndex: "profit_wbs_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.profit_belong_wbs_name",
    subTitle: "分公司",
    dataIndex: "profit_belong_wbs_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.business_partner",
    subTitle: "往来单位",
    dataIndex: "business_partner",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.client_name",
    subTitle: "客户名称",
    dataIndex: "client_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.trade_partner",
    subTitle: "贸易伙伴",
    dataIndex: "trade_partner",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.company_name",
    subTitle: "公司名称",
    dataIndex: "company_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.company_size",
    subTitle: "企业规模",
    dataIndex: "company_size",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.company_size_description",
    subTitle: "企业规模描述",
    dataIndex: "company_size_description",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.operating_status",
    subTitle: "经营状态",
    dataIndex: "operating_status",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.operation_status_description",
    subTitle: "经营状态描述",
    dataIndex: "operation_status_description",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_year",
    subTitle: "立项年度",
    dataIndex: "project_year",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.plan_start_time",
    subTitle: "计划开始日期",
    dataIndex: "plan_start_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.plan_finish_time",
    subTitle: "计划完成日期",
    dataIndex: "plan_finish_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_system_status",
    subTitle: "项目系统状态",
    dataIndex: "project_system_status",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.income_method",
    subTitle: "收入确认方式",
    dataIndex: "income_method",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.fmis_self_six_code",
    subTitle: "FMIS自辅06编号",
    dataIndex: "fmis_self_six_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.fmis_self_six_name",
    subTitle: "FMIS自辅06名称",
    dataIndex: "fmis_self_six_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_level",
    subTitle: "项目等级",
    dataIndex: "project_level",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_address",
    subTitle: "项目地点",
    dataIndex: "project_address",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_location",
    subTitle: "项目部所在地",
    dataIndex: "project_location",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.responsible_person",
    subTitle: "负责人",
    dataIndex: "responsible_person",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contact_information",
    subTitle: "联系方式",
    dataIndex: "contact_information",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.main_workload",
    subTitle: "主要工作量",
    dataIndex: "main_workload",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.inside_outside_group",
    subTitle: "集团内外",
    dataIndex: "inside_outside_group",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark",
    subTitle: "备注",
    dataIndex: "remark",
    width: 160,
    align: "center",
  },
];
