export const configColumns = [
  {
    title: "PerformanceLedger.contract_income_id",
    subTitle: "选择收入合同",
    dataIndex: "contract_income_id",
    width: 160,
    align: "center",
  },
  {
    title: "PerformanceLedger.performance_type",
    subTitle: "业绩类型",//(收入合同的项目分类)
    dataIndex: "performance_type",
    width: 160,
    align: "center",
  },
  {
    title: "PerformanceLedger.performance_detail",
    subTitle: "业绩细分",
    dataIndex: "performance_detail",
    width: 160,
    align: "center",
  },
  {
    title: "PerformanceLedger.performance_detail",
    subTitle: "业绩细分",
    dataIndex: "performance_detail_name",
    width: 160,
    align: "center",
  },
  {
    title: "PerformanceLedger.project_name",
    subTitle: "项目名称",
    dataIndex: "project_name",
    width: 160,
    align: "center",
  },
  {
    title: "PerformanceLedger.construction_unit",
    subTitle: "建设单位",//(甲方单位名称)
    dataIndex: "construction_unit",
    width: 160,
    align: "center",
  },
  {
    title: "PerformanceLedger.branch_company",
    subTitle: "承接工程分公司",
    dataIndex: "branch_company",
    width: 160,
    align: "center",
  },
  {
    title: "PerformanceLedger.contract_mode",
    subTitle: "承包方式",
    dataIndex: "contract_mode",
    width: 160,
    align: "center",
  },
  {
    title: "PerformanceLedger.contract_type",
    subTitle: "合同类型",
    dataIndex: "contract_type",
    width: 160,
    align: "center",
  },
  {
    title: "PerformanceLedger.start_date",
    subTitle: "开工日期",
    dataIndex: "start_date",
    width: 160,
    align: "center",
  },
  {
    title: "PerformanceLedger.end_date",
    subTitle: "竣工日期",
    dataIndex: "end_date",
    width: 160,
    align: "center",
  },
  {
    title: "PerformanceLedger.start_date_str",
    subTitle: "开工日期",
    dataIndex: "start_date_str",
    width: 160,
    align: "center",
  },
  {
    title: "PerformanceLedger.end_date_str",
    subTitle: "竣工日期",
    dataIndex: "end_date_str",
    width: 160,
    align: "center",
  },
  {
    title: "PerformanceLedger.contract_amount",
    subTitle: "合同金额（万元）",
    dataIndex: "contract_amount",
    width: 180,
    align: "center",
  },
  {
    title: "PerformanceLedger.work_scope",
    subTitle: "工作范围",
    dataIndex: "work_scope",
    width: 160,
    align: "center",
  },
  {
    title: "PerformanceLedger.contract_year",
    subTitle: "合同年份",
    dataIndex: "contract_year",
    width: 160,
    align: "center",
  },
  {
    title: "PerformanceLedger.main_engineering",
    subTitle: "主要工程内容",
    dataIndex: "main_engineering",
    width: 160,
    align: "center",
  },
  {
    title: "PerformanceLedger.contract_key_pages",
    subTitle: "合同关键页",
    dataIndex: "contract_key_pages",
    width: 160,
    align: "center",
  },
  {
    title: "PerformanceLedger.handover_report",
    subTitle: "中间交接证书/竣工报告",
    dataIndex: "handover_report",
    width: 280,
    align: "center",
  },
  {
    title: "PerformanceLedger.id",
    subTitle: "序号",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "PerformanceLedger.RowNumber",
    subTitle: "序号",
    dataIndex: "RowNumber",
    width: 160,
    align: "center",
  },
];
