export const configColumns = [
  {
    title: "InspectorSeniorityApply.sub_comp_code",
    subTitle: "分公司",
    dataIndex: "sub_comp_name",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.dep_code",
    subTitle: "项目部",
    dataIndex: "dep_name",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.name",
    subTitle: "姓名",
    dataIndex: "name",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.gender",
    subTitle: "性别",
    dataIndex: "gender",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.birth_date",
    subTitle: "出生日期",
    dataIndex: "birth_date",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.job",
    subTitle: "职务",
    dataIndex: "job",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.job_title",
    subTitle: "职称",
    dataIndex: "job_title",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.work_date",
    subTitle: "参加工作时间",
    dataIndex: "work_date",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.education",
    subTitle: "文化程度",
    dataIndex: "education",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.employee_no",
    subTitle: "员工编号",
    dataIndex: "employee_no",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.graduation_school",
    subTitle: "毕业院校",
    dataIndex: "graduation_school",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.major",
    subTitle: "所学专业",
    dataIndex: "major",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.department",
    subTitle: "所在单位部门",
    dataIndex: "department",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.post",
    subTitle: "现从事岗位",
    dataIndex: "post",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.train_date",
    subTitle: "培训时间",
    dataIndex: "train_date",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.train_grade",
    subTitle: "培训成绩",
    dataIndex: "train_grade",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.application_project",
    subTitle: "申请操作项目",
    dataIndex: "application_project",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.phone",
    subTitle: "联系电话",
    dataIndex: "phone",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.on_duty",
    subTitle: "在岗状态",
    dataIndex: "on_duty",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.related_work_date",
    subTitle: "从事质检或相关工作时间",
    dataIndex: "related_work_date",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.apply_major",
    subTitle: "申请检查专业",
    dataIndex: "apply_major",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.job_resume",
    subTitle: "工作简历",
    dataIndex: "job_resume",
    width: 210,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.approval_date",
    subTitle: "审批时间",
    dataIndex: "approval_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.employee_number",
    subTitle: "员工编号",
    dataIndex: "employee_number",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.name",
    subTitle: "姓名",
    dataIndex: "name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.phone",
    subTitle: "电话号码",
    dataIndex: "phone",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.current_unit",
    subTitle: "现单位",
    dataIndex: "current_unit",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.employment_type",
    subTitle: "用工形式",
    dataIndex: "employment_type",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.employment_type",
    subTitle: "用工形式",
    dataIndex: "employment_type_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.gender",
    subTitle: "性别",
    dataIndex: "gender",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.nation",
    subTitle: "民族",
    dataIndex: "nation",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.nation",
    subTitle: "民族",
    dataIndex: "nation_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.operation_project",
    subTitle: "作业项目",
    dataIndex: "operation_project",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.operation_project",
    subTitle: "作业项目",
    dataIndex: "operation_project_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.education",
    subTitle: "文化程度",
    dataIndex: "education",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.education",
    subTitle: "文化程度",
    dataIndex: "education_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.skill_level",
    subTitle: "职业技能等级",
    dataIndex: "skill_level",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.skill_level",
    subTitle: "职业技能等级",
    dataIndex: "skill_level_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.id_card",
    subTitle: "身份证号",
    dataIndex: "id_card",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.address",
    subTitle: "身份证地址",
    dataIndex: "address",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.file_no",
    subTitle: "档案编号",
    dataIndex: "file_no",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.health_status",
    subTitle: "职业健康状况",
    dataIndex: "health_status",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.review_date",
    subTitle: "复审日期",
    dataIndex: "review_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.next_review_date",
    subTitle: "下次审核日期",
    dataIndex: "next_review_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.violation_statuse",
    subTitle: "违章作业情况",
    dataIndex: "violation_status",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.work_start_date",
    subTitle: "参加工作时间",
    dataIndex: "work_start_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.work_years",
    subTitle: "从事本工种年限",
    dataIndex: "work_years",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.remark",
    subTitle: "备注",
    dataIndex: "remark",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_ts_str",
    subTitle: "创建时间",
    dataIndex: "create_ts_format",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_ts_str",
    subTitle: "创建时间",
    dataIndex: "create_ts_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_user_name",
    subTitle: "创建人名称",
    dataIndex: "create_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_ts_str",
    subTitle: "修改时间",
    dataIndex: "modify_ts_format",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_ts_str",
    subTitle: "修改时间",
    dataIndex: "modify_ts_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_user_name",
    subTitle: "修改人名称",
    dataIndex: "modify_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "levelConstructor.url",
    subTitle: "附件",
    dataIndex: "url",
    width: 160,
    align: "center",
  },
  {
    title: "common.status",
    subTitle: "审批状态",
    dataIndex: "approval_status",
    width: 160,
    align: "center",
  },

];