export const configColumns = [
  {
    title: "scheduleManagement.wbs_code",
    subTitle: "wbs编码",
    dataIndex: "wbs_code",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.country",
    subTitle: "项目所在国",
    dataIndex: "country",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.province",
    subTitle: "项目所在省/直辖市",
    dataIndex: "province",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.city",
    subTitle: "城市",
    dataIndex: "city",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.area",
    subTitle: "区域",
    dataIndex: "area",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.address",
    subTitle: "项目部详细地址",
    dataIndex: "address",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.branch_comp_name",
    subTitle: "上报单位(分公司)",
    dataIndex: "branch_comp_name",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.dep_name",
    subTitle: "项目经理部",
    dataIndex: "dep_name",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.specialty_type_name",
    subTitle: "专业类型",
    dataIndex: "specialty_type_name",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.project_level_name",
    subTitle: "项目等级",
    dataIndex: "project_level_name",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.contract_start_date_format",
    subTitle: "合同开工日期",
    dataIndex: "contract_start_date_format",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.contract_end_date",
    subTitle: "合同完工日期",
    dataIndex: "contract_end_date_format",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.actual_start_date",
    subTitle: "实际开工日期",
    dataIndex: "actual_start_date_format",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.actual_end_date_format",
    subTitle: "实际完工日期",
    dataIndex: "actual_end_date_format",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.plan_finish_date",
    subTitle: "预计完工日期",
    dataIndex: "plan_finish_date_format",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.next_month_plan",
    subTitle: "本月计划（%）",
    dataIndex: "next_month_plan",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.curr_month_reality",
    subTitle: "本月实际进度（%）",
    dataIndex: "curr_month_reality",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.curr_month_plan",
    subTitle: "当前累计计划进度（%）",
    dataIndex: "curr_month_plan",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.cumulative_month_reality",
    subTitle: "当前累计实际进度（%）",
    dataIndex: "cumulative_month_reality",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.delay_reasons",
    subTitle: "滞后原因",
    dataIndex: "delay_reasons",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.year",
    subTitle: "统计年",
    dataIndex: "year",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.month",
    subTitle: "统计月",
    dataIndex: "month",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.month_plan_total_value",
    subTitle: "本月计划产值（万元）",
    dataIndex: "month_plan_total_value",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.month_reality_total_value",
    subTitle: "本月实际产值（万元）",
    dataIndex: "month_reality_total_value",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.annual_plan_output_value",
    subTitle: "本年计划产值（万元）",
    dataIndex: "annual_plan_output_value",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.curr_year_output_value",
    subTitle: "本年实际产值（万元）",
    dataIndex: "curr_year_output_value",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.cumulative_output_value",
    subTitle: "自开工累计产值（万元）",
    dataIndex: "cumulative_output_value",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.designer_total_count",
    subTitle: "设计人员",
    dataIndex: "designer_total_count",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.manager_total_count",
    subTitle: "管理人员",
    dataIndex: "manager_total_count",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.worker_total_count",
    subTitle: "施工人员",
    dataIndex: "worker_total_count",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.hrp_total_count",
    subTitle: "采办人员",
    dataIndex: "hrp_total_count",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.owner_group_name",
    subTitle: "系统分类",
    dataIndex: "owner_group_name",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.project_status",
    subTitle: "采办人员",
    dataIndex: "project_status_name",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.project_subject",
    subTitle: "项目概况",
    dataIndex: "project_subject",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.project_quantities",
    subTitle: "项目工程量",
    dataIndex: "project_quantities",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.next_plan",
    subTitle: "本月计划安排形象进度描述及主要节点安排",
    dataIndex: "next_plan",
    width: 270,
    align: "center",
  },
  {
    title: "scheduleManagement.this_month",
    subTitle: "实际完成进度描述",
    dataIndex: "this_month",
    width: 210,
    align: "center",
  },
  // ==================
  {
    title: "scheduleManagement.region_category",
    subTitle: "地域类型",
    dataIndex: "region_category",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.owner_group",
    subTitle: "系统分类",
    dataIndex: "owner_group",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.sign_status",
    subTitle: "签约情况",
    dataIndex: "sign_status",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.erp_code",
    subTitle: "ERP编码",
    dataIndex: "erp_code",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.epm_code",
    subTitle: "EPM编码",
    dataIndex: "epm_code",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.create_dep_code",
    subTitle: "创建单位",
    dataIndex: "create_dep_code",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.report_dep_code",
    subTitle: "填报单位",
    dataIndex: "report_dep_code",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.project_name",
    subTitle: "项目名称",
    dataIndex: "project_name",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.contract_no",
    subTitle: "合同号",
    dataIndex: "contract_no",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.contract_status",
    subTitle: "合同状态",
    dataIndex: "contract_status",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.plan_finish_date",
    subTitle: "预计完工日期",
    dataIndex: "plan_finish_date",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.warranty_period",
    subTitle: "合同质保期",
    dataIndex: "warranty_period",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.project_category",
    subTitle: "专业分类",
    dataIndex: "project_category",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.three_new_category",
    subTitle: "三新分类",
    dataIndex: "three_new_category",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.sub_category",
    subTitle: "专业细分",
    dataIndex: "sub_category",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.contract_mode",
    subTitle: "合同类型",
    dataIndex: "contract_mode",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.contract_mode",
    subTitle: "合同类型",
    dataIndex: "contract_mode_name",
    width: 160,
    align: "center",
  },
  
  {
    title: "scheduleManagement.project_level",
    subTitle: "项目等级",
    dataIndex: "project_level",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.is_guaranty",
    subTitle: "是否由中油工程担保",
    dataIndex: "is_guaranty",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.is_related",
    subTitle: "是否CPECC内部关联项目",
    dataIndex: "is_related",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.import_level",
    subTitle: "项目重要级别",
    dataIndex: "import_level",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.project_status",
    subTitle: "项目状态",
    dataIndex: "project_status",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.project_subject",
    subTitle: "项目概况",
    dataIndex: "project_subject",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.project_quantities",
    subTitle: "项目工程量",
    dataIndex: "project_quantities",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.project_significance",
    subTitle: "项目意义",
    dataIndex: "project_significance",
    width: 160,
    align: "center",
  },
  
  {
    title: "scheduleManagement.project_director",
    subTitle: "项目主任",
    dataIndex: "project_director",
    width: 160,
    align: "center",
  },



  {
    title: "scheduleManagement.contract_say_price",
    subTitle: "合同金额（含税）",
    dataIndex: "contract_say_price",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.contract_un_say_price",
    subTitle: "合同金额（不含税）",
    dataIndex: "contract_un_say_price",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.contract_sign_date",
    subTitle: "合同签署日期",
    dataIndex: "contract_sign_date",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.contract_start_date",
    subTitle: "合同生效日期",
    dataIndex: "contract_start_date",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.contract_start_date",
    subTitle: "合同生效日期",
    dataIndex: "contract_start_date_format",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.actual_start_date",
    subTitle: "实际开工日期",
    dataIndex: "actual_start_date",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.contract_end_date",
    subTitle: "合同完工日期",
    dataIndex: "contract_end_date",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.contract_end_date",
    subTitle: "合同完工日期",
    dataIndex: "contract_end_date_format",
    width: 160,
    align: "center",
  },

  {
    title: "scheduleManagement.director_phone",
    subTitle: "联系电话",
    dataIndex: "director_phone",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.director_email",
    subTitle: "电子邮箱",
    dataIndex: "director_email",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.project_manager",
    subTitle: "项目经理",
    dataIndex: "project_manager",
    width: 160,
    align: "center",
  },

  {
    title: "scheduleManagement.manager_phone",
    subTitle: "项目经理联系电话",
    dataIndex: "manager_phone",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.manager_email",
    subTitle: "项目经理电子邮箱",
    dataIndex: "manager_email",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.project_contact",
    subTitle: "项目联系人",
    dataIndex: "project_contact",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.contact_phone",
    subTitle: "项目联系人电话",
    dataIndex: "contact_phone",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.contact_email",
    subTitle: "项目联系人邮箱",
    dataIndex: "contact_email",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.project_doc_control",
    subTitle: "项目文控",
    dataIndex: "project_doc_control",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.dc_phone",
    subTitle: "项目文控联系电话",
    dataIndex: "dc_phone",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.dc_email",
    subTitle: "项目文控电子邮箱",
    dataIndex: "dc_email",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.construction_dep",
    subTitle: "建设单位",
    dataIndex: "construction_dep",
    width: 160,
    align: "center",
  },


  {
    title: "scheduleManagement.construction_dep_contact",
    subTitle: "建设单位联系人",
    dataIndex: "construction_dep_contact",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.construction_dep_phone",
    subTitle: "建设单位联系电话",
    dataIndex: "construction_dep_phone",
    width: 160,
    align: "center",
  },

  {
    title: "scheduleManagement.construction_dep_email",
    subTitle: "建设单位电子邮箱",
    dataIndex: "construction_dep_email",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.pmc_pmt_dep",
    subTitle: "PMC/PMT单位",
    dataIndex: "pmc_pmt_dep",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.pmc_pmt_contact",
    subTitle: "PMC/PMT联系人",
    dataIndex: "pmc_pmt_contact",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.pmc_pmt_phone",
    subTitle: "PMC/PMT联系电话",
    dataIndex: "pmc_pmt_phone",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.pmc_pmt_email",
    subTitle: "PMC/PMT电子邮箱",
    dataIndex: "pmc_pmt_email",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.supervision_dep",
    subTitle: "监理单位",
    dataIndex: "supervision_dep",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.supervision_dep_contact",
    subTitle: "监理单位联系人",
    dataIndex: "supervision_dep_contact",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.supervision_dep_phone",
    subTitle: "监理单位联系电话",
    dataIndex: "supervision_dep_phone",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.supervision_dep_email",
    subTitle: "监理单位电子邮箱",
    dataIndex: "supervision_dep_email",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.general_contractor_data",
    subTitle: "总承包单位",
    dataIndex: "general_contractor_data",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.design_dep_data",
    subTitle: "设计单位",
    dataIndex: "design_dep_data",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.purchase_dep_data",
    subTitle: "采购单位",
    dataIndex: "purchase_dep_data",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.internal_dep_data",
    subTitle: "内部施工单位",
    dataIndex: "internal_dep_data",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.external_dep_data",
    subTitle: "外部施工单位",
    dataIndex: "external_dep_data",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.ndt_dep_data",
    subTitle: "无损检测单位",
    dataIndex: "ndt_dep_data",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.operation_dep_data",
    subTitle: "投产运行单位",
    dataIndex: "operation_dep_data",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.project_location",
    subTitle: "项目地点",
    dataIndex: "project_location",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.longitude",
    subTitle: "经度",
    dataIndex: "longitude",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.latitude",
    subTitle: "纬度",
    dataIndex: "latitude",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.area_data",
    subTitle: "区域",
    dataIndex: "area_data",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.create_ts",
    subTitle: "录入时间",
    dataIndex: "create_ts",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.create_user_name",
    subTitle: "录入人名称",
    dataIndex: "create_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.modify_user_name",
    subTitle: "修改人名称",
    dataIndex: "modify_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.modify_ts_format",
    subTitle: "修改时间",
    dataIndex: "modify_ts_format",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.create_ts",
    subTitle: "录入时间",
    dataIndex: "create_ts_format",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.flow_status",
    subTitle: "审批状态",
    dataIndex: "flow_status",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.flow_status",
    subTitle: "审批状态",
    dataIndex: "flow_status_name",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.calculate_date",
    subTitle: "计算合同工期",
    dataIndex: "calculate_date",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.sign_status",
    subTitle: "合同签约情况",
    dataIndex: "sign_status",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.contract_currency",
    subTitle: "合同币种",
    dataIndex: "contract_currency",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.RMB_rate",
    subTitle: "人民币汇率",
    dataIndex: "RMB_rate",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.equivalent_RMB_price",
    subTitle: "折合人民币(含税)",
    dataIndex: "equivalent_RMB_price",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.equivalent_RMB_un_price",
    subTitle: "折合人民币(不含税)",
    dataIndex: "equivalent_RMB_un_price",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.US_rate",
    subTitle: "美元汇率",
    dataIndex: "US_rate",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.equivalent_US_price",
    subTitle: "折合美元(含税)",
    dataIndex: "equivalent_US_price",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.equivalent_US_un_price",
    subTitle: "折合美元(不含税)",
    dataIndex: "equivalent_US_un_price",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.RMB_Total_price",
    subTitle: "人民币合计(含税)",
    dataIndex: "RMB_Total_price",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.RMB_Total_un_price",
    subTitle: "人民币合计(不含税)",
    dataIndex: "RMB_Total_un_price",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.US_Total_price",
    subTitle: "美元合计(含税)",
    dataIndex: "US_Total_price",
    width: 160,
    align: "center",
  },
  {
    title: "scheduleManagement.US_Total_un_price",
    subTitle: "美元合计(不含税)",
    dataIndex: "US_Total_un_price",
    width: 160,
    align: "center",
  },


];
