export const configColumns = [
  {
    title: "compinfo.form_no",
    subTitle: "主键ID",
    dataIndex: "form_no",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.out_info_id",
    subTitle: "分包合同id",
    dataIndex: "out_info_id",
    width: 160,
    align: "center",
  },
  {
    title: "工程名称",
    subTitle: "工程名称",
    dataIndex: "contract_out_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.record_name",
    subTitle: "记录名称",
    dataIndex: "record_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.approval_process_id",
    subTitle: "审批流程ID",
    dataIndex: "approval_process_id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.status",
    subTitle: "审批状态（-1:审批驳回,0-未审批，1-审批中，2-审批完成）",
    dataIndex: "status",
    width: 160,
    align: "center",
  },
  {
    title: "归档时间",
    subTitle: "归档时间",
    dataIndex: "approval_date",
    width: 160,
    align: "center",
  },
  {
    title: "归档时间",
    subTitle: "归档时间",
    dataIndex: "approval_date_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.dep_code",
    subTitle: "(项目部)",
    dataIndex: "dep_code",
    width: 160,
    align: "center",
  },
  {
    title: "项目名称",
    subTitle: "项目名称",
    dataIndex: "dep_name",
    width: 160,
    align: "center",
  },
  {
    title: "工程分公司/指挥部名称",
    subTitle: "工程分公司/指挥部名称",
    dataIndex: "up_wbs_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_code",
    subTitle: "制单人编码",
    dataIndex: "form_maker_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_name",
    subTitle: "制单人名称",
    dataIndex: "form_maker_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_time",
    subTitle: "制单时间",
    dataIndex: "form_make_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_time",
    subTitle: "制单时间",
    dataIndex: "form_make_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_tz",
    subTitle: "制单时区",
    dataIndex: "form_make_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.archive_num",
    subTitle: "数量",
    dataIndex: "archive_num",
    width: 160,
    align: "center",
  },

];
