export const configColumns = [
    {
      title: "compinfo.id",
      subTitle: "主键ID",
      dataIndex: "id",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.work_permit_code",
      subTitle: "作业许可证编号",
      dataIndex: "work_permit_code",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.work_content",
      subTitle: "作业内容名称",
      dataIndex: "work_content",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.work_content",
      subTitle: "作业内容名称",
      dataIndex: "work_content_name",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.work_location",
      subTitle: "作业地点",
      dataIndex: "work_location",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.wbs_code",
      subTitle: "作业单位",
      dataIndex: "wbs_code",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.wbs_code",
      subTitle: "作业单位",
      dataIndex: "wbs_name",
      width: 160,
      align: "center",
    },
    {
      title: "costControl.branch_comp_name",
      subTitle: "分公司名称",
      dataIndex: "branch_comp_code",
      width: 160,
      align: "center",
    },
    {
      title: "costControl.branch_comp_name",
      subTitle: "分公司名称",
      dataIndex: "branch_comp_name",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.start_time",
      subTitle: "作业开始时间",
      dataIndex: "start_time",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.start_time",
      subTitle: "作业开始时间",
      dataIndex: "start_time_str",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.end_time",
      subTitle: "作业结束时间",
      dataIndex: "end_time",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.end_time",
      subTitle: "作业结束时间",
      dataIndex: "end_time_str",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.approver",
      subTitle: "作业批准人",
      dataIndex: "approver",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.guardian",
      subTitle: "作业监护人",
      dataIndex: "guardian",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.recorder",
      subTitle: "记录人",
      dataIndex: "recorder",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.depCode",
      subTitle: "项目经理部",
      dataIndex: "dep_name",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.remark",
      subTitle: "备注",
      dataIndex: "remark",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.create_ts_str",
      subTitle: "创建时间",
      dataIndex: "create_ts_str",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.create_user_name",
      subTitle: "创建人名称",
      dataIndex: "create_user_name",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.modify_ts_str",
      subTitle: "修改时间",
      dataIndex: "modify_ts_str",
      width: 160,
      align: "center",
    },
    {
      title: "wrokLicenseRegister.modify_user_name",
      subTitle: "修改人名称",
      dataIndex: "modify_user_name",
      width: 160,
      align: "center",
    },
    {
      title: "contract.file_url",
      subTitle: "附件",
      dataIndex: "url",
      width: 160,
      align: "center",
    },
    {
      title: "scheduleManagement.flow_status",
      subTitle: "审批状态",
      dataIndex: "flow_status",
      width: 160,
      align: "center",
    }
  ];
