export const configColumns = [
    {
      title: "compinfo.id",
      subTitle: "主键ID",
      dataIndex: "id",
      width: 160,
      align: "center",
    },
    {
      title: "国家优质工程等奖励情况",
      subTitle: "国家优质工程等奖励情况",
      dataIndex: "national_association",
      width: 160,
      align: "center",
    },
    {
      title: "专业协会优质工程等奖励情况",
      subTitle: "专业协会优质工程等奖励情况",
      dataIndex: "specialty_association",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.group_company_awards",
      subTitle: "集团公司优质工程等奖励情况",
      dataIndex: "group_company_awards",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.dep_code",
      subTitle: "depcode",
      dataIndex: "dep_code",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.form_maker_code",
      subTitle: "制单人编码",
      dataIndex: "form_maker_code",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.form_maker_name",
      subTitle: "制单人名称",
      dataIndex: "form_maker_name",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.form_make_time",
      subTitle: "制单时间",
      dataIndex: "form_make_time",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.form_make_time",
      subTitle: "制单时间",
      dataIndex: "form_make_time_str",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.form_make_tz",
      subTitle: "制单时区",
      dataIndex: "form_make_tz",
      width: 160,
      align: "center",
    },
  ];
