import PublishStatus from "@/pages/HR/Common/PublishStatus";

export const configColumns = [
  {
    title: "compinfo.id",
    subTitle: "自增主键",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.wbs_code",
    subTitle: "wbsCode",
    dataIndex: "wbs_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.prop_key",
    subTitle: "层级branchComp公司级",
    dataIndex: "prop_key",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.subComp",
    subTitle: "分公司",
    dataIndex: "subComp",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.dep",
    subTitle: "项目部",
    dataIndex: "dep",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.paper_name",
    subTitle: "试卷名称",
    dataIndex: "paper_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.module_code",
    subTitle: "模块号",
    dataIndex: "module_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.module_code",
    subTitle: "模块号",
    dataIndex: "module_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.class_type",
    subTitle: "课程分类",
    dataIndex: "class_type",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.grade",
    subTitle: "岗位级别",
    dataIndex: "grade",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.grade",
    subTitle: "岗位级别",
    dataIndex: "grade_name",
    width: 160,
    align: "center",
  },

  {
    title: "compinfo.start_time",
    subTitle: "开始时间",
    dataIndex: "start_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.end_time",
    subTitle: "结束时间",
    dataIndex: "end_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.publish_status",
    subTitle: "发布状态0未发布",
    dataIndex: "publish_status",
    width: 160,
    align: "center",
    render: (h, params) => {
      return (
        <PublishStatus text={h}/>
      )
    }
  },
  {
    title: "compinfo.is_allow_apply",
    subTitle: "是否允许报名",
    dataIndex: "is_allow_apply",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.is_allow_apply",
    subTitle: "是否允许报名",
    dataIndex: "is_allow_apply_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.total_score",
    subTitle: "试卷总分",
    dataIndex: "total_score",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.pass_score",
    subTitle: "及格分数",
    dataIndex: "pass_score",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.single_count",
    subTitle: "单选题数量",
    dataIndex: "single_count",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.single_score",
    subTitle: "单选题分数",
    dataIndex: "single_score",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.judge_count",
    subTitle: "判断题数量",
    dataIndex: "judge_count",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.judge_score",
    subTitle: "判断题分数",
    dataIndex: "judge_score",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.other_count",
    subTitle: "简答题数量",
    dataIndex: "other_count",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.other_score",
    subTitle: "简答题分数",
    dataIndex: "other_score",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_ts",
    subTitle: "创建时间",
    dataIndex: "create_ts",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_tz",
    subTitle: "创建时区",
    dataIndex: "create_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_user_code",
    subTitle: "创建人编码",
    dataIndex: "create_user_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_user_name",
    subTitle: "创建人名称",
    dataIndex: "create_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_ts",
    subTitle: "修改时间",
    dataIndex: "modify_ts",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_tz",
    subTitle: "修改时区",
    dataIndex: "modify_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_user_code",
    subTitle: "修改人编码",
    dataIndex: "modify_user_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_user_name",
    subTitle: "修改人名称",
    dataIndex: "modify_user_name",
    width: 160,
    align: "center",
  },
];
