import React from 'react';


export const configColumns = [
  {
    title: 'material.form_no',
    subTitle: '单据号',
    dataIndex: 'form_no',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.form_no_show',
    subTitle: '单据号',
    dataIndex: 'form_no_show',
    width: 320,
    align: 'center',
  },
  {
    title: 'material.form_date',
    subTitle: '单据日期',
    dataIndex: 'form_date',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.form_date',
    subTitle: '单据日期',
    dataIndex: 'form_date_format',
    width: 160,
    align: 'center',
  },
  {
    title: "material.material_type",
    subTitle: "材质类别",
    dataIndex: "material_type",
    width: 160,
    align: "center",
  },{
    title: "material.material",
    subTitle: "材质",
    dataIndex: "material",
    width: 160,
    align: "center",
  },
  {
    title: 'material.dev_code',
    subTitle: '装置编码',
    dataIndex: 'dev_code',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.unit_project_code',
    subTitle: '单位工程编码',
    dataIndex: 'unit_project_code',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.unit_code',
    subTitle: '单元编码',
    dataIndex: 'unit_code',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.obs_code',
    subTitle: '分包队伍编码',
    dataIndex: 'obs_code',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.obs_name',
    subTitle: '分包队伍名称',
    dataIndex: 'obs_name',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.status',
    subTitle: '审批状态',
    dataIndex: 'status',
    width: 160,
    align: 'center'
  },
  {
    title: 'material.status',
    subTitle: '审批状态', //  0-未发起审批 1-审批中 2-审批完成 -1-驳回
    dataIndex: 'status_str',
    width: 160,
    align: 'center'
  },
  {
    title: 'material.apprv_complete_ts',
    subTitle: '审批完成时间',
    dataIndex: 'apprv_complete_ts',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.apprv_complete_ts',
    subTitle: '审批完成时间',
    dataIndex: 'apprv_complete_ts_str',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.apprv_complete_tz',
    subTitle: '审核完成时区',
    dataIndex: 'apprv_complete_tz',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.instance_code',
    subTitle: '审批实例编码',
    dataIndex: 'instance_code',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.form_maker_code',
    subTitle: '制单人编码',
    dataIndex: 'form_maker_code',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.form_maker_name',
    subTitle: '制单人姓名',
    dataIndex: 'form_maker_name',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.form_make_time',
    subTitle: '制单时间',
    dataIndex: 'form_make_time',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.form_make_time',
    subTitle: '制单时间',
    dataIndex: 'form_make_time_format',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.form_make_tz',
    subTitle: '制单时区',
    dataIndex: 'form_make_tz',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.modify_code',
    subTitle: '修改人编码',
    dataIndex: 'modify_code',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.modify_name',
    subTitle: '修改人',
    dataIndex: 'modify_name',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.modify_time',
    subTitle: '修改时间',
    dataIndex: 'modify_time',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.modify_time',
    subTitle: '修改时间',
    dataIndex: 'modify_time_format',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.modify_tz',
    subTitle: '修改时区',
    dataIndex: 'modify_tz',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.remark',
    subTitle: '备注',
    dataIndex: 'remark',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.dev_name',
    subTitle: '装置编码',
    dataIndex: 'dev_name',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.unit_project_name',
    subTitle: '单位工程名称',
    dataIndex: 'unit_project_name',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.unit_name',
    subTitle: '单位名称',
    dataIndex: 'unit_name',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.prod_key',
    subTitle: '物料序号',
    dataIndex: 'prod_key',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.prod_code',
    subTitle: '物料编码',
    dataIndex: 'prod_code',
    width: 230,
    align: 'center',
  },
  {
    title: 'material.anti_rank',
    subTitle: '防腐等级',
    dataIndex: 'anti_rank',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.split_num',
    subTitle: '分割数量',
    dataIndex: 'split_num',
    width: 160,
    align: 'center',
  },
  //
  {
    title: 'material.allow_split_more',
    subTitle: '允许分割超计划比例(%)',
    dataIndex: 'allow_split_more',
    width: 160,
    align: 'center',
    render: (text: any) => {
      return `${text}%`;
    },
  },
  {
    title: 'material.pipe_code',
    subTitle: '管线号',
    dataIndex: 'pipe_code',
    width: 320,
    align: 'center',
  },
  {
    title: 'material.pipe_image_no',
    subTitle: '管道图号',
    dataIndex: 'pipe_image_no',
    width: 320,
    align: 'center',
  },
  {
    title: 'material.pipe_section_code',
    subTitle: '管段号',
    dataIndex: 'pipe_section_code',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.prod_memo',
    subTitle: '备注',
    dataIndex: 'prod_memo',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.prod_name',
    subTitle: '物料名称',
    dataIndex: 'prod_name',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.prod_describe',
    subTitle: '物料描述',
    dataIndex: 'prod_describe',
    width: 560,
    align: 'center',
  },
  {
    title: 'material.unit',
    subTitle: '单元',
    dataIndex: 'unit',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.spec',
    subTitle: '规格',
    dataIndex: 'spec',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.cls_code',
    subTitle: '分类编码',
    dataIndex: 'cls_code',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.cls_name',
    subTitle: '分类名称',
    dataIndex: 'cls_name',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.plan_num',
    subTitle: '计划数量',
    dataIndex: 'plan_num',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.rest_plan_num',
    subTitle: '剩余计划数量',
    dataIndex: 'rest_plan_num',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.total_plan_num',
    subTitle: '计划总量',
    dataIndex: 'total_plan_num',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.total_split_num',
    subTitle: '已分割总量',
    dataIndex: 'total_split_num',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.out_storage_num',
    subTitle: '已出库量',
    dataIndex: 'out_storage_num',
    width: 160,
    align: 'center',
  },
  {
    title: "material.rest_num",
    subTitle: "剩余数量",
    dataIndex: "rest_num",
    width: 160,
    align: "center",
  },

  {
    title: 'material.split_num_version1',
    subTitle: '版本1分割预算数量',
    dataIndex: 'split_num_version1',
    width: 260,
    align: 'center',
  },

  {
    title: 'material.split_num_version2',
    subTitle: '版本2分割预算数量',
    dataIndex: 'split_num_version2',
    width: 260,
    align: 'center',
  },

  {
    title: '分割图纸净量',
    subTitle: '分割图纸净量',
    dataIndex: 'split_net_num',
    width: 160,
    align: 'center',
  },
  {
    title: '分割图纸裕量',
    subTitle: '分割图纸裕量',
    dataIndex: 'split_margin_num',
    width: 160,
    align: 'center',
  },
  {
    title: '供货类型',
    subTitle: '供货类型',
    dataIndex: 'supply_type',
    width: 180,
    align: 'center',
  },
  {
    title: '物料类型',
    subTitle: '物料类型',
    dataIndex: 'plan_materials_type',
    width: 180,
    align: 'center',
  },
   {
    title: '供货类型',
    subTitle: '供货类型',
    dataIndex: 'supply_type_str',
    width: 180,
    align: 'center',
  },
  {
    title: '物料类型',
    subTitle: '物料类型',
    dataIndex: 'plan_materials_type_str',
    width: 180,
    align: 'center',
  },
  {
    title: '仓库编码',
    subTitle: "仓库编码",
    dataIndex: "warehouse_code",
    width: 160,
    align: 'center',
  },
  {
    title: '仓库名称',
    subTitle: "仓库名称",
    dataIndex: "warehouse_name",
    width: 160,
    align: 'center',
  },
  {
    title: '仓库编码',
    subTitle: "仓库编码",
    dataIndex: "warehouse_code_str",
    width: 160,
    align: 'center',
  },
  {
    title: '仓库名称',
    subTitle: "仓库名称",
    dataIndex: "warehouse_name_str",
    width: 160,
    align: 'center',
  },
];
