export const errColumns = [
  {
    title: 'material.prod_code',
    subTitle: '物料编码',
    dataIndex: 'prod_code',
    width: 230,
    align: 'center',
  },
  {
    title: 'material.pipe_code',
    subTitle: '管线号',
    dataIndex: 'pipe_code',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.pipe_image_no',
    subTitle: '管线图号',
    dataIndex: 'pipe_image_no',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.pipe_section_code',
    subTitle: '管段号',
    dataIndex: 'pipe_section_code',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.plan_num',
    subTitle: '计划数量',
    dataIndex: 'plan_num',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.after.import.split_num',
    subTitle: '导入后的分割数量',
    dataIndex: 'split_num',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.allow_split_more',
    subTitle: '允许分割超计划的比例(%)',
    dataIndex: 'allow_split_more',
    width: 160,
    align: 'center',
  }, {
    title: 'material.allow_split_num',
    subTitle: '允许分割数量',
    dataIndex: 'allow_split_num',
    width: 160,
    align: 'center',
  },
  {
    title: 'material.rest.split_num',
    subTitle: '导入后未分割量',
    dataIndex: 'rest_split_num',
    width: 160,
    align: 'center',
  }, {
    title: 'material.sub_split_num',
    subTitle: '系统扣除量',
    dataIndex: 'sub_split_num',
    width: 160,
    align: 'center',
  },
];
