export const configColumns = [
  {
    title: "compinfo.dep_code",
    subTitle: "depcode",
    dataIndex: "dep_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.dep_name",
    subTitle: "depname",
    dataIndex: "dep_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_code",
    subTitle: "制单人编码",
    dataIndex: "form_maker_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_name",
    subTitle: "制单人名称",
    dataIndex: "form_maker_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_time",
    subTitle: "制单时间",
    dataIndex: "form_make_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_tz",
    subTitle: "制单时区",
    dataIndex: "form_make_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_no",
    subTitle: "单据号",
    dataIndex: "form_no",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_code_id",
    subTitle: "配置id",
    dataIndex: "type_code_id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_code_name",
    subTitle: "配置名称",
    dataIndex: "type_code_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.rt_shots",
    subTitle: "RT张拍片",
    dataIndex: "rt_shots",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.rt_pass",
    subTitle: "RT张合格",
    dataIndex: "rt_pass",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.ut_meters",
    subTitle: "UT米检测",
    dataIndex: "ut_meters",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.ut_pass",
    subTitle: "UT米合格",
    dataIndex: "ut_pass",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.pt_mt_tests",
    subTitle: "PT和MT检测",
    dataIndex: "pt_mt_tests",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.pt_mt_pass",
    subTitle: "PT和MT合格",
    dataIndex: "pt_mt_pass",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.tofd_meters",
    subTitle: "TOFD米检测",
    dataIndex: "tofd_meters",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.tofd_pass",
    subTitle: "TOFD米检测合格",
    dataIndex: "tofd_pass",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.rt_ratio",
    subTitle: "RT张合格率",
    dataIndex: "rt_ratio",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.ut_ratio",
    subTitle: "UT米合格率",
    dataIndex: "ut_ratio",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.pt_ratio",
    subTitle: "PT米合格率",
    dataIndex: "pt_ratio",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.tofd_ratio",
    subTitle: "TofD米合格率",
    dataIndex: "tofd_ratio",
    width: 160,
    align: "center",
  },
];
