export const configColumns = [
  {
    title: "compinfo.id",
    subTitle: "主键ID",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.nextMonthPlan",
    subTitle: "工作安排及建议",
    dataIndex: "next_month_plan",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.work_advice",
    subTitle: "质量管理工作意见、建议",
    dataIndex: "work_advice",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.coordination_issues",
    subTitle: "需总部协调解决的问题",
    dataIndex: "coordination_issues",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.dep_code",
    subTitle: "dep_code",
    dataIndex: "dep_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_code",
    subTitle: "制单人编码",
    dataIndex: "form_maker_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_name",
    subTitle: "制单人名称",
    dataIndex: "form_maker_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_time",
    subTitle: "制单时间",
    dataIndex: "form_make_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_time",
    subTitle: "制单时间",
    dataIndex: "form_make_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_tz",
    subTitle: "制单时区",
    dataIndex: "form_make_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.file_url",
    subTitle: "附件",
    dataIndex: "file_url",
    width: 160,
    align: "center",
  },
];
