export const configColumns = [
  {
    title: "InspectorSeniorityApply.sub_comp_code",
    subTitle: "分公司",
    dataIndex: "sub_comp_name",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.dep_code",
    subTitle: "项目部",
    dataIndex: "dep_name",
    width: 160,
    align: "center",
  },

  {
    title: "monitoringMeasuring.year",
    subTitle: "年份",
    dataIndex: "year",
    width: 160,
    align: "center",
  },
  {
    title: "monitoringMeasuring.month",
    subTitle: "月份",
    dataIndex: "month",
    width: 160,
    align: "center",
  },
  {
    title: "monitoringMeasuring.name",
    subTitle: "名称",
    dataIndex: "name",
    width: 150,
    align: 'center',
  },
  {
    title: "monitoringMeasuring.spec_model",
    subTitle: "规格型号",
    dataIndex: "spec_model",
    width: 160,
    align: 'center',
  },
  {
    title: "monitoringMeasuring.factory_no",
    subTitle: "出厂编号",
    dataIndex: "factory_no",
    width: 160,
    align: "center",
  },
  {
    title: "monitoringMeasuring.manufacturer",
    subTitle: "生产厂",
    dataIndex: "manufacturer",
    width: 150,
    align: 'center',
  },
  {
    title: "monitoringMeasuring.accuracy_grade",
    subTitle: "准确度等级",
    dataIndex: "accuracy_grade",
    width: 160,
    align: "center",
  },
  {
    title: "monitoringMeasuring.measurement_range",
    subTitle: "测量范围",
    dataIndex: "measurement_range",
    width: 120,
    align: 'center',
  },
  {
    title: "monitoringMeasuring.is_disposable",
    subTitle: "是否一次性",
    dataIndex: "is_disposable",
    width: 160,
    align: "center",
  },
  {
    title: "monitoringMeasuring.verification_cycle",
    subTitle: "检定周期（月）",
    dataIndex: "verification_cycle",
    width: 160,
    align: "center",
  },
  {
    title: "monitoringMeasuring.verification_date",
    subTitle: "检定日期",
    dataIndex: "verification_date",
    width: 160,
    align: "center",
  },
  {
    title: "monitoringMeasuring.valid_date",
    subTitle: "有效日期",
    dataIndex: "valid_date",
    width: 160,
    align: "center",
  },
  {
    title: "monitoringMeasuring.verification_result",
    subTitle: "检定结果",
    dataIndex: "verification_result",
    width: 160,
    align: "center",
  },
  {
    title: "monitoringMeasuring.verification_unit",
    subTitle: "检定单位",
    dataIndex: "verification_unit",
    width: 150,
    align: 'center',
  },
  {
    title: "monitoringMeasuring.use_unit",
    subTitle: "使用单位",
    dataIndex: "use_unit",
    width: 150,
    align: 'center',
  },
  {
    title: "monitoringMeasuring.keeper",
    subTitle: "保管人姓名",
    dataIndex: "keeper",
    width: 160,
    align: "center",
  },
  {
    title: "monitoringMeasuring.professional_class",
    subTitle: "专业分类",
    dataIndex: "professional_class",
    width: 160,
    align: "center",
  },
  {
    title: "monitoringMeasuring.category",
    subTitle: "类别",
    dataIndex: "category",
    width: 160,
    align: "center",
  },
  {
    title: "monitoringMeasuring.status",
    subTitle: "状态",
    dataIndex: "status",
    width: 160,
    align: "center",
  },
  {
    title: "monitoringMeasuring.transfer_to",
    subTitle: "转移至何处",
    dataIndex: "transfer_to",
    width: 150,
    align: 'center',
  },
  {
    title: "monitoringMeasuring.affiliated_unit",
    subTitle: "所属单位",
    dataIndex: "affiliated_unit",
    width: 160,
    align: "center",
  },
  {
    title: "monitoringMeasuring.safety_protection",
    subTitle: "安全防护",
    dataIndex: "safety_protection",
    width: 160,
    align: "center",
  },

  {
    title: "wrokLicenseRegister.remark",
    subTitle: "备注",
    dataIndex: "remark",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_ts_str",
    subTitle: "创建时间",
    dataIndex: "create_ts_format",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_ts_str",
    subTitle: "创建时间",
    dataIndex: "create_ts_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_user_name",
    subTitle: "创建人名称",
    dataIndex: "create_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_ts_str",
    subTitle: "修改时间",
    dataIndex: "modify_ts_format",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_ts_str",
    subTitle: "修改时间",
    dataIndex: "modify_ts_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_user_name",
    subTitle: "修改人名称",
    dataIndex: "modify_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "levelConstructor.url",
    subTitle: "附件",
    dataIndex: "url",
    width: 160,
    align: "center",
  },
  {
    title: "common.status",
    subTitle: "审批状态",
    dataIndex: "approval_status",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_code",
    subTitle: "制单人编码",
    dataIndex: "form_maker_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_name",
    subTitle: "制单人名称",
    dataIndex: "form_maker_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_time",
    subTitle: "制单时间",
    dataIndex: "form_make_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_time",
    subTitle: "制单时间",
    dataIndex: "form_make_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_tz",
    subTitle: "制单时区",
    dataIndex: "form_make_tz",
    width: 160,
    align: "center",
  },
];