export const configColumns = [
  {
    title: "compinfo.id",
    subTitle: "主键",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.supplier_name",
    subTitle: "供应商名称",
    dataIndex: "supplier_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.supplier_code",
    subTitle: "供应商编码",
    dataIndex: "supplier_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.supplier_status",
    subTitle: "供应商状态",//如在用/停用/待审核
    dataIndex: "supplier_status",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.supplier_level",
    subTitle: "供应商等级",
    dataIndex: "supplier_level",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.collaboration_status",
    subTitle: "供应商协同功能",//如支持/不支持
    dataIndex: "collaboration_status",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.bank_account",
    subTitle: "银行账号",
    dataIndex: "bank_account",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.address",
    subTitle: "地址",
    dataIndex: "address",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.product_access",
    subTitle: "产品准入信息",
    dataIndex: "product_access",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contact_person",
    subTitle: "联系人",
    dataIndex: "contact_person",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contact_phone",
    subTitle: "联系方式",
    dataIndex: "contact_phone",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.supply_content",
    subTitle: "供货内容",
    dataIndex: "supply_content",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.dep_code",
    subTitle: "depcode",
    dataIndex: "dep_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark",
    subTitle: "备注",
    dataIndex: "remark",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_code",
    subTitle: "制单人编码",
    dataIndex: "form_maker_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_name",
    subTitle: "制单人名称",
    dataIndex: "form_maker_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_time",
    subTitle: "制单时间",
    dataIndex: "form_make_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_tz",
    subTitle: "制单时区",
    dataIndex: "form_make_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.RowNumber",
    subTitle: "序号",
    dataIndex: "RowNumber",
    width: 160,
    align: "center",
  },
];
