export const configColumns = [
  {
    title: "compinfo.id",
    subTitle: "主键ID",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.check_time",
    subTitle: "检查时间",
    dataIndex: "check_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.check_time",
    subTitle: "检查时间",
    dataIndex: "check_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.check_unit",
    subTitle: "检查单位",
    dataIndex: "check_unit",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.main_problems",
    subTitle: "检查出的主要问题",
    dataIndex: "main_problems",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.rectification",
    subTitle: "目前整改情况",
    dataIndex: "rectification",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.dep_code",
    subTitle: "depcode",
    dataIndex: "dep_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_code",
    subTitle: "制单人编码",
    dataIndex: "form_maker_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_name",
    subTitle: "制单人名称",
    dataIndex: "form_maker_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_time",
    subTitle: "制单时间",
    dataIndex: "form_make_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_time",
    subTitle: "制单时间",
    dataIndex: "form_make_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_tz",
    subTitle: "制单时区",
    dataIndex: "form_make_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_name",
    subTitle: "工程名称",
    dataIndex: "project_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_name",
    subTitle: "工程名称",
    dataIndex: "project_code",
    width: 160,
    align: "center",
  },
];
