export const configColumns = [
  {
    title: "compinfo.form_no",
    subTitle: "主键ID",
    dataIndex: "form_no",
    width: 160,
    align: "center",
  },
  {
    title: "单位",
    subTitle: "单位",
    dataIndex: "dep_code",
    width: 160,
    align: "center",
  },
  {
    title: "单位",
    subTitle: "单位",
    dataIndex: "dep_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_code",
    subTitle: "制单人编码",
    dataIndex: "form_maker_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_name",
    subTitle: "制单人名称",
    dataIndex: "form_maker_name",
    width: 160,
    align: "center",
  },
  {
    title: "日期",
    subTitle: "日期",
    dataIndex: "form_make_time",
    width: 160,
    align: "center",
  },
  {
    title: "日期",
    subTitle: "日期",
    dataIndex: "form_make_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_tz",
    subTitle: "制单时区",
    dataIndex: "form_make_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.id",
    subTitle: "主键ID",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_no",
    subTitle: "HSE重大风险及控制措施清单id",
    dataIndex: "form_no",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.out_info_id",
    subTitle: "分包合同id",
    dataIndex: "out_info_id",
    width: 160,
    align: "center",
  },
  {
    title: "工程名称",
    subTitle: "工程名称",
    dataIndex: "contract_out_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.level1_flow",
    subTitle: "一级流程/作业专业/作业区域",
    dataIndex: "level1_flow",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.level2_flow",
    subTitle: "二级流程/专业内容/作业活动",
    dataIndex: "level2_flow",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.level3_flow",
    subTitle: "三级流程/工作步骤",
    dataIndex: "level3_flow",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_code",
    subTitle: "分类(0:HSE重大风险及控制措施清单 ,1:重要环境因素及控制措施清单)",
    dataIndex: "type_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.detail_position",
    subTitle: "具体部位（区域、编号、相关参数等）",
    dataIndex: "detail_position",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.equipment_tool",
    subTitle: "设备/工具",
    dataIndex: "equipment_tool",
    width: 160,
    align: "center",
  },
  {
    title: "环境因素类别",
    subTitle: "环境因素类别",
    dataIndex: "hazard_category",
    width: 160,
    align: "center",
  },
  {
    title: "环境影响",
    subTitle: "环境影响",
    dataIndex: "main_consequence",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.control_measures",
    subTitle: "控制措施",
    dataIndex: "control_measures",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.responsible_person",
    subTitle: "责任人",
    dataIndex: "responsible_person",
    width: 160,
    align: "center",
  },
  {
    title: "责任单位",
    subTitle: "责任单位",
    dataIndex: "responsible_unit",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.plan_implement_time",
    subTitle: "计划实施时间",
    dataIndex: "plan_implement_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.plan_implement_time",
    subTitle: "计划实施时间",
    dataIndex: "plan_implement_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark",
    subTitle: "备注",
    dataIndex: "remark",
    width: 160,
    align: "center",
  },
];
