export const configColumns = [
  {
    title: "compinfo.id",
    subTitle: "主键 ID",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.dep_code",
    subTitle: "项目部",
    dataIndex: "dep_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.dep_name",
    subTitle: "项目部",
    dataIndex: "dep_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.meeting_type",
    subTitle: "上会类型 1-TC 2 - 执行董事",
    dataIndex: "meeting_type",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.meeting_type",
    subTitle: "上会类型 1-TC 2 - 执行董事",
    dataIndex: "meeting_type_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.meeting_item",
    subTitle: "审议事项",
    dataIndex: "meeting_item",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.start_price",
    subTitle: "起始金额标准（万元）",
    dataIndex: "start_price",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.end_price",
    subTitle: "截至金额标准（万元）",
    dataIndex: "end_price",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark",
    subTitle: "备注",
    dataIndex: "remark",
    width: 160,
    align: "center",
  },
];
