export const configColumns = [
  {
    title: "InspectorSeniorityApply.sub_comp_code",
    subTitle: "分公司",
    dataIndex: "sub_comp_name",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.dep_code",
    subTitle: "项目部",
    dataIndex: "dep_name",
    width: 160,
    align: "center",
  },

  {
    title: "monitoringMeasuring.year",
    subTitle: "年份",
    dataIndex: "year",
    width: 160,
    align: "center",
  },
  {
    title: "monitoringMeasuring.month",
    subTitle: "月份",
    dataIndex: "month",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contract_no",
    subTitle: "合同编号",
    dataIndex: "contract_no",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.visit_date",
    subTitle: "回访时间",
    dataIndex: "visit_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.visit_unit",
    subTitle: "回访单位",
    dataIndex: "visit_unit",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.visit_person",
    subTitle: "回访人",
    dataIndex: "visit_person",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.responsible_person",
    subTitle: "责任人",
    dataIndex: "responsible_person",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.year_stage",
    subTitle: "阶段",
    dataIndex: "year_stage",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.year_stage",
    subTitle: "阶段",
    dataIndex: "year_stage_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.team_code",
    subTitle: "工程队编号",
    dataIndex: "team_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.welder_name",
    subTitle: "焊工姓名",
    dataIndex: "welder_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.employment_type",
    subTitle: "用工形式",
    dataIndex: "employment_type",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.employee_code",
    subTitle: "员工编号",
    dataIndex: "employee_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_name",
    subTitle: "工程名称",
    dataIndex: "project_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.certificate_no",
    subTitle: "证件编号",
    dataIndex: "certificate_no",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.equipment_type",
    subTitle: "特种设备类别",
    dataIndex: "equipment_type",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.equipment_type",
    subTitle: "特种设备类别",
    dataIndex: "equipment_type_str",
    width: 160,
    align: "center",
  },
  
  {
    title: "compinfo.welding_method_code",
    subTitle: "焊接方法代号",
    dataIndex: "welding_method_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.welding_method_code",
    subTitle: "焊接方法代号",
    dataIndex: "welding_method_code_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.welding_quantity",
    subTitle: "焊接数量",
    dataIndex: "welding_quantity",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.unit",
    subTitle: "单位（吋/米）",
    dataIndex: "unit",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.ndt_num",
    subTitle: "无损检测底片数量",
    dataIndex: "ndt_num",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.qualified_num",
    subTitle: "合格底片数量",
    dataIndex: "qualified_num",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.pass_percent",
    subTitle: "焊接一次合格率（%）",
    dataIndex: "pass_percent",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.repair_num",
    subTitle: "返修焊口底片数量",
    dataIndex: "repair_num",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.material_category",
    subTitle: "材质类别",
    dataIndex: "material_category",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.material_category",
    subTitle: "材质类别",
    dataIndex: "material_category_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.quality_accident",
    subTitle: "质量事故",
    dataIndex: "quality_accident",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.quality_accident",
    subTitle: "质量事故",
    dataIndex: "quality_accident_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.remark",
    subTitle: "备注",
    dataIndex: "remark",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_ts_str",
    subTitle: "创建时间",
    dataIndex: "create_ts_format",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_ts_str",
    subTitle: "创建时间",
    dataIndex: "create_ts_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_user_name",
    subTitle: "创建人名称",
    dataIndex: "create_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_ts_str",
    subTitle: "修改时间",
    dataIndex: "modify_ts_format",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_ts_str",
    subTitle: "修改时间",
    dataIndex: "modify_ts_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_user_name",
    subTitle: "修改人名称",
    dataIndex: "modify_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "levelConstructor.url",
    subTitle: "附件",
    dataIndex: "url",
    width: 160,
    align: "center",
  },
  {
    title: "common.status",
    subTitle: "审批状态",
    dataIndex: "approval_status",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_code",
    subTitle: "制单人编码",
    dataIndex: "form_maker_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_name",
    subTitle: "制单人名称",
    dataIndex: "form_maker_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_time",
    subTitle: "制单时间",
    dataIndex: "form_make_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_time",
    subTitle: "制单时间",
    dataIndex: "form_make_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_tz",
    subTitle: "制单时区",
    dataIndex: "form_make_tz",
    width: 160,
    align: "center",
  },
];