export const configColumns = [
  {
    title: "月份",
    subTitle: "month",
    dataIndex: "month",
    width: 160,
    align: "center",
  },
  {
    title: "项目部名称",
    subTitle: "项目部名称",
    dataIndex: "dep_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num1",
    subTitle: "本月数量",
    dataIndex: "type_num1",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num2",
    subTitle: "本月数量",
    dataIndex: "type_num2",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num3",
    subTitle: "本月数量",
    dataIndex: "type_num3",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num4",
    subTitle: "本月数量",
    dataIndex: "type_num4",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num5",
    subTitle: "本月数量",
    dataIndex: "type_num5",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num6",
    subTitle: "本月数量",
    dataIndex: "type_num6",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num7",
    subTitle: "本月数量",
    dataIndex: "type_num7",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num8",
    subTitle: "本月数量",
    dataIndex: "type_num8",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num9",
    subTitle: "本月数量",
    dataIndex: "type_num9",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num10",
    subTitle: "本月数量",
    dataIndex: "type_num10",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num11",
    subTitle: "本月数量",
    dataIndex: "type_num11",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num12",
    subTitle: "本月数量",
    dataIndex: "type_num12",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num13",
    subTitle: "本月数量",
    dataIndex: "type_num13",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num14",
    subTitle: "本月数量",
    dataIndex: "type_num14",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num15",
    subTitle: "本月数量",
    dataIndex: "type_num15",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num16",
    subTitle: "本月数量",
    dataIndex: "type_num16",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num17",
    subTitle: "本月数量",
    dataIndex: "type_num17",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num18",
    subTitle: "本月数量",
    dataIndex: "type_num18",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num19",
    subTitle: "本月数量",
    dataIndex: "type_num19",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num20",
    subTitle: "本月数量",
    dataIndex: "type_num20",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num21",
    subTitle: "本月数量",
    dataIndex: "type_num21",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num22",
    subTitle: "本月数量",
    dataIndex: "type_num22",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num23",
    subTitle: "本月数量",
    dataIndex: "type_num23",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num24",
    subTitle: "本月数量",
    dataIndex: "type_num24",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num25",
    subTitle: "本月数量",
    dataIndex: "type_num25",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num26",
    subTitle: "本月数量",
    dataIndex: "type_num26",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num27",
    subTitle: "本月数量",
    dataIndex: "type_num27",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num28",
    subTitle: "本月数量",
    dataIndex: "type_num28",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num29",
    subTitle: "本月数量",
    dataIndex: "type_num29",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num30",
    subTitle: "本月数量",
    dataIndex: "type_num30",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num31",
    subTitle: "本月数量",
    dataIndex: "type_num31",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num32",
    subTitle: "本月数量",
    dataIndex: "type_num32",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num33",
    subTitle: "本月数量",
    dataIndex: "type_num33",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num34",
    subTitle: "本月数量",
    dataIndex: "type_num34",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num35",
    subTitle: "本月数量",
    dataIndex: "type_num35",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num36",
    subTitle: "本月数量",
    dataIndex: "type_num36",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num37",
    subTitle: "本月数量",
    dataIndex: "type_num37",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num38",
    subTitle: "本月数量",
    dataIndex: "type_num38",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num39",
    subTitle: "本月数量",
    dataIndex: "type_num39",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_num40",
    subTitle: "本月数量",
    dataIndex: "type_num40",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark1",
    subTitle: "备注",
    dataIndex: "remark1",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark2",
    subTitle: "备注",
    dataIndex: "remark2",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark3",
    subTitle: "备注",
    dataIndex: "remark3",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark4",
    subTitle: "备注",
    dataIndex: "remark4",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark5",
    subTitle: "备注",
    dataIndex: "remark5",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark6",
    subTitle: "备注",
    dataIndex: "remark6",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark7",
    subTitle: "备注",
    dataIndex: "remark7",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark8",
    subTitle: "备注",
    dataIndex: "remark8",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark9",
    subTitle: "备注",
    dataIndex: "remark9",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark10",
    subTitle: "备注",
    dataIndex: "remark10",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark11",
    subTitle: "备注",
    dataIndex: "remark11",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark12",
    subTitle: "备注",
    dataIndex: "remark12",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark13",
    subTitle: "备注",
    dataIndex: "remark13",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark14",
    subTitle: "备注",
    dataIndex: "remark14",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark15",
    subTitle: "备注",
    dataIndex: "remark15",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark16",
    subTitle: "备注",
    dataIndex: "remark16",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark17",
    subTitle: "备注",
    dataIndex: "remark17",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark18",
    subTitle: "备注",
    dataIndex: "remark18",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark19",
    subTitle: "备注",
    dataIndex: "remark19",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark20",
    subTitle: "备注",
    dataIndex: "remark20",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark21",
    subTitle: "备注",
    dataIndex: "remark21",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark22",
    subTitle: "备注",
    dataIndex: "remark22",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark23",
    subTitle: "备注",
    dataIndex: "remark23",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark24",
    subTitle: "备注",
    dataIndex: "remark24",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark25",
    subTitle: "备注",
    dataIndex: "remark25",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark26",
    subTitle: "备注",
    dataIndex: "remark26",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark27",
    subTitle: "备注",
    dataIndex: "remark27",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark28",
    subTitle: "备注",
    dataIndex: "remark28",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark29",
    subTitle: "备注",
    dataIndex: "remark29",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark30",
    subTitle: "备注",
    dataIndex: "remark30",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark31",
    subTitle: "备注",
    dataIndex: "remark31",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark32",
    subTitle: "备注",
    dataIndex: "remark32",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark33",
    subTitle: "备注",
    dataIndex: "remark33",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark34",
    subTitle: "备注",
    dataIndex: "remark34",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark35",
    subTitle: "备注",
    dataIndex: "remark35",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark36",
    subTitle: "备注",
    dataIndex: "remark36",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark37",
    subTitle: "备注",
    dataIndex: "remark37",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark38",
    subTitle: "备注",
    dataIndex: "remark38",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark39",
    subTitle: "备注",
    dataIndex: "remark39",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark40",
    subTitle: "备注",
    dataIndex: "remark40",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.dep_code",
    subTitle: "depcode",
    dataIndex: "dep_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_code",
    subTitle: "制单人编码",
    dataIndex: "form_maker_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_name",
    subTitle: "制单人名称",
    dataIndex: "form_maker_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_time",
    subTitle: "制单时间",
    dataIndex: "form_make_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_time",
    subTitle: "制单时间",
    dataIndex: "form_make_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_tz",
    subTitle: "制单时区",
    dataIndex: "form_make_tz",
    width: 160,
    align: "center",
  },
];
