export const columns = [
  {
    title: '序号',
    dataIndex: 'equipment_index',
    align: 'center',
    width: 100,
  },
  {
    title: '设备名称',
    dataIndex: 'equipment_name',
    align: 'center',
    width: 120,
  },
  {
    title: "自有/台(套)",
    subTitle: "自有/台(套)",
    dataIndex: "own_equipment_count",
    width: 100,
    align: "center",
    valueType: 'number',
  },
  {
    title: "租赁/台(套)",
    subTitle: "租赁/台(套)",
    dataIndex: "leasing_equipment_count",
    width: 100,
    align: "center",
    valueType: 'number',
  },
  {
    title: "租赁公司",
    subTitle: "租赁公司",
    dataIndex: "leasing_company",
    width: 160,
    align: "center",
    valueType: 'input',
  },
  {
    title: "共享/台(套)",
    subTitle: "共享/台(套)",
    dataIndex: "shared_equipment_count",
    width: 100,
    align: "center",
    valueType: 'number',
  },
  {
    title: "共享单位",
    subTitle: "共享单位",
    dataIndex: "shared_company",
    width: 160,
    align: "center",
    valueType: 'input',
  },
  {
    title: "备注",
    subTitle: "备注",
    dataIndex: "remark",
    width: 160,
    align: "center",
    valueType: 'input',
  },
]
