import { getUrlCrypto } from "@/components/HuaWeiOBSUploadSingleFile";

export const configColumns = [
  {
    title: "InspectorSeniorityApply.sub_comp_code",
    subTitle: "分公司",
    dataIndex: "sub_comp_name",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.dep_code",
    subTitle: "项目部",
    dataIndex: "dep_name",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.name",
    subTitle: "姓名",
    dataIndex: "name",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.gender",
    subTitle: "性别",
    dataIndex: "gender",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.birth_date",
    subTitle: "出生日期",
    dataIndex: "birth_date",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.job",
    subTitle: "职务",
    dataIndex: "job",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.job_title",
    subTitle: "职称",
    dataIndex: "job_title",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.work_date",
    subTitle: "参加工作时间",
    dataIndex: "work_date",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.education",
    subTitle: "文化程度",
    dataIndex: "education",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.employee_no",
    subTitle: "员工编号",
    dataIndex: "employee_no",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.graduation_school",
    subTitle: "毕业院校",
    dataIndex: "graduation_school",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.major",
    subTitle: "所学专业",
    dataIndex: "major",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.department",
    subTitle: "所在单位部门",
    dataIndex: "department",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.post",
    subTitle: "现从事岗位",
    dataIndex: "post",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.train_date",
    subTitle: "培训时间",
    dataIndex: "train_date",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.train_grade",
    subTitle: "培训成绩",
    dataIndex: "train_grade",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.application_project",
    subTitle: "申请操作项目",
    dataIndex: "application_project",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.phone",
    subTitle: "联系电话",
    dataIndex: "phone",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.on_duty",
    subTitle: "在岗状态",
    dataIndex: "on_duty",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.related_work_date",
    subTitle: "从事质检或相关工作时间",
    dataIndex: "related_work_date",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.apply_major",
    subTitle: "申请检查专业",
    dataIndex: "apply_major",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.job_resume",
    subTitle: "工作简历",
    dataIndex: "job_resume",
    width: 210,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.approval_date",
    subTitle: "审批时间",
    dataIndex: "approval_date",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.remark",
    subTitle: "备注",
    dataIndex: "remark",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_ts_str",
    subTitle: "创建时间",
    dataIndex: "create_ts_format",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_ts_str",
    subTitle: "创建时间",
    dataIndex: "create_ts_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_user_name",
    subTitle: "创建人名称",
    dataIndex: "create_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_ts_str",
    subTitle: "修改时间",
    dataIndex: "modify_ts_format",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_ts_str",
    subTitle: "修改时间",
    dataIndex: "modify_ts_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_user_name",
    subTitle: "修改人名称",
    dataIndex: "modify_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "levelConstructor.url",
    subTitle: "附件",
    dataIndex: "url",
    width: 160,
    align: "center",
  },
  {
    title: "common.status",
    subTitle: "审批状态",
    dataIndex: "approval_status",
    width: 160,
    align: "center",
  },

  {
    title: "wrokLicenseRegister.lab_full_name",
    subTitle: "外委实验室的全称",
    dataIndex: "lab_full_name",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.lab_nature",
    subTitle: "外委实验室的性质",
    dataIndex: "lab_nature",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.qualifications",
    subTitle: "外委实验室的资质证名称及相应有效期",
    dataIndex: "qualifications",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.qualification_scope",
    subTitle: "资质范围",
    dataIndex: "qualification_scope",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.business_license_no",
    subTitle: "外委实验室营业执照号码",
    dataIndex: "business_license_no",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.lab_responsible_person",
    subTitle: "外委实验室负责人",
    dataIndex: "lab_responsible_person",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.province",
    subTitle: "所在省份",
    dataIndex: "province",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.province",
    subTitle: "所在省份",
    dataIndex: "province_name",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.city",
    subTitle: "所在地市",
    dataIndex: "city",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.city",
    subTitle: "所在地市",
    dataIndex: "city_name",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.address",
    subTitle: "详细地址",
    dataIndex: "address",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.lab_phone",
    subTitle: "外委实验室联系电话",
    dataIndex: "lab_phone",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.geo_traffic",
    subTitle: "地理位置、交通情况",
    dataIndex: "geo_traffic",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.entrusted_projects",
    subTitle: "拟委托实验项目",
    dataIndex: "entrusted_projects",
    width: 160,
    align: "center",
  },

];
/**
   * 工作简历表格列配置
   */
export const resumeColumns = [
  {
    title: '资质证名称',
    dataIndex: 'qualification',
    key: 'qualification',
    width: 210,
    render: (text: string) => text || '-',
  },
  {
    title: '有效期',
    dataIndex: 'qualification_date',
    key: 'qualification_date',
    width: 120,
    render: (text: string) => text || '-',
  },
  {
    title: '资质附件',
    dataIndex: 'qualification_url',
    key: 'qualification_url',
    width: 200,
    render: (text: string) => {
      return (
        <a
          onClick={() => window.open(getUrlCrypto(text))}
          type='link'
        >下载文件</a>
      )
    },
  }
];
