export const configColumns = [
    {
      title: "compinfo.id",
      subTitle: "主键ID",
      dataIndex: "id",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.id",
      subTitle: "主键ID",
      dataIndex: "contract_out_id",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.code",
      subTitle: "编码",
      dataIndex: "code",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.wbs_code",
      subTitle: "项目部",
      dataIndex: "wbs_code",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.report_date",
      subTitle: "填报日期",
      dataIndex: "report_date",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.report_date",
      subTitle: "填报日期",
      dataIndex: "report_date_str",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.branchCompCode",
      subTitle: "分公司",
      dataIndex: "branch_comp_code",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.branchCompCode",
      subTitle: "分公司",
      dataIndex: "branch_comp_name",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.depCode",
      subTitle: "项目经理部",
      dataIndex: "dep_code",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.depCode",
      subTitle: "项目经理部",
      dataIndex: "dep_name",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.contractor_name",
      subTitle: "承包商名称",
      dataIndex: "contractor_name",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.contractor_manager",
      subTitle: "承包商项目经理",
      dataIndex: "contractor_manager",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.contractor_manager",
      subTitle: "承包商项目经理",
      dataIndex: "contractor_manager_name",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.register_number",
      subTitle: "承包商编码",
      dataIndex: "register_number",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.contact_phone",
      subTitle: "联系电话",
      dataIndex: "contact_phone",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.contract_name",
      subTitle: "合同名称",
      dataIndex: "contract_name",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.contract_amount",
      subTitle: "合同总额（元）",
      dataIndex: "contract_amount",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.contract_start_date",
      subTitle: "合同起始日期",
      dataIndex: "contract_start_date",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.contract_end_date",
      subTitle: "合同结束日期",
      dataIndex: "contract_end_date",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.annual_completed_amount",
      subTitle: "当年完成合同额（元）",
      dataIndex: "annual_completed_amount",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.project_category",
      subTitle: "项目类别",
      dataIndex: "project_category",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.project_category",
      subTitle: "项目类别",
      dataIndex: "project_category_name",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.form_maker_code",
      subTitle: "制单人编码",
      dataIndex: "form_maker_code",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.form_maker_name",
      subTitle: "制单人名称",
      dataIndex: "form_maker_name",
      width: 160,
      align: "center",
    },

    {
      title: "compinfo.project_principal",
      subTitle: "项目部考核负责人",
      dataIndex: "project_principal",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.contract_out_score",
      subTitle: "分公司考核得分",
      dataIndex: "contract_out_score",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.contract_out_principal",
      subTitle: "分公司考核负责人",
      dataIndex: "contract_out_principal",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.contract_out_reason",
      subTitle: "分公司考核扣分原因",
      dataIndex: "contract_out_reason",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.monthly_person_count",
      subTitle: "本月人数",
      dataIndex: "monthly_person_count",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.monthly_output_value",
      subTitle: "本月完成产值 (万元)",
      dataIndex: "monthly_output_value",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.actual_start_date",
      subTitle: "实际开工日期",
      dataIndex: "actual_start_date",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.actual_end_date",
      subTitle: "实际完工日期",
      dataIndex: "actual_end_date",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.actual_start_date",
      subTitle: "实际开工日期",
      dataIndex: "actual_start_date_str",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.actual_end_date",
      subTitle: "实际完工日期",
      dataIndex: "actual_end_date_str",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.constructionRemark",
      subTitle: "施工进度描述",
      dataIndex: "remark",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.project_principal",
      subTitle: "项目负责人",
      dataIndex: "project_principal",
      width: 160,
      align: "center",
    },
    {
      title: "subletting_enroll_code",
      subTitle: "乙方单位名称",
      dataIndex: "subletting_enroll_code",
      width: 160,
      align: "center",
    },
    {
      title: "subletting_enroll_code",
      subTitle: "乙方单位名称",
      dataIndex: "subletting_enroll_name",
      width: 160,
      align: "center",
    },

    {
      title: "compinfo.belong_month",
      subTitle: "所属月份",
      dataIndex: "belong_month",
      width: 160,
      align: "center",
    },
    {
      title: "compinfo.cumulative_output_value",
      subTitle: "累计完成产值（万元）",
      dataIndex: "cumulative_output_value",
      width: 210,
      align: "center",
    },
    {
      title: "contract.pre_total_output_value",
      subTitle: "本月前累计产值",
      dataIndex: "pre_total_output_value",
      width: 160,
      align: "center",
    }
  ];
