// 格式化金额：千分位，保留两位小数
const formatAmount = (value: any): string => {
  if (value === null || value === undefined || value === '') {
    return '-';
  }
  const num = Number(value);
  if (isNaN(num)) {
    return '-';
  }
  return num.toLocaleString('zh-CN', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
};

export const configColumns = [
  {
    title: "compinfo.id",
    subTitle: "主键",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contract_income_id",
    subTitle: "合同收入表ID",
    dataIndex: "contract_income_id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.settlement_status",
    subTitle: "结算状态",
    dataIndex: "settlement_status",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.settlement_status",
    subTitle: "结算状态",
    dataIndex: "settlement_status_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.expected_settlement_amount",
    subTitle: "预计结算值",
    dataIndex: "expected_settlement_amount",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.progress_settlement_current_year",
    subTitle: "本年办理",
    dataIndex: "progress_settlement_current_year",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.progress_settlement_total",
    subTitle: "累计办理",
    dataIndex: "progress_settlement_total",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.received_cash",
    subTitle: "货币资金",
    dataIndex: "received_cash",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.received_bill",
    subTitle: "票据",
    dataIndex: "received_bill",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.received_material",
    subTitle: "材料款",
    dataIndex: "received_material",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.received_other",
    subTitle: "其它",
    dataIndex: "received_other",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.received_subtotal",
    subTitle: "累计收款情况小计",
    dataIndex: "received_subtotal",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.book_receivable_balance",
    subTitle: "账面应收款项余额",
    dataIndex: "book_receivable_balance",
    width: 180,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.advance_receipt_balance",
    subTitle: "预收款项余额",
    dataIndex: "advance_receipt_balance",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.net_receivable_amount",
    subTitle: "应收款项净额",
    dataIndex: "net_receivable_amount",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.net_receivable_recover_in_year",
    subTitle: "年内可回收",
    dataIndex: "net_receivable_recover_in_year",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.net_receivable_recover_after_year",
    subTitle: "年后可回收",
    dataIndex: "net_receivable_recover_after_year",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.net_receivable_bad_debt",
    subTitle: "已计提坏账及难以回收部分",
    dataIndex: "net_receivable_bad_debt",
    width: 240,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.expected_receivable_amount",
    subTitle: "预计应收款项",
    dataIndex: "expected_receivable_amount",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.total_invoice_count",
    subTitle: "累计开发票数",
    dataIndex: "total_invoice_count",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.collection_plan_reason",
    subTitle: "简述收款计划（年度内不能回收的原因）",
    dataIndex: "collection_plan_reason",
    width: 300,
    align: "center",
  },
  {
    title: "compinfo.responsible_person",
    subTitle: "责任人",
    dataIndex: "responsible_person",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.account_name",
    subTitle: "科目名称",
    dataIndex: "account_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.debtStatisticsWbsCode",
    subTitle: "自辅06-项目编码",
    dataIndex: "wbs_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.debtStatisticsContractName",
    subTitle: "工程名称",
    dataIndex: "contract_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.relative_person_code",
    subTitle: "客户编码",
    dataIndex: "relative_person_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.owner_unit_name",
    subTitle: "客户名称",
    dataIndex: "owner_unit_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.debtStatisticsContractSayPrice",
    subTitle: "合同额（含税）",
    dataIndex: "contract_say_price",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.contract_no",
    subTitle: "合同编码",
    dataIndex: "contract_no",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.profit_center_code",
    subTitle: "利润中心编码",
    dataIndex: "profit_center_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.counterparty_risk",
    subTitle: "往来单位风险情况（诉讼、经营异常、资金紧张等）",
    dataIndex: "counterparty_risk",
    width: 350,
    align: "center",
  },
  {
    title: "compinfo.create_ts",
    subTitle: "制单时间",
    dataIndex: "create_ts",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_ts",
    subTitle: "制单时间",
    dataIndex: "create_ts_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_tz",
    subTitle: "制单时区",
    dataIndex: "create_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_user_code",
    subTitle: "制单人编码",
    dataIndex: "create_user_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_user_name",
    subTitle: "制单人姓名",
    dataIndex: "create_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_ts",
    subTitle: "修改时间",
    dataIndex: "modify_ts",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_ts",
    subTitle: "修改时间",
    dataIndex: "modify_ts_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_tz",
    subTitle: "修改时区",
    dataIndex: "modify_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_user_code",
    subTitle: "修改人编码",
    dataIndex: "modify_user_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_user_name",
    subTitle: "修改人编码",
    dataIndex: "modify_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.dep_code",
    subTitle: "项目部编码",
    dataIndex: "dep_code",
    width: 160,
    align: "center",
  },
];
