
export const configColumns = [
  // 专项预案配置表
  {
    title: "emergencyplan.RowNumber",
    subTitle: "序号",
    dataIndex: "RowNumber",
    width: 160,
    align: "center",
  },
  {
    title: "emergencyplan.form_no",
    subTitle: "序号",
    dataIndex: "form_no",
    width: 160,
    align: "center",
  },
  {
    title: "emergencyplan.plan_name",
    subTitle: "专项应急预案名称",
    dataIndex: "plan_name",
    width: 200,
    align: "center",
  },
  {
    title: "emergencyplan.applicable_area",
    subTitle: "适用区域",
    dataIndex: "applicable_area",
    width: 160,
    align: "center",
  },
  {
    title: "emergencyplan.scene",
    subTitle: "场景",
    dataIndex: "scene",
    width: 160,
    align: "center",
  },
  {
    title: "emergencyplan.punishment_principle",
    subTitle: "处置原则",
    dataIndex: "punishment_principle",
    width: 160,
    align: "center",
  },
  {
    title: "emergencyplan.disposal_process",
    subTitle: "处置流程",
    dataIndex: "disposal_process",
    width: 160,
    align: "center",
  },
  {
    title: "emergencyplan.dep_code",
    subTitle: "项目部",
    dataIndex: "dep_code",
    width: 160,
    align: "center",
  },
  {
    title: "emergencyplan.form_maker_code",
    subTitle: "制单人编码",
    dataIndex: "form_maker_code",
    width: 160,
    align: "center",
  },
  {
    title: "emergencyplan.form_maker_name",
    subTitle: "制单人名称",
    dataIndex: "form_maker_name",
    width: 160,
    align: "center",
  },
  {
    title: "emergencyplan.form_make_time",
    subTitle: "制单时间",
    dataIndex: "form_make_time",
    width: 160,
    align: "center",
  },
  {
    title: "emergencyplan.form_make_time",
    subTitle: "制单时间",
    dataIndex: "form_make_time_str",
    width: 160,
    align: "center",
  },
  // 事件等级表
  {
    title: "emergencyplan.level_name",
    subTitle: "等级名称（蓝色预警、黄色预警）",
    dataIndex: "level_name",
    width: 160,
    align: "center",
  },
  {
    title: "emergencyplan.level_rgb",
    subTitle: "颜色",
    dataIndex: "level_rgb",
    width: 160,
    align: "center",
  },
  {
    title: "emergencyplan.level_code",
    subTitle: "级别",
    dataIndex: "level_code",
    width: 160,
    align: "center",
  },
  {
    title: "emergencyplan.description",
    subTitle: "事件分级",
    dataIndex: "description",
    width: 160,
    align: "center",
  },
  {
    title: "emergencyplan.message_source",
    subTitle: "信息来源",
    dataIndex: "message_source",
    width: 160,
    align: "center",
  },
  {
    title: "emergencyplan.verification_analysis",
    subTitle: "核实研判",
    dataIndex: "verification_analysis",
    width: 160,
    align: "center",
  },
  {
    title: "emergencyplan.push_level_and_scope",
    subTitle: "发布层级和范围",
    dataIndex: "push_level_and_scope",
    width: 160,
    align: "center",
  },
  {
    title: "emergencyplan.response_preparation",
    subTitle: "响应准备",
    dataIndex: "response_preparation",
    width: 160,
    align: "center",
  },
  {
    title: "emergencyplan.order_num",
    subTitle: "排序",
    dataIndex: "order_num",
    width: 160,
    align: "center",
  },
  {
    title: "emergencyplan.warning_release",
    subTitle: "预警解除",
    dataIndex: "warning_release",
    width: 160,
    align: "center",
  },
  {
    title: "emergencyplan.possible_accident",
    subTitle: "可能会发生的意外情景",
    dataIndex: "possible_accident",
    width: 200,
    align: "center",
  },
  {
    title: "emergencyplan.report_path",
    subTitle: "信息报告途径",
    dataIndex: "report_path",
    width: 160,
    align: "center",
  },
  {
    title: "emergencyplan.social_resource",
    subTitle: "社会依托资源资源",
    dataIndex: "social_resource",
    width: 200,
    align: "center",
  },
  {
    title: "emergencyplan.social_resource_contact",
    subTitle: "社会依托资源联系方式",
    dataIndex: "social_resource_contact",
    width: 200,
    align: "center",
  },
  {
    title: "emergencyplan.social_resource_estimate",
    subTitle: "社会依托资源需求估量",
    dataIndex: "social_resource_estimate",
    width: 200,
    align: "center",
  },
  {
    title: "emergencyplan.termination_condition",
    subTitle: "终止条件",
    dataIndex: "termination_condition",
    width: 160,
    align: "center",
  },
  {
    title: "emergencyplan.follow_up_requirements",
    subTitle: "后续管理要求",
    dataIndex: "follow_up_requirements",
    width: 160,
    align: "center",
  },
  // 应急预案
  {
    title: "emergencyplan.plan_config_id",
    subTitle: "专项应急预案名称",
    dataIndex: "plan_config_id",
    width: 200,
    align: "center",
  },
  {
    title: "emergencyplan.receiver",
    subTitle: "接收人",
    dataIndex: "receiver",
    width: 160,
    align: "center"
  },
  {
    title: "emergencyplan.principal",
    subTitle: "负责人",
    dataIndex: "principal",
    width: 160,
    align: "center"
  },
  {
    title: "emergencyplan.publisher",
    subTitle: "信息发布人",
    dataIndex: "publisher",
    width: 160,
    align: "center"
  },
  {
    title: "emergencyplan.decision_info",
    subTitle: "负责人及决策信息",
    dataIndex: "decision_info",
    width: 200,
    align: "center"
  }
];
