// 格式化金额：千分位，保留两位小数
export const formatAmount = (value: any): string => {
  if (value === null || value === undefined || value === '') {
    return '-';
  }
  const num = Number(value);
  if (isNaN(num)) {
    return '-';
  }
  return num.toLocaleString('zh-CN', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
};

export const configColumns = [
  {
    title: "compinfo.id",
    subTitle: "主键",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "主合同wbs项目定义",
    subTitle: "自辅06-项目编码",
    dataIndex: "wbs_code",
    width: 160,
    align: "center",
  },
  {
    title: "主合同编码",
    subTitle: "主合同编码",
    dataIndex: "income_info_contract_no",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.out_info_id",
    subTitle: "合同收入表ID",
    dataIndex: "out_info_id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.settlement_status",
    subTitle: "结算状态",
    dataIndex: "settlement_status",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.settlement_status",
    subTitle: "结算状态",
    dataIndex: "settlement_status_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.final_or_expected_settlement_amount",
    subTitle: "最终结算值/预计结算值",
    dataIndex: "final_or_expected_settlement_amount",
    width: 240,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.progress_settlement_current_year",
    subTitle: "本年办理",
    dataIndex: "progress_settlement_current_year",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.progress_settlement_total",
    subTitle: "累计办理",
    dataIndex: "progress_settlement_total",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.received_cash",
    subTitle: "货币资金",
    dataIndex: "received_cash",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.received_bill",
    subTitle: "票据",
    dataIndex: "received_bill",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.received_material",
    subTitle: "材料款",
    dataIndex: "received_material",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.received_other",
    subTitle: "其它",
    dataIndex: "received_other",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.received_subtotal",
    subTitle: "小计",
    dataIndex: "received_subtotal",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.book_payable_balance",
    subTitle: "账面应付款项余额",
    dataIndex: "book_payable_balance",
    width: 200,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.advance_payment_balance",
    subTitle: "预付款项余额",
    dataIndex: "advance_payment_balance",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.net_payable_amount",
    subTitle: "应付款项净额",
    dataIndex: "net_payable_amount",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.net_payable_current_year_available",
    subTitle: "本年具备支付条件金额",
    dataIndex: "net_payable_current_year_available",
    width: 240,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.net_payable_quality_and_deposit",
    subTitle: "质保金、结算资料押金",
    dataIndex: "net_payable_quality_and_deposit",
    width: 240,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.net_payable_after_year",
    subTitle: "年后付款金额",
    dataIndex: "net_payable_after_year",
    width: 200,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.net_payable_pending_writeoff",
    subTitle: "待结算后核销金额",
    dataIndex: "net_payable_pending_writeoff",
    width: 240,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.expected_remaining_payable",
    subTitle: "预计剩余应付款项",
    dataIndex: "expected_remaining_payable",
    width: 200,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.two_arrears_total_invoiced",
    subTitle: "累计开发票数",
    dataIndex: "two_arrears_total_invoiced",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.two_arrears_cost_not_invoiced",
    subTitle: "已列成本未开发票数",
    dataIndex: "two_arrears_cost_not_invoiced",
    width: 200,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.two_arrears_expected_payment_ratio",
    subTitle: "根据结算方式和工程进度情况已结算挂账部分应达到的付款比例",
    dataIndex: "two_arrears_expected_payment_ratio",
    width: 400,
    align: "center",
    render: (text: any) => <span>{text}%</span>,
  },
  {
    title: "compinfo.two_arrears_actual_payment_ratio",
    subTitle: "实际付款比例",
    dataIndex: "two_arrears_actual_payment_ratio",
    width: 160,
    align: "center",
    render: (text: any) => <span>{text}%</span>,
  },
  {
    title: "compinfo.two_arrears_remaining_by_ratio",
    subTitle: "按照付款比例尚欠款数",
    dataIndex: "two_arrears_remaining_by_ratio",
    width: 240,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.two_arrears_within_1_year",
    subTitle: "1年以内",
    dataIndex: "two_arrears_within_1_year",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.two_arrears_1_to_3_years",
    subTitle: "1-3年",
    dataIndex: "two_arrears_1_to_3_years",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.two_arrears_over_3_years",
    subTitle: "3年以上",
    dataIndex: "two_arrears_over_3_years",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.two_arrears_due_to_funds_shortage",
    subTitle: "其中因资金紧缺无法支付金额",
    dataIndex: "two_arrears_due_to_funds_shortage",
    width: 300,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "compinfo.two_arrears_reason_analysis",
    subTitle: "欠款原因分析",
    dataIndex: "two_arrears_reason_analysis",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contract_payment_clause",
    subTitle: "简述合同付款比例条款",
    dataIndex: "contract_payment_clause",
    width: 240,
    align: "center",
  },
  {
    title: "进度款结算比例（按合同额）",
    subTitle: "进度结算比例（按合同额）",
    dataIndex: "contract_progress_ratio_contract",
    width: 160,
    align: "center",
    render: (text: any) => <span>{text}%</span>,
  },
  {
    title: "进度款结算比例（按预算）",
    subTitle: "进度结算比例（按预算）",
    dataIndex: "contract_progress_ratio_budget",
    width: 160,
    align: "center",
    render: (text: any) => <span>{text}%</span>,
  },
  {
    title: "工程名称",
    subTitle: "工程名称",
    dataIndex: "contract_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.relative_person_code",
    subTitle: "单位编码",
    dataIndex: "relative_person_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.owner_unit_name",
    subTitle: "客户名称",
    dataIndex: "owner_unit_name",
    width: 160,
    align: "center",
  },
  {
    title: "合同额（元）",
    subTitle: "合同额（含税）",
    dataIndex: "contract_say_price",
    width: 160,
    align: "center",
    render: (text: any) => formatAmount(text),
  },
  {
    title: "分包合同号",
    subTitle: "合同号（分包采购等）",
    dataIndex: "contract_no",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.profit_center_code",
    subTitle: "利润中心编码",
    dataIndex: "profit_center_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.subletting_enroll_name",
    subTitle: "供应商名称",
    dataIndex: "subletting_enroll_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contract_category",
    subTitle: "合同分类",
    dataIndex: "contract_category",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.account_name",
    subTitle: "科目名称",
    dataIndex: "account_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.counterparty_risk",
    subTitle: "往来单位风险情况",
    dataIndex: "counterparty_risk",
    width: 200,
    align: "center",
  },
  {
    title: "compinfo.create_ts",
    subTitle: "制单时间",
    dataIndex: "create_ts",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_tz",
    subTitle: "制单时区",
    dataIndex: "create_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_user_code",
    subTitle: "制单人编码",
    dataIndex: "create_user_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_user_name",
    subTitle: "制单人姓名",
    dataIndex: "create_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_ts",
    subTitle: "修改时间",
    dataIndex: "modify_ts",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_tz",
    subTitle: "修改时区",
    dataIndex: "modify_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_user_code",
    subTitle: "修改人编码",
    dataIndex: "modify_user_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_user_name",
    subTitle: "修改人编码",
    dataIndex: "modify_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.dep_code",
    subTitle: "项目部编码",
    dataIndex: "dep_code",
    width: 160,
    align: "center",
  },
];
