export const configColumns = [
  {
    title: "compinfo.id",
    subTitle: "主键ID",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.out_info_id",
    subTitle: "分包合同id",
    dataIndex: "out_info_id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.type_code",
    subTitle: "分类(0:季度 ,1:月份)",
    dataIndex: "type_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_department",
    subTitle: "项目部",
    dataIndex: "project_department",
    width: 160,
    align: "center",
  },
  {
    title: "工程名称",
    subTitle: "工程名称",
    dataIndex: "contract_out_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.level1_process",
    subTitle: "一级流程/作业/专业/作业区域",
    dataIndex: "level1_process",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.level2_process",
    subTitle: "二级流程/专业内容/作业活动",
    dataIndex: "level2_process",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.level3_process",
    subTitle: "三级流程/工作步骤",
    dataIndex: "level3_process",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.major_risk_detail",
    subTitle: "重大风险具体内容（部位/区域/编号/数量/参数等）",
    dataIndex: "major_risk_detail",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.equipment_tool",
    subTitle: "设备/工具",
    dataIndex: "equipment_tool",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.hazard_type",
    subTitle: "危害因素类别",
    dataIndex: "hazard_type",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.company_area_supervisor",
    subTitle: "公司片区督导",
    dataIndex: "company_area_supervisor",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.risk_level",
    subTitle: "风险层级(0:项目部,1:分公司,2:公司)",
    dataIndex: "risk_level",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.risk_level",
    subTitle: "风险层级(0:项目部,1:分公司,2:公司)",
    dataIndex: "risk_level_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.plan_execute_time",
    subTitle: "计划实施时间",
    dataIndex: "plan_execute_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.plan_execute_time",
    subTitle: "计划实施时间",
    dataIndex: "plan_execute_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.dep_code",
    subTitle: "(项目部)",
    dataIndex: "dep_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_code",
    subTitle: "制单人编码",
    dataIndex: "form_maker_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_name",
    subTitle: "制单人名称",
    dataIndex: "form_maker_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_time",
    subTitle: "制单时间",
    dataIndex: "form_make_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_tz",
    subTitle: "制单时区",
    dataIndex: "form_make_tz",
    width: 160,
    align: "center",
  },
  {
    title: "二级单位",
    subTitle: "二级单位",
    dataIndex: "up_dep_name",
    width: 160,
    align: "center",
  },
  {
    title: "项目部",
    subTitle: "项目部",
    dataIndex: "dep_name",
    width: 160,
    align: "center",
  },
];
