export const configColumns = [
  {
    title: "InspectorSeniorityApply.sub_comp_code",
    subTitle: "分公司",
    dataIndex: "sub_comp_name",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.dep_code",
    subTitle: "项目部",
    dataIndex: "dep_name",
    width: 160,
    align: "center",
  },

  {
    title: "monitoringMeasuring.year",
    subTitle: "年份",
    dataIndex: "year",
    width: 160,
    align: "center",
  },
  {
    title: "建设单位名称 ",
    subTitle: "建设单位名称 ",
    dataIndex: "owner_name",
    width: 160,
    align: "center",
  },
  {
    title: "回访工程（产品）名称",
    subTitle: "回访工程（产品）名称",
    dataIndex: "contract_name",
    width: 210,
    align: "center",
  },
  {
    title: "竣工（交付）日期",
    subTitle: "竣工（交付）日期",
    dataIndex: "contract_end_date",
    width: 210,
    align: "center",
  },
  {
    title: "monitoringMeasuring.month",
    subTitle: "月份",
    dataIndex: "month",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.contract_no",
    subTitle: "合同编号",
    dataIndex: "contract_no",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.visit_date",
    subTitle: "回访时间",
    dataIndex: "visit_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.is_finish",
    subTitle: "完成情况",
    dataIndex: "is_finish",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.is_finish",
    subTitle: "完成情况",
    dataIndex: "is_finish_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.visit_unit",
    subTitle: "完成单位",
    dataIndex: "visit_unit",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.visit_person",
    subTitle: "回访人",
    dataIndex: "visit_person",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.responsible_person",
    subTitle: "责任人",
    dataIndex: "responsible_person",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.remark",
    subTitle: "备注",
    dataIndex: "remark",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_ts_str",
    subTitle: "创建时间",
    dataIndex: "create_ts_format",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_ts_str",
    subTitle: "创建时间",
    dataIndex: "create_ts_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_user_name",
    subTitle: "创建人名称",
    dataIndex: "create_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_ts_str",
    subTitle: "修改时间",
    dataIndex: "modify_ts_format",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_ts_str",
    subTitle: "修改时间",
    dataIndex: "modify_ts_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_user_name",
    subTitle: "修改人名称",
    dataIndex: "modify_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "levelConstructor.url",
    subTitle: "附件",
    dataIndex: "url",
    width: 160,
    align: "center",
  },
  {
    title: "common.status",
    subTitle: "审批状态",
    dataIndex: "approval_status",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_code",
    subTitle: "制单人编码",
    dataIndex: "form_maker_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_name",
    subTitle: "制单人名称",
    dataIndex: "form_maker_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_time",
    subTitle: "制单时间",
    dataIndex: "form_make_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_time",
    subTitle: "制单时间",
    dataIndex: "form_make_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_tz",
    subTitle: "制单时区",
    dataIndex: "form_make_tz",
    width: 160,
    align: "center",
  },
];