import { Tag } from 'antd';

export const configColumns = [
  {
    title: "compinfo.id",
    subTitle: "主键ID",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.problem_obs_code",
    subTitle: "问题来源",
    dataIndex: "problem_obs_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.problem_obs_code",
    subTitle: "问题来源",
    dataIndex: "problem_obs_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.examine_wbs_code",
    subTitle: "检查单位",
    dataIndex: "examine_wbs_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.examine_wbs_code",
    subTitle: "检查单位",
    dataIndex: "examine_wbs_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.upload_date",
    subTitle: "上传日期",
    dataIndex: "upload_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.upload_date",
    subTitle: "上传日期",
    dataIndex: "upload_date_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.branchCompName",
    subTitle: "分公司",
    dataIndex: "branch_comp_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.branchCompName",
    subTitle: "分公司",
    dataIndex: "branch_comp_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.wbsCode",
    subTitle: "项目部",
    dataIndex: "wbs_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.wbsCode",
    subTitle: "项目部",
    dataIndex: "wbs_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.project_name",
    subTitle: "工程名称",
    dataIndex: "project_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.check_date",
    subTitle: "检查日期",
    dataIndex: "check_date",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.check_date",
    subTitle: "检查日期",
    dataIndex: "check_date_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.problem_description",
    subTitle: "问题描述",
    dataIndex: "problem_description",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.problem_image_url",
    subTitle: "问题图片",
    dataIndex: "problem_image_url",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.problem_category",
    subTitle: "问题类别",
    dataIndex: "problem_category",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.problem_category",
    subTitle: "问题类别",
    dataIndex: "problem_category",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.problem_category",
    subTitle: "问题类别",
    dataIndex: "problem_category_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.question_category",
    subTitle: "问题类别",
    dataIndex: "question_category",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.question_category",
    subTitle: "问题类别",
    dataIndex: "question_category_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.problem_type",
    subTitle: "问题归类",
    dataIndex: "problem_type",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.problem_type",
    subTitle: "问题归类",
    dataIndex: "problem_type_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.quality_factor1",
    subTitle: "质量管理类一级要素",
    dataIndex: "quality_factor1",
    width: 200,
    align: "center",
    render: (text: any) => {
      return text ? text : <Tag color="red">不存在 质量管理类一级要素</Tag>;
    },
  },
  {
    title: "compinfo.quality_factor2",
    subTitle: "质量管理类二级要素",
    dataIndex: "quality_factor2",
    width: 200,
    align: "center",
    render: (text: any) => {
      return text ? text : <Tag color="red">不存在 质量管理类二级要素</Tag>;
    },
  },
  {
    title: "compinfo.entity_quality",
    subTitle: "质量实体类",
    dataIndex: "entity_quality",
    width: 160,
    align: "center",
    render: (text: any) => {
      return text ? text : <Tag color="red">不存在 质量实体类</Tag>;
    },
  },
  {
    title: "compinfo.entity_quality",
    subTitle: "质量实体类",
    dataIndex: "entity_quality_str",
    width: 160,
    align: "center",
    render: (text: any) => {
      return text ? text : <Tag color="red">不存在 质量实体类</Tag>;
    },
  },
  {
    title: "compinfo.operation_behavior_ids",
    subTitle: "作业行为类",
    dataIndex: "operation_behavior_ids",
    width: 160,
    align: "center",
    render: (text: any) => {
      return text ? text : <Tag color="red">不存在 作业行为类</Tag>;
    },
  },
  {
    title: "compinfo.operation_behavior_ids",
    subTitle: "作业行为类",
    dataIndex: "operation_behavior_str",
    width: 160,
    align: "center",
    render: (text: any) => {
      return text ? text : <Tag color="red">不存在 作业行为类</Tag>;
    },
  },
  {
    title: "compinfo.hour_num",
    subTitle: "检查时间 (小时数)",
    dataIndex: "hour_num",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.safety_factor1",
    subTitle: "安全管理类一级要素",
    dataIndex: "safety_factor1",
    width: 200,
    align: "center",
    render: (text: any) => {
      return text ? text : <Tag color="red">不存在 安全管理类一级要素</Tag>;
    },
  },
  {
    title: "compinfo.safety_factor2",
    subTitle: "安全管理类二级要素",
    dataIndex: "safety_factor2",
    width: 200,
    align: "center",
    render: (text: any) => {
      return text ? text : <Tag color="red">不存在 安全管理类二级要素</Tag>;
    },
  },
  {
    title: "compinfo.safety_radio",
    subTitle: "安全管理类符合程度",
    dataIndex: "safety_radio",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.responsible_unit",
    subTitle: "责任单位归属",
    dataIndex: "responsible_unit",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.responsible_unit",
    subTitle: "责任单位归属",
    dataIndex: "responsible_unit_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.violation_unit",
    subTitle: "具体违章单位名称",
    dataIndex: "violation_unit",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.severity_level",
    subTitle: "问题严重程度",
    dataIndex: "severity_level",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.severity_level",
    subTitle: "问题严重程度",
    dataIndex: "severity_level_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.system_belong",
    subTitle: "问题归属系统",
    dataIndex: "system_belong",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.system_belong",
    subTitle: "问题归属系统",
    dataIndex: "system_belong_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.verify_obs_code",
    subTitle: "项目验证部门",
    dataIndex: "verify_obs_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark",
    subTitle: "备注",
    dataIndex: "remark",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.tz",
    subTitle: "时区",
    dataIndex: "tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_code",
    subTitle: "制单人编码",
    dataIndex: "form_maker_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_maker_name",
    subTitle: "制单人名称",
    dataIndex: "form_maker_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_time",
    subTitle: "制单时间",
    dataIndex: "form_make_time",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.form_make_tz",
    subTitle: "制单时区",
    dataIndex: "form_make_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.precautionary_analysis_num",
    subTitle: "是否为不安全行为",
    dataIndex: "precautionary_analysis_num",
    width: 160,
    align: "center",
    render: (text: any) => {
      return text === 0 ? <Tag color="green">安全行为</Tag> : <Tag color="red">不安全行为</Tag>;
    },
  },
  {
    title: "compinfo.judgment_basis",
    subTitle: "判定依据",
    dataIndex: "judgment_basis",
    width: 160,
    align: "center",
  },
];
