export const configColumns = [
  {
    title: "wrokLicenseRegister.dep_reviewer",
    subTitle: "审查单位",
    dataIndex: "sub_comp_name",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.dep_reviewer",
    subTitle: "审查单位",
    dataIndex: "dep_name",
    width: 160,
    align: "center",
  },
  {
    title: "monitoringMeasuring.year",
    subTitle: "年份",
    dataIndex: "year",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.name",
    subTitle: "姓名",
    dataIndex: "name",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.gender",
    subTitle: "性别",
    dataIndex: "gender",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.birth_date",
    subTitle: "出生日期",
    dataIndex: "birth_date",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.job",
    subTitle: "职务",
    dataIndex: "job",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.job_title",
    subTitle: "职称",
    dataIndex: "job_title",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.work_date",
    subTitle: "参加工作时间",
    dataIndex: "work_date",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.education",
    subTitle: "文化程度",
    dataIndex: "education",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.employee_no",
    subTitle: "员工编号",
    dataIndex: "employee_no",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.graduation_school",
    subTitle: "毕业院校",
    dataIndex: "graduation_school",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.major",
    subTitle: "所学专业",
    dataIndex: "major",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.department",
    subTitle: "所在单位部门",
    dataIndex: "department",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.post",
    subTitle: "现从事岗位",
    dataIndex: "post",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.train_date",
    subTitle: "培训时间",
    dataIndex: "train_date",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.train_grade",
    subTitle: "培训成绩",
    dataIndex: "train_grade",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.application_project",
    subTitle: "申请操作项目",
    dataIndex: "application_project",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.phone",
    subTitle: "联系电话",
    dataIndex: "phone",
    width: 160,
    align: "center",
  },
  {
    title: "PersonnelApplyForm.on_duty",
    subTitle: "在岗状态",
    dataIndex: "on_duty",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.related_work_date",
    subTitle: "从事质检或相关工作时间",
    dataIndex: "related_work_date",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.apply_major",
    subTitle: "申请检查专业",
    dataIndex: "apply_major",
    width: 160,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.job_resume",
    subTitle: "工作简历",
    dataIndex: "job_resume",
    width: 210,
    align: "center",
  },
  {
    title: "InspectorSeniorityApply.approval_date",
    subTitle: "审批时间",
    dataIndex: "approval_date",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.remark",
    subTitle: "备注",
    dataIndex: "remark",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_ts_str",
    subTitle: "创建时间",
    dataIndex: "create_ts_format",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_ts_str_reviewer",
    subTitle: "审查日期",
    dataIndex: "create_ts_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.create_user_name_reviewer",
    subTitle: "审查人",
    dataIndex: "create_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_ts_str",
    subTitle: "修改时间",
    dataIndex: "modify_ts_format",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_ts_str",
    subTitle: "修改时间",
    dataIndex: "modify_ts_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.modify_user_name",
    subTitle: "修改人名称",
    dataIndex: "modify_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "levelConstructor.url",
    subTitle: "附件",
    dataIndex: "url",
    width: 160,
    align: "center",
  },
  {
    title: "common.status",
    subTitle: "审批状态",
    dataIndex: "approval_status",
    width: 160,
    align: "center",
  },

  {
    title: "wrokLicenseRegister.qualification_change",
    subTitle: "实验室资质范围、有效期的变化情况",
    dataIndex: "qualification_change",
    width: 360,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.data_reliability",
    subTitle: "数据可靠性",
    dataIndex: "data_reliability",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.data_reliability",
    subTitle: "数据可靠性",
    dataIndex: "data_reliability_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.service_quality",
    subTitle: "服务质量",
    dataIndex: "service_quality",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.contract_performance",
    subTitle: "合同履约",
    dataIndex: "contract_performance",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.service_quality",
    subTitle: "服务质量",
    dataIndex: "service_quality_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.contract_performance",
    subTitle: "合同履约",
    dataIndex: "contract_performance_str",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.reviewer",
    subTitle: "审查人姓名",
    dataIndex: "reviewer",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.review_date",
    subTitle: "审查日期",
    dataIndex: "review_date",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.review_unit",
    subTitle: "审查单位",
    dataIndex: "review_unit",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.is_choose",
    subTitle: "下年度是否选用",
    dataIndex: "is_choose",
    width: 160,
    align: "center",
  },
  {
    title: "wrokLicenseRegister.is_choose",
    subTitle: "下年度是否选用",
    dataIndex: "is_choose_str",
    width: 160,
    align: "center",
  },
];
/**
   * 工作简历表格列配置
   */
export const resumeColumns = [
  {
    title: '开始时间',
    dataIndex: 'time_start',
    key: 'time_start',
    width: 120,
    render: (text: string) => text || '-',
  },
  {
    title: '结束时间',
    dataIndex: 'time_end',
    key: 'time_end',
    width: 120,
    render: (text: string) => text || '-',
  },
  {
    title: '工作单位',
    dataIndex: 'company',
    key: 'company',
    width: 200,
    render: (text: string) => text || '-',
  },
  {
    title: '工作经历和业绩',
    dataIndex: 'experience',
    key: 'experience',
    width: 300,
    render: (text: string) => text || '-',
  },
];
