export const configColumns = [
  {
    title: "scoringPersonnel.RowNumber",
    subTitle: "序号",
    dataIndex: "RowNumber",
    width: 160,
    align: "center",
  },
  {
    title: "scoringPersonnel.id",
    subTitle: "序号",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "scoringPersonnel.unit_code",
    subTitle: "单位",
    dataIndex: "unit_code",
    width: 160,
    align: "center",
  },
  {
    title: "scoringPersonnel.unit_code",
    subTitle: "单位",
    dataIndex: "unit_name",
    width: 160,
    align: "center",
  },
  {
    title: "scoringPersonnel.project_name",
    subTitle: "工程名称",
    dataIndex: "project_name",
    width: 160,
    align: "center",
  },
  {
    title: "scoringPersonnel.dept_name",
    subTitle: "部门/队伍名称",
    dataIndex: "dept_name",
    width: 160,
    align: "center",
  },
  {
    title: "scoringPersonnel.person_name",
    subTitle: "姓名",
    dataIndex: "person_name",
    width: 160,
    align: "center",
  },
  {
    title: "scoringPersonnel.gender",
    subTitle: "性别",
    dataIndex: "gender",
    width: 160,
    align: "center",
  },
  {
    title: "scoringPersonnel.birth_date",
    subTitle: "出生日期",
    dataIndex: "birth_date",
    width: 160,
    align: "center",
  },
  {
    title: "scoringPersonnel.position_level",
    subTitle: "职级",
    dataIndex: "position_level",
    width: 160,
    align: "center",
  },
  {
    title: "scoringPersonnel.title_level",
    subTitle: "职称级别",
    dataIndex: "title_level",
    width: 160,
    align: "center",
  },
  {
    title: "scoringPersonnel.position_level",
    subTitle: "职级",
    dataIndex: "position_level_name",
    width: 160,
    align: "center",
  },
  {
    title: "scoringPersonnel.title_level",
    subTitle: "职称级别",
    dataIndex: "title_level_name",
    width: 160,
    align: "center",
  },
  {
    title: "scoringPersonnel.person_code",
    subTitle: "人员编号",
    dataIndex: "person_code",
    width: 160,
    align: "center",
  },
  {
    title: "scoringPersonnel.scoring_object_type",
    subTitle: "记分对象类别",
    dataIndex: "scoring_object_type",
    width: 160,
    align: "center",
  },
  {
    title: "scoringPersonnel.scoring_object_type",
    subTitle: "记分对象类别",
    dataIndex: "scoring_object_name",
    width: 160,
    align: "center",
  },
  {
    title: "scoringPersonnel.scoring_score",
    subTitle: "记分分数",
    dataIndex: "scoring_score",
    width: 160,
    align: "center",
  },
  {
    title: "scoringPersonnel.scoring_reason",
    subTitle: "记分原因",
    dataIndex: "scoring_reason",
    width: 160,
    align: "center",
  },
  {
    title: "scoringPersonnel.penalty_amount",
    subTitle: "处罚罚金（个人）",
    dataIndex: "penalty_amount",
    width: 230,
    align: "center",
  },
  {
    title: "scoringPersonnel.penalty_voucher",
    subTitle: "罚款凭证",
    dataIndex: "penalty_voucher",
    width: 160,
    align: "center",
  },
  {
    title: "scoringPersonnel.block_situation",
    subTitle: "拉黑情况",
    dataIndex: "block_situation",
    width: 160,
    align: "center",
  },
  {
    title: "scoringPersonnel.nature_problem",
    subTitle: "问题性质",
    dataIndex: "nature_problem",
    width: 160,
    align: "center",
  },
  {
    title: "scoringPersonnel.problem_description",
    subTitle: "问题描述字段",
    dataIndex: "problem_description",
    width: 160,
    align: "center",
  },
  {
    title: "scoringPersonnel.contractor_penalty_amount",
    subTitle: "惩罚金额（承包商）",
    dataIndex: "contractor_penalty_amount",
    width: 230,
    align: "center",
  },
  {
    title: "scoringPersonnel.unit_code",
    subTitle: "单位",
    dataIndex: "branch_comp_code",
    width: 160,
    align: "center",
  },
  {
    title: "scoringPersonnel.unit_code",
    subTitle: "单位",
    dataIndex: "branch_comp_name",
    width: 160,
    align: "center",
  },
];
