export const materialsColumns = [
  {
    title: "标段编号",
    subTitle: "标段编号",
    dataIndex: "lot_no",
    width: 160,
    align: "center",
  },
  {
    title: "采购进度计划编号",
    subTitle: "采购进度计划编号",
    dataIndex: "schedule_form_no",
    width: 160,
    align: "center",
  },
  {
    title: "总体策略编号",
    subTitle: "总体策略编号",
    dataIndex: "main_form_no",
    width: 160,
    align: "center",
  },
  {
    title: "标段名称",
    subTitle: "标段名称(从附件1传值)",
    dataIndex: "lot_name",
    width: 160,
    align: "center",
  },
  {
    title: "物资性质",
    subTitle: "物资性质(0:长周期物资,1:关键物资,2:其他)",
    dataIndex: "materials_type",
    width: 160,
    align: "center",
  },
  {
    title: "物资性质",
    subTitle: "物资性质(0:长周期物资,1:关键物资,2:其他)",
    dataIndex: "materials_type_str",
    width: 160,
    align: "center",
  },
  {
    title: "业主受控",
    subTitle: "业主受控(0:甲定乙采,1:甲控乙采,2:乙采,3:/)",
    dataIndex: "is_owner_controlled",
    width: 160,
    align: "center",
  },
  {
    title: "业主受控",
    subTitle: "业主受控(0:甲定乙采,1:甲控乙采,2:乙采,3:/)",
    dataIndex: "is_owner_controlled_str",
    width: 160,
    align: "center",
  },
  {
    title: "管控级别",
    subTitle: "管控级别(0:集团公司工程和物装管理部,1:中油工程,2:/)",
    dataIndex: "control_level",
    width: 160,
    align: "center",
  },
  {
    title: "管控级别",
    subTitle: "管控级别(0:集团公司工程和物装管理部,1:中油工程,2:/)",
    dataIndex: "control_level_str",
    width: 160,
    align: "center",
  },
  {
    title: "采购编号(RFQ NO.)",
    subTitle: "采购编号(RFQ NO.)",
    dataIndex: "rfq_no",
    width: 160,
    align: "center",
  },
  {
    title: "成本控制区间(CNY万元)",
    subTitle: "成本控制区间(CNY万元)",
    dataIndex: "cost_control_range",
    width: 160,
    align: "center",
  },
  {
    title: "13034品名编码",
    subTitle: "13034品名编码",
    dataIndex: "item_code",
    width: 160,
    align: "center",
  },
  {
    title: "物资等级",
    subTitle: "物资等级(物资专用)(0:一级,1:二级)",
    dataIndex: "material_grade",
    width: 160,
    align: "center",
  },
  {
    title: "物资等级",
    subTitle: "物资等级(物资专用)(0:一级,1:二级)",
    dataIndex: "material_grade_str",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.source_reason_desc",
    subTitle: "寻源供应商背景信息及推荐理由",
    dataIndex: "source_reason_desc",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.legal_basis",
    subTitle: "采购方式依法合规依据",
    dataIndex: "legal_basis",
    width: 160,
    align: "center",
  },
  {
    title: "技术合格 经评审最低投标价法",
    subTitle: "技术合格 经评审最低投标价法",
    dataIndex: "method_summary_technology",
    width: 160,
    align: "center",
  },
  {
    title: "综合评分法",
    subTitle: "综合评分法",
    dataIndex: "method_summary_total",
    width: 160,
    align: "center",
  },
  {
    title: "现场需求时间",
    subTitle: "现场需求时间",
    dataIndex: "site_demand_time",
    width: 160,
    align: "center",
  },
    {
    title: "现场需求时间",
    subTitle: "现场需求时间",
    dataIndex: "site_demand_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "工程物资交付条件(成交交付要求)",
    subTitle: "工程物资交付条件(成交交付要求)",
    dataIndex: "delivery_terms_dom",
    width: 160,
    align: "center",
  },
  {
    title: "工程物资交付条件(国际贸易术语)",
    subTitle: "工程物资交付条件(国际贸易术语)",
    dataIndex: "delivery_terms_intl",
    width: 160,
    align: "center",
  },
  {
    title: "付款条款",
    subTitle: "付款条款",
    dataIndex: "payment_terms",
    width: 160,
    align: "center",
  },
  {
    title: "保函条款(预付款保函)",
    subTitle: "保函条款(预付款保函)",
    dataIndex: "guarantee_prepay",
    width: 160,
    align: "center",
  },
  {
    title: "保函条款(履约保函)",
    subTitle: "保函条款(履约保函)",
    dataIndex: "guarantee_perf",
    width: 160,
    align: "center",
  },
  {
    title: "保函条款(质保保函)",
    subTitle: "保函条款(质保保函)",
    dataIndex: "guarantee_quality",
    width: 160,
    align: "center",
  },
  {
    title: "质保期要求",
    subTitle: "质保期要求",
    dataIndex: "warranty_period_req",
    width: 160,
    align: "center",
  },
  {
    title: "废标条件",
    subTitle: "废标条件",
    dataIndex: "disqualify_criteria",
    width: 160,
    align: "center",
  },
  {
    title: "其他要素",
    subTitle: "其他要素",
    dataIndex: "other_elements",
    width: 160,
    align: "center",
  },
  {
    title: "备注",
    subTitle: "备注",
    dataIndex: "remark",
    width: 160,
    align: "center",
  },
  {
    title: "拟推荐供应商名称",
    subTitle: "拟推荐单位名称(分别填写内容 供应商名称,承包商名称,服务商名称 )",
    dataIndex: "supplier_name",
    width: 160,
    align: "center",
  },
  {
    title: "供应商来源",
    subTitle: "单位来源(0:ITB,1:AVL,2:业主信函,3:寻源（背调及推荐理由见下方）)",
    dataIndex: "supplier_source",
    width: 160,
    align: "center",
  },
  {
    title: "原产地要求",
    subTitle: "原产地要求(物资专用)",
    dataIndex: "origin_requirement",
    width: 160,
    align: "center",
  },
  {
    title: "供应商一般往来单位编码",
    subTitle: "单位编码(供应商/承包商/服务商编码)",
    dataIndex: "supplier_code",
    width: 160,
    align: "center",
  },
  {
    title: "供应商类别",
    subTitle: "单位类别(0:制造商,1:代理商（制造商授权书见附件）,2:贸易商,3:集成商（OEM资质文件件附件）,4:其他（参见备注详细描述）)",
    dataIndex: "supplier_category",
    width: 160,
    align: "center",
  },
  {
    title: "采购方式",
    subTitle: "采购方式(0:公开招标,1:邀请招标,2:公开询比采购,3:邀请询比采购,4:公开谈判采购,5:邀请谈判采购,6:直接采购,7:目录采购,8:执行集采结果)",
    dataIndex: "procurement_method",
    width: 160,
    align: "center",
  },
  {
    title: "采购方式",
    subTitle: "采购方式(0:公开招标,1:邀请招标,2:公开询比采购,3:邀请询比采购,4:公开谈判采购,5:邀请谈判采购,6:直接采购,7:目录采购,8:执行集采结果)",
    dataIndex: "procurement_method_str",
    width: 160,
    align: "center",
  },
  {
    title: "评审方式",
    subTitle: "评审方式(0:技术合格 经评审最低投标价法,1:综合评分法)",
    dataIndex: "eval_method",
    width: 160,
    align: "center",
  },
  {
    title: "评审方式",
    subTitle: "评审方式(0:技术合格 经评审最低投标价法,1:综合评分法)",
    dataIndex: "eval_method_str",
    width: 160,
    align: "center",
  },
  {
    title: "分标信息",
    subTitle: "分标信息(0:允许,1:不允许)",
    dataIndex: "lot_division",
    width: 160,
    align: "center",
  },
  {
    title: "拟成交人数量",
    subTitle: "拟成交人数量",
    dataIndex: "proposed_qty",
    width: 160,
    align: "center",
  },
  {
    title: "币种",
    subTitle: "币种",
    dataIndex: "currency",
    width: 160,
    align: "center",
  },
  {
    title: "采购执行单位",
    subTitle: "采购执行单位",
    dataIndex: "purchase_obs_code",
    width: 160,
    align: "center",
  },
];

export const subcontractColumns = [
  {
    title: "标段编号",
    subTitle: "标段编号(从附件1传值)",
    dataIndex: "lot_no",
    width: 160,
    align: "center",
  },
  {
    title: "采购进度计划编号",
    subTitle: "采购进度计划编号",
    dataIndex: "schedule_form_no",
    width: 160,
    align: "center",
  },
  {
    title: "总体策略编号",
    subTitle: "总体策略编号",
    dataIndex: "main_form_no",
    width: 160,
    align: "center",
  },
  {
    title: "标段名称",
    subTitle: "标段名称(从附件1传值)",
    dataIndex: "lot_name",
    width: 160,
    align: "center",
  },
  {
    title: "采购包类型",
    subTitle: "采购包类型",
    dataIndex: "package_type",
    width: 160,
    align: "center",
  },
  {
    title: "管控级别",
    subTitle: "管控级别(0:集团公司工程和物装管理部,1:中油工程,2:/)",
    dataIndex: "control_level",
    width: 160,
    align: "center",
  },
  {
    title: "管控级别",
    subTitle: "管控级别(0:集团公司工程和物装管理部,1:中油工程,2:/)",
    dataIndex: "control_level_str",
    width: 160,
    align: "center",
  },
  {
    title: "采购编号(RFQ NO.)",
    subTitle: "采购编号(RFQ NO.)",
    dataIndex: "rfq_no",
    width: 160,
    align: "center",
  },
  {
    title: "成本控制区间(CNY万元)",
    subTitle: "成本控制区间(CNY万元)",
    dataIndex: "cost_control_range",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.source_reason_desc",
    subTitle: "寻源供应商背景信息及推荐理由",
    dataIndex: "source_reason_desc",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.legal_basis",
    subTitle: "采购方式依法合规依据",
    dataIndex: "legal_basis",
    width: 160,
    align: "center",
  },
  {
    title: "技术合格 经评审最低投标价法",
    subTitle: "技术合格 经评审最低投标价法",
    dataIndex: "method_summary_technology",
    width: 160,
    align: "center",
  },
  {
    title: "综合评分法",
    subTitle: "综合评分法",
    dataIndex: "method_summary_total",
    width: 160,
    align: "center",
  },
  {
    title: "现场需求时间",
    subTitle: "现场需求时间",
    dataIndex: "site_demand_time",
    width: 160,
    align: "center",
  },
    {
    title: "现场需求时间",
    subTitle: "现场需求时间",
    dataIndex: "site_demand_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "付款条款",
    subTitle: "付款条款",
    dataIndex: "payment_terms",
    width: 160,
    align: "center",
  },
  {
    title: "保函条款(预付款保函)",
    subTitle: "保函条款(预付款保函)",
    dataIndex: "guarantee_prepay",
    width: 160,
    align: "center",
  },
  {
    title: "保函条款(履约保函)",
    subTitle: "保函条款(履约保函)",
    dataIndex: "guarantee_perf",
    width: 160,
    align: "center",
  },
  {
    title: "保函条款(质保保函)",
    subTitle: "保函条款(质保保函)",
    dataIndex: "guarantee_quality",
    width: 160,
    align: "center",
  },
  {
    title: "质保期要求",
    subTitle: "质保期要求",
    dataIndex: "warranty_period_req",
    width: 160,
    align: "center",
  },
  {
    title: "废标条件",
    subTitle: "废标条件",
    dataIndex: "disqualify_criteria",
    width: 160,
    align: "center",
  },
  {
    title: "其他要素",
    subTitle: "其他要素",
    dataIndex: "other_elements",
    width: 160,
    align: "center",
  },
  {
    title: "是否允许成交商再分包",
    subTitle: "是否允许成交商再分包(分包专用)(0:不允许,1:允许)",
    dataIndex: "is_sub_allowed",
    width: 160,
    align: "center",
  },
  {
    title: "再分包理由",
    subTitle: "再分包理由(分包专用)",
    dataIndex: "sub_allowed_reason",
    width: 160,
    align: "center",
  },
  {
    title: "备注",
    subTitle: "备注",
    dataIndex: "remark",
    width: 160,
    align: "center",
  },
  {
    title: "拟推荐承包商名称",
    subTitle: "拟推荐单位名称(分别填写内容 供应商名称,承包商名称,服务商名称 )",
    dataIndex: "supplier_name",
    width: 160,
    align: "center",
  },
  {
    title: "承包商来源",
    subTitle: "单位来源(0:ITB,1:AVL,2:业主信函,3:寻源（背调及推荐理由见下方）)",
    dataIndex: "supplier_source",
    width: 160,
    align: "center",
  },
  {
    title: "承包商注册地",
    subTitle: "承包商注册地",
    dataIndex: "supplier_reg_addr",
    width: 160,
    align: "center",
  },
  {
    title: "集团承包商资源库编码",
    subTitle: "集团承包商资源库编码",
    dataIndex: "supplier_code",
    width: 160,
    align: "center",
  },
  // {
  //   title: "compinfo.supplier_category",
  //   subTitle: "单位类别(0:制造商,1:代理商（制造商授权书见附件）,2:贸易商,3:集成商（OEM资质文件件附件）,4:其他（参见备注详细描述）)",
  //   dataIndex: "qualification_category",
  //   width: 160,
  //   align: "center",
  // },
  {
    title: "采购方式",
    subTitle: "采购方式(0:公开招标,1:邀请招标,2:公开询比采购,3:邀请询比采购,4:公开谈判采购,5:邀请谈判采购,6:直接采购,7:目录采购,8:执行集采结果)",
    dataIndex: "procurement_method",
    width: 160,
    align: "center",
  },
  {
    title: "采购方式",
    subTitle: "采购方式(0:公开招标,1:邀请招标,2:公开询比采购,3:邀请询比采购,4:公开谈判采购,5:邀请谈判采购,6:直接采购,7:目录采购,8:执行集采结果)",
    dataIndex: "procurement_method_str",
    width: 160,
    align: "center",
  },
  {
    title: "评审方式",
    subTitle: "评审方式(0:技术合格 经评审最低投标价法,1:综合评分法)",
    dataIndex: "eval_method",
    width: 160,
    align: "center",
  },
  {
    title: "评审方式",
    subTitle: "评审方式(0:技术合格 经评审最低投标价法,1:综合评分法)",
    dataIndex: "eval_method_str",
    width: 160,
    align: "center",
  },
  {
    title: "分标信息",
    subTitle: "分标信息(0:允许,1:不允许)",
    dataIndex: "lot_division",
    width: 160,
    align: "center",
  },
  {
    title: "拟成交人数量",
    subTitle: "拟成交人数量",
    dataIndex: "proposed_qty",
    width: 160,
    align: "center",
  },
  {
    title: "币种",
    subTitle: "币种",
    dataIndex: "currency",
    width: 160,
    align: "center",
  },
  {
    title: "采购执行单位",
    subTitle: "采购执行单位",
    dataIndex: "purchase_obs_code",
    width: 160,
    align: "center",
  },
];

export const serviceColumns = [
  {
    title: "标段编号",
    subTitle: "标段编号",
    dataIndex: "lot_no",
    width: 160,
    align: "center",
  },
  {
    title: "采购进度计划编号",
    subTitle: "采购进度计划编号",
    dataIndex: "schedule_form_no",
    width: 160,
    align: "center",
  },
  {
    title: "总体策略编号",
    subTitle: "总体策略编号",
    dataIndex: "main_form_no",
    width: 160,
    align: "center",
  },
  {
    title: "标段名称",
    subTitle: "标段名称(从附件1传值)",
    dataIndex: "lot_name",
    width: 160,
    align: "center",
  },
  {
    title: "采购包类型",
    subTitle: "采购包类型",
    dataIndex: "package_type",
    width: 160,
    align: "center",
  },
  {
    title: "采购编号(RFQ NO.)",
    subTitle: "采购编号(RFQ NO.)",
    dataIndex: "rfq_no",
    width: 160,
    align: "center",
  },
  {
    title: "成本控制区间(CNY万元)",
    subTitle: "成本控制区间(CNY万元)",
    dataIndex: "cost_control_range",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.source_reason_desc",
    subTitle: "寻源供应商背景信息及推荐理由",
    dataIndex: "source_reason_desc",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.legal_basis",
    subTitle: "采购方式依法合规依据",
    dataIndex: "legal_basis",
    width: 160,
    align: "center",
  },
  {
    title: "技术合格 经评审最低投标价法",
    subTitle: "技术合格 经评审最低投标价法",
    dataIndex: "method_summary_technology",
    width: 160,
    align: "center",
  },
  {
    title: "综合评分法",
    subTitle: "综合评分法",
    dataIndex: "method_summary_total",
    width: 160,
    align: "center",
  },
  {
    title: "现场需求时间",
    subTitle: "现场需求时间",
    dataIndex: "site_demand_time",
    width: 160,
    align: "center",
  },
    {
    title: "现场需求时间",
    subTitle: "现场需求时间",
    dataIndex: "site_demand_time_str",
    width: 160,
    align: "center",
  },
  {
    title: "付款条款",
    subTitle: "付款条款",
    dataIndex: "payment_terms",
    width: 160,
    align: "center",
  },
  {
    title: "保函条款(预付款保函)",
    subTitle: "保函条款(预付款保函)",
    dataIndex: "guarantee_prepay",
    width: 160,
    align: "center",
  },
  {
    title: "保函条款(履约保函)",
    subTitle: "保函条款(履约保函)",
    dataIndex: "guarantee_perf",
    width: 160,
    align: "center",
  },
  {
    title: "保函条款(质保保函)",
    subTitle: "保函条款(质保保函)",
    dataIndex: "guarantee_quality",
    width: 160,
    align: "center",
  },
  {
    title: "质保期要求",
    subTitle: "质保期要求",
    dataIndex: "warranty_period_req",
    width: 160,
    align: "center",
  },
  {
    title: "废标条件",
    subTitle: "废标条件",
    dataIndex: "disqualify_criteria",
    width: 160,
    align: "center",
  },
  {
    title: "其他要素",
    subTitle: "其他要素",
    dataIndex: "other_elements",
    width: 160,
    align: "center",
  },
  {
    title: "备注",
    subTitle: "备注",
    dataIndex: "remark",
    width: 160,
    align: "center",
  },
  {
    title: "拟推荐服务商名称",
    subTitle: "拟推荐单位名称(分别填写内容 供应商名称,承包商名称,服务商名称 )",
    dataIndex: "supplier_name",
    width: 160,
    align: "center",
  },
  {
    title: "服务商来源",
    subTitle: "单位来源(0:ITB,1:AVL,2:业主信函,3:寻源（背调及推荐理由见下方）)",
    dataIndex: "supplier_source",
    width: 160,
    align: "center",
  },
  {
    title: "服务商注册地",
    subTitle: "服务商注册地",
    dataIndex: "supplier_reg_addr",
    width: 160,
    align: "center",
  },
  {
    title: "EMP 2.0服务商编码",
    subTitle: "单位编码(供应商/承包商/服务商编码)",
    dataIndex: "supplier_code",
    width: 160,
    align: "center",
  },
  {
    title: "采购方式",
    subTitle: "采购方式(0:公开招标,1:邀请招标,2:公开询比采购,3:邀请询比采购,4:公开谈判采购,5:邀请谈判采购,6:直接采购,7:目录采购,8:执行集采结果)",
    dataIndex: "procurement_method",
    width: 160,
    align: "center",
  },
  {
    title: "采购方式",
    subTitle: "采购方式(0:公开招标,1:邀请招标,2:公开询比采购,3:邀请询比采购,4:公开谈判采购,5:邀请谈判采购,6:直接采购,7:目录采购,8:执行集采结果)",
    dataIndex: "procurement_method_str",
    width: 160,
    align: "center",
  },
  {
    title: "评审方式",
    subTitle: "评审方式(0:技术合格 经评审最低投标价法,1:综合评分法)",
    dataIndex: "eval_method",
    width: 160,
    align: "center",
  },
  {
    title: "评审方式",
    subTitle: "评审方式(0:技术合格 经评审最低投标价法,1:综合评分法)",
    dataIndex: "eval_method_str",
    width: 160,
    align: "center",
  },
  {
    title: "分标信息",
    subTitle: "分标信息(0:允许,1:不允许)",
    dataIndex: "lot_division",
    width: 160,
    align: "center",
  },
  {
    title: "拟成交人数量",
    subTitle: "拟成交人数量",
    dataIndex: "proposed_qty",
    width: 160,
    align: "center",
  },
  {
    title: "币种",
    subTitle: "币种",
    dataIndex: "currency",
    width: 160,
    align: "center",
  },
  {
    title: "采购执行单位",
    subTitle: "采购执行单位",
    dataIndex: "purchase_obs_code",
    width: 160,
    align: "center",
  },
];