export const configColumns = [
  {
    title: "compinfo.id",
    subTitle: "项目唯一ID",
    dataIndex: "id",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.dep_code",
    subTitle: "WBS项目部",
    dataIndex: "dep_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.item_key",
    subTitle: "项目名称编码",
    dataIndex: "item_key",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.item_name",
    subTitle: "项目名称，如“营业总收入”",
    dataIndex: "item_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.sort_order",
    subTitle: "同级项目的排序号",
    dataIndex: "sort_order",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.year",
    subTitle: "年份",
    dataIndex: "year",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.q1_month1",
    subTitle: "1月份",
    dataIndex: "q1_month1",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.q1_month2",
    subTitle: "2月份",
    dataIndex: "q1_month2",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.q1_month3",
    subTitle: "3月份",
    dataIndex: "q1_month3",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.q1_subtotal",
    subTitle: "1季度",
    dataIndex: "q1_subtotal",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.q2_month1",
    subTitle: "4月份",
    dataIndex: "q2_month1",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.q2_month2",
    subTitle: "5月份",
    dataIndex: "q2_month2",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.q2_month3",
    subTitle: "6月份",
    dataIndex: "q2_month3",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.q2_subtotal",
    subTitle: "2季度",
    dataIndex: "q2_subtotal",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.q3_month1",
    subTitle: "7月份",
    dataIndex: "q3_month1",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.q3_month2",
    subTitle: "8月份",
    dataIndex: "q3_month2",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.q3_month3",
    subTitle: "9月份",
    dataIndex: "q3_month3",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.q3_subtotal",
    subTitle: "3季度",
    dataIndex: "q3_subtotal",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.q4_month1",
    subTitle: "10月份",
    dataIndex: "q4_month1",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.q4_month2",
    subTitle: "11月份",
    dataIndex: "q4_month2",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.q4_month3",
    subTitle: "12月份",
    dataIndex: "q4_month3",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.q4_subtotal",
    subTitle: "4季度",
    dataIndex: "q4_subtotal",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.full_year_amount",
    subTitle: "全年预测",
    dataIndex: "full_year_amount",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.indicator_amount",
    subTitle: "指标数",
    dataIndex: "indicator_amount",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.remark",
    subTitle: "备注",
    dataIndex: "remark",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_ts",
    subTitle: "创建时间",
    dataIndex: "create_ts",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_tz",
    subTitle: "创建时区",
    dataIndex: "create_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_user_code",
    subTitle: "创建人编码",
    dataIndex: "create_user_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.create_user_name",
    subTitle: "创建人名称",
    dataIndex: "create_user_name",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_ts",
    subTitle: "修改时间",
    dataIndex: "modify_ts",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_tz",
    subTitle: "修改时区",
    dataIndex: "modify_tz",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_user_code",
    subTitle: "修改人编码",
    dataIndex: "modify_user_code",
    width: 160,
    align: "center",
  },
  {
    title: "compinfo.modify_user_name",
    subTitle: "修改人名称",
    dataIndex: "modify_user_name",
    width: 160,
    align: "center",
  },
];
